### ISSUE TITLE
Single cell analysis sample annotation

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1003]
Hello and thanks for such a great tool,

 I am wondering how it is best to annotate single cell samples when using the LFQ-MBR workflow. I also have 100 cell libraries and blank samples that were run in the same experiment. Should single cells be in the same experiment, libraries in their own, ect? 

For the MBR, I saw in a presentation that one can select which samples to be used as libraries so that MBR performs better. How can this be done? Will this detract if there are peptides in single cells which are not identified in the 100 cell libraries? 

Finally, if running Fragpipe with single cells, 100 cell libraries, and blanks, should normalization be used? From my results it looks like this skews the intensities in the blank samples. Does the same apply for the MaxLFQ intensities?

Thanks,
Ronnie

**Comment by fcyu** [comment]
Hi Ronnie,

Thank you for your interest in our tools.

Supposing you have two blank runs, three 1-cell runs, and four 100-cell runs. You can have

| Path           | Experiment | Bioreplicate | Data type |   |
|----------------|------------|--------------|-----------|---|
| blank_a.mzML   | blank      | 1            | DDA       |   |
| blank_b.mzML   | blank      | 2            | DDA       |   |
| cell1_a.mzML   | cell1      | 3            | DDA       |   |
| cell1_b.mzML   | cell1      | 4            | DDA       |   |
| cell1_c.mzML   | cell1      | 5            | DDA       |   |
| cell100_a.mzML | lib        |              | DDA       |   |
| cell100_b.mzML | lib        |              | DDA       |   |
| cell100_c.mzML | lib        |              | DDA       |   |
| cell100_d.mzML | lib        |              | DDA       |   |

For the `Bioreplicate`, you can have `1,2`, and `1,2,3` if you are not going to use MSstats as downstream analysis. Runs with experiment names starting with `lib` will be treated as library runs, and will not be used in normalization and MaxLFQ.

> Will this detract if there are peptides in single cells which are not identified in the 100 cell libraries?

The peptides only in the single cell runs will be detected by MS/MS matches if the quality is high.

> if running Fragpipe with single cells, 100 cell libraries, and blanks, should normalization be used?

I think normalization should be enabled.

>  From my results it looks like this skews the intensities in the blank samples. Does the same apply for the MaxLFQ intensities?

Can you try assigning the library runs to `lib` experiments so that they won't be included in the normalization and MaxLFQ?

Best,

Fengchao

**Comment by cutleraging** [comment]
Great, let me try this. Thanks a lot!
