### ISSUE TITLE
glyco errors

### ISSUE THREAD

**Issue by lbeer272** [Nesvilab/FragPipe#1013]
- Describe the issue or question:
Hello,  I am trying to run some test glyco workflows and am having some problems. 

1.)First, I am running the glyco-N-LFQ to test a mouse dataset, using the default glycan database and Uniprot database. 

I am getting an error of "Failed to correct the modification mass...". Log file (log_2023-02-22_12-26-46_QuantError.txt) attached.

2.) Another problem that I encountered was when running a glyco-N-HCD workflow for a human file, and  loaded the pGlyco-N-Human.gdb glycan database (added 695 glycans).  The search seems to hang up on the "Begin glycan assignment" step. I have left it running over 24 hrs with no result, so I am wondering if  there is a problem with the way the workflow is set up. (log_2023-02-21_11-35-22_partial.txt)

Thank you.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-02-22_12-26-46_QuantError.txt](https://github.com/Nesvilab/FragPipe/files/10806785/log_2023-02-22_12-26-46_QuantError.txt)
[log_2023-02-21_11-35-22_partial.txt](https://github.com/Nesvilab/FragPipe/files/10806787/log_2023-02-21_11-35-22_partial.txt)

**Comment by dpolasky** [comment]
We have made fixes for both of these issues and they'll be available in the next release. If you would like a pre-release version with the fixes now, send me an email at dpolasky [at] umich.edu. 

The second issue about the glycan database is due to an unrecognized glycan in the pGlyco database, but I think they should all be recognized. Can you upload the glycan database file so I can take a look? The fixed version will not crash on an unexpected glycan, but it will ignore it if it cannot parse. 

Best,
Dan

**Comment by dpolasky** [comment]
Thanks! I see the issue - it looks like I never implemented support for the pGlyco format in the PTM-Shepherd module even though FragPipe can read it. Will add that to the fixed version

**Comment by dpolasky** [comment]
fixed in 19.2-build17
