### ISSUE TITLE
DIA data types

### ISSUE THREAD

**Issue by cutleraging** [Nesvilab/FragPipe#1020]
Hello,

Thanks for all your great work on the amazing FragPipe. I am trying to process some samples run with DIA from a thermo instrument using the default DIA_SpecLib_Quant workflow. I am wondering what the options for different DIA data types mean, i.e. DIA vs. DIA-Quant vs. DIA-Lib? When would you want to use these?

Also, when using DIA-NN for quant, are the default settings used here? Is normalization (global or RT-dependent) and MBR enabled?

Thanks,
Ronnie

**Comment by fcyu** [comment]
Hi Ronnie,

Thanks for the kind words.

When hover the mouse over the data types, there will some some tooltips:
![image](https://user-images.githubusercontent.com/6926299/221372035-488a9292-ce81-4c83-ab1f-976fc7a64463.png)

Basically, DIA will be used in spectral library building and quantification. GPF-DIA is for gas-phase fractionated DIA. It will be only used in spectral library building. DIA-Quant will be only used in quantification.  DIA-Lib will be only used in library building.

> Also, when using DIA-NN for quant, are the default settings used here? Is normalization (global or RT-dependent) and MBR enabled?

Most of the settings are by default. There is normalization but no MBR because MBR is for DIA-NN's library-free approach. Since FragPipe has already built a library from your data, there is no need to perform MBR.

Best,

Fengchao

**Comment by cutleraging** [comment]
Thanks a lot!

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
