### ISSUE TITLE
MSBooster calls DIA-NN with TMT mod

### ISSUE THREAD

**Issue by alchemistmatt** [Nesvilab/FragPipe#1031]
When FragPipe runs MSBooster I see in the output messages that it's calling DiaNN.exe using a TMT modification, even though my MSFragger parameter file does not have TMT defined as a static or variable mod, for example:
```
java.exe -Xmx16G -cp "C:\DMS_Programs\MSFragger\fragpipe\tools\msbooster-1.1.11.jar;C:\DMS_Programs\MSFragger\fragpipe\tools\batmass-io-1.28.9.jar" Features.MainClass --paramsList D:\DMS_WorkDir4\msbooster_params.txt

Generating DIA-NN predictions
C:\DMS_Programs\MSFragger\fragpipe\tools\diann\1.8.2_beta_8\win\DiaNN.exe --lib D:\DMS_WorkDir4\GAPDH_LFQ_2_Sample_1_Bane_08Mar22_21-04-05\spectraRT.tsv --predict --threads 4 --strip-unknown-mods --mod TMT,229.1629 --predict-n-frag 100
```

This leads to DIA-NN displaying these messages (also shown in issue #1026)
```
Modification TMT with mass delta 229.163 added to the list of recognised modifications for spectral library-based search
Deep learning predictor will predict 100 fragments
Cannot find a UniMod modification match for TMT: 73.0618 minimal mass discrepancy; using the original modificaiton name
```

Why use `--mod TMT,229.1629` when calling DIA-NN? 

Also, not sure if this matters, but modification mass 229.1629 corresponds to UniMod name [TMT6plex](http://www.unimod.org/modifications_view.php?editid1=737), which is compatible with 6-plex, 10-plex, and 11-plex TMT.  In contrast, [TMT](http://www.unimod.org/modifications_view.php?editid1=739) is TMT 0, with mass 224.152478.

**Comment by alchemistmatt** [comment]
I forgot to add version details, though it's sort of implied from the MSBooster command line:
* FragPipe v19.1
* MSBooster v1.1.11
* DIA-NN 1.8.2 beta 8

**Comment by yangkl96** [comment]
Hello,

We use `--mod TMT,229.1629` because it is how we get DIA-NN to be able to parse TMT peptide strings in the input file. We hardcoded it in our call to DIA-NN, but it doesn't change anything when TMT peptides are not being predicted. We agree it is confusing to get these warnings especially for non-TMT experiments, so we will suppress these warnings in the next FragPipe version. 

Thank you for also pointing out the TMT vs TMT6plex discrepancy. DIA-NN prediction currently only supports TMT 6/10/11, so predicting a peptide with "TMT" in our case is just considering that TMT mass

**Comment by alchemistmatt** [comment]
Thanks for clarifying.  That is what I suspected, but it's nice to have it confirmed.
