### ISSUE TITLE
Addition of decoys and contaminants

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1055]
Greetings,

I am trying to search my proteomics data against a large protein database containing 39,576,194 forwards protein sequences. When I try to append this protein database with FragPipeGUI add decoy feature, I always hit an error. I understand this is a extremally large protein database.

Could you advise me on how to append this custom protein database onto FragPipeGUI?

Regards,
Ben

**Comment by BenSamy2020** [comment]
Greetings,

This is the error message:
![image](https://user-images.githubusercontent.com/69944967/227781309-9f037b0f-78ab-406e-b664-7d520653c152.png)

**Comment by fcyu** [comment]
Hi Ben,

It is because your fasta tile is too big to add the decoys within 10 minutes (FragPipe has a 10 minute timeout for the decoy adding). You can workaround by running the commands in CLI by yourself. The commands can be found in the console of the Run tab.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings,

Thank you! 
Also MSFragger team response to issues are really fast. Thank you for the prompt response!

Regards,
Ben

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Managed to append the database into FragPipeGUI. But I hit the below error:
![image](https://user-images.githubusercontent.com/69944967/227782429-10b7a135-aef7-43bd-b59a-d67b5f98d0bf.png)


I utilised the split database option of 8. I am trying to establish a ISO-Seq-FragPipe Pipeline. I am generating custom protein database from ISO-Seq. I am searching paired immunopeptidomics data against this custom database. By any chance could you advise me on how to make this search happen?

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben,

Your database is very large. I am not sure about your computer's memory, but I guess 8 splits are not enough. Could you increase it to, say, 16, 32,..., until MSFragger can run?

Also, since your database is not like the normal proteomics database, you probably will see other errors from Philosopher later if there is not enough memory. We are working on optimizing the speed and memory usage, and already have a pre-released version that may solve the issue. If you are interested in it, please send an email to yufe AT umich.edu

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings @fcyu,

Just sent the email.

Regards,
Ben
