### ISSUE TITLE
DIA-NN: "Replace library spectra with predicted"

### ISSUE THREAD

**Issue by chscho** [Nesvilab/FragPipe#1060]
Dear FragPipe Team

I've realized, that the "DIA_SpecLib_Quant" workflow has the tickbox "Replace library spectra with predicted" in DIA-NN activated by default. I've seen, that this leads to the activation of DIA-NN options: «--predictor --dl-no-rt --dl-no-im --strip-unknown-mods». Why is this option turned on by default? Wasn't the library supposed to be generated by EasyPQP based on the MSfragger output? What is the "--predictor" option used for here?

I did a quick comparison of the most intense Fragment.Quant.Intensities of all Features and found a certain correlation. - But also quite some differences:

![image001](https://user-images.githubusercontent.com/62370919/228584863-f53599e4-1f4b-4470-9be8-6178067f615b.png)

I further noticed that the content in Fragment.info (--report-lib-info) differed from activated «b3^1/256.1291809» to «b4-unknown^1/327.1662903» if the predictor was deactivated.

I assume, there are good reasons to keep the "Replace library spectra with predicted" option activated by default. But can you give an example, under which condition this option should be turned off? Will the predictor replace all spectra in the easyPQP library?

Thank you for your explanation!

Best,
Christian

**Comment by fcyu** [comment]
Hi Christian,

It is due to the nature of DIA-NN's FDR estimation. We found that after replacing the experiment peaks with the predicted ones, the result is more conservative (lower actual FDR). Since we care about the quality and confidence level more than the number of IDs, we enabled this option by default.

> I further noticed that the content in Fragment.info (--report-lib-info) differed from activated «b3^1/256.1291809» to «b4-unknown^1/327.1662903» if the predictor was deactivated.

Could you elaborate it more? 256.1291809 and 327.1662903 are two different fragments.

Best,

Fengchao

**Comment by anesvi** [comment]
Some comments from me - First, that option only replaces Fragment intensities. Which is not that critical (the empirical retention times are still used). The main reason we use it is that DIA-NN does a better job with FDR modeling when the library contains more fragments (since the empirical spectrum may only have just 5-6 fragments). However, you would not want to do this replacement when doing PTM searches or nonspecific peptidome analysis. We may also switch back to unchecking that option by default in the next release. As I said, at the end, the results are not affected that much.

**Comment by chscho** [comment]
Thank you for your quick reply. That answered my questions. I'll keep that option in mind for upcoming PTM searches.

@fcyu : sorry for the confusion with the two different fragments. I actually just wanted to highlight the "-unknown" portion in the Fragment.info of the DIANN-report, if DIANN was run without the "Replace library spectra with predicted" option. 
So to clarify: all reported fragments had following structure: «b4**-unknown**^1/327.1662903», where as the "-unknown" portion was not there in Fragment.info, if the "Replace library spectra with predicted" was activated...

**Comment by fcyu** [comment]
If I understand it correctly. That `unknown` means the neutral loss type is unknown. DIA-NN treats those fragments as no neutral losses. With `replace library spectra with predicted`, DIA-NN knows the neutral loss type since it predicts it. That is why the `unknown` is gone.

Best,

Fengchao
