### ISSUE TITLE
Database dowload issue

### ISSUE THREAD

**Issue by camerondobrotka** [Nesvilab/FragPipe#1061]
- Describe the issue or question:

I recieve an error when attempting to download a database within the Philosopher tab in the GUI. I have attempted to change the path for different options, but there is no output no matter where I change the path to.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2023-03-29_15-37-50.txt](https://github.com/Nesvilab/FragPipe/files/11104899/log_2023-03-29_15-37-50.txt)

**Comment by fcyu** [comment]
Thanks for reporting this issue. I have reproduced it:

![image](https://user-images.githubusercontent.com/6926299/228650207-ddf85663-f31f-4d08-baa5-29a36a9d4c10.png)


Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by prvst** [comment]
the API is offline, I'm getting the same issue here

**Comment by camerondobrotka** [comment]
My apologies for what may be a naïve question, but when will the API be back online?

**Comment by prvst** [comment]
We pull the data from UniProt, we do not have access or control to do what they do. Have to wait. This seems to be some internal issue. Give it a couple of hours and try again.

**Comment by camerondobrotka** [comment]
Thank you!

**Comment by tobiasko** [comment]
Hi @prvst the Uniprot API seems to be a constant trouble maker. I am considering to contact Uniprot directly to discuss this issue... What is your opinion? Do you get all the support you need to drive your development? Is the API robust/stable? We see many many jobs on our cluster that fail during the DB download. And honestly: It drives me crazy, because it has been like this for months already.

**Comment by danielgeiszler** [comment]
To offer an alternative that isn’t sensitive to Uniprot: you can use some stable databases and point to them rather than redownloading them for every analysis.On Mar 30, 2023, at 12:25, Tobias Kockmann ***@***.***> wrote:﻿
Hi @prvst the Uniprot API seems to be a constant trouble maker. I am considering to contact Uniprot directly to discuss this issue... What is your opinion? Do you get all the support you need to drive your development? Is the API robust/stable? We see many many jobs on our cluster that fail during the DB download. And honestly: It drives me crazy, because it has been like this for months already.

**Comment by prvst** [comment]
@tobiasko I have been working with UniProt for about 15 years, and the recent issues are a new experience for me as well. I believe this is an effect from their updates, which included the frontend revamp. If you want to contact them, please do, but don't expect much. UniProt serves a much bigger purpose than providing programmatic access to FASTA to us, we are just a fraction of the whole community that uses it services, so the chances for them to accommodate your requests might be small. My suggestion is to hold tight for a little longer.
