### ISSUE TITLE
"ImportError: Can't determine version for bottleneck" and "Broken.process.pool" at end of analysis

### ISSUE THREAD

**Issue by mart5176** [Nesvilab/FragPipe#1091]
Hello,

Ran into the errors "ImportError: Can't determine version for bottleneck" and "Broken.process.pool" after a long analysis (Reg-MS, DDA). I don't have the background to figure out where they're coming from and with a ~60 hr analysis, I'm hesitant to use trial and error. It may be a memory error though I would have expected a memory error long before this with 60 Gb allocated. Please find the log attached. 

Thank you for maintaining this software and all your help, past and present.
[log_2023-04-27_16-23-49.txt](https://github.com/Nesvilab/FragPipe/files/11355219/log_2023-04-27_16-23-49.txt)

**Comment by fcyu** [comment]
It appears that MSFragger crashed during the process of collecting results after completing all searches (`DONE: DB split 100 of 100`). The crash is likely due to insufficient memory. 

Additionally, if you convert your raw files to mzML format before running MSFragger, you can potentially reduce the runtime by almost 50%. Reading raw files is a slow process and can take nearly as long as the actual search.

Best,

Fengchao

**Comment by mart5176** [comment]
Ok, I'll see what I can do about the memory and try again. 

That's great to know about converting to mzML beforehand for shorter runtimes. Thank you.
