### ISSUE TITLE
My open search results aren't making it into the combined reports

### ISSUE THREAD

**Issue by orsburn** [Nesvilab/FragPipe#1109]
- Describe the issue or question:
Hi FragPipe team! 
Is there a way to get my open search results into my final quantitative reports? I'm trying to do a limited open search (oxidation products...relatively low delta mass, but unpredictable) on TIMSTOF Flex data across a bunch of files. Everything seems to complete and I do see some of my cool mods in the individual file reports but they don't make it into the combined text files. 
Thanks!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
The `combined_ion/peptide/protein.tsv` won't have the open search modifications (in the delta mass format) because the PSMs have been collapsed to the peptide/protein level. Also, currently, the label-free quantification (IonQuant) does not support open search. 

If the number of  your favorite modifications is less than, say 10, you can perform a closed search by putting your modifications to the variable mod settings. You can get the "theoretical masses" from the `global.profile.tsv` or `global.modsummary.tsv` files (BTW, those two files are super useful to the modification discovery).

Hope it helps.

Best,

Fengchao

**Comment by orsburn** [comment]
Thanks Fengchao! 
I thought maybe that was the case, but I wanted to make sure I wasn't missing an option somewhere.

**Comment by fcyu** [comment]
No problem! Feel free to contact us again if you have any other questions.

Best,

Fengchao
