### ISSUE TITLE
FragPipe Glyco analysis freezes when using external glycan databases since last update. 

### ISSUE THREAD

**Issue by MarcD83** [Nesvilab/FragPipe#1151]
First I have to say that I am using FragPuipe Glyco quite heavily - Thanks for putting this out here!! 

Since updating to v20  I have had the following issue:

**Issue:**
Whenever I use Glycan databases NOT in the internal selection the workflow will freeze after PTMShepherd's "Diagnostic ion extraction".
I have used 4 differnt (N)Glycan databases (different formats) - all of which yielded good results in V19.1
Using the internal databases yields results for the current workflow 
Using the "same" 309 Byonic database yield results for internal and freezes at the same position if custom loaded.  (keeping all other setting identical)
This is the same on two different Computers. 

**Questions:**
Is there a changed format requirement? (i.e. no mod.masses in file or similar)
Or can we add Glycan databases to the internal list?  
How are Offsets determined from the internal lists? (they seem to be only Glycan compostion) 

**Logs:**
Here is one example log of the issue:   (309 external)
[log_2023-06-20_09-21-46.txt](https://github.com/Nesvilab/FragPipe/files/11797313/log_2023-06-20_09-21-46.txt)

Here is a Log that went through :  (309 internal)
[log_2023-06-19_22-15-28.txt](https://github.com/Nesvilab/FragPipe/files/11797367/log_2023-06-19_22-15-28.txt)

Otherwise v20 is Awesome!

Thanks,
Marc

**Comment by danielgeiszler** [comment]
Last release we fixed a bug where it was crashing on some glycan databases, and now it looks like that made it crash on yours. Can you please post the database you're using so we can see what's causing it?

**Comment by MarcD83** [comment]
thanks (again) for the super quick reply!
These are two differnt Composition formats formats 
Here they are: 
[N-glycan 309_Byos.txt](https://github.com/Nesvilab/FragPipe/files/11797664/N-glycan.309_Byos.txt)
[N-riley_fragPipe_incl_P_S_.txt](https://github.com/Nesvilab/FragPipe/files/11797691/N-riley_fragPipe_incl_P_S_.txt)

The others are equivalent (eg N-182 Byos)

These are two differnt Composition formats formats

**Comment by dpolasky** [comment]
Hi Marc,
Thanks for the report - there were some changes to the database format, but I think the issue here is that the parser is getting confused about which format you're using. We're not using the HexNAc-1_Hex-1 format internally any more (though it's still supported for compatibility), but the presence of the `% [mass]` term makes the parser think it's the new format [which lists compositions as `HexNAc(1)Hex(1)`]. I will update the parser to be more robust, but in the meantime, you should be able to get it working by changing all `_` and `-` to `(` and `)`, and removing the header line in the external database file. If you still have issues with those changes, let me know! 

Best,
Dan

**Comment by MarcD83** [comment]
Hi Dan,

Thanks for the help - now it ran through! (tested the 309 first) 

Can you share the (best) possible formats? 
i.e. Hex(x)  +% [mass] 
or 
Hex_x ....    # I guess this kind of answered, but which sepperator for [mass] would be recognized? 

Last question:
With the changes, which types of components will be recognized: 
i.e: HexNAc / Hex etc is clear /  
but what about HexNAz / Sulpho or S / Phospho  or P / etc.

Is there a List you are able to share (or a tutorial etc. I might have missed) ? 
Or something like an updated cheat sheet for glycan lists that FragPipe likes ... 

Thanks and Best,
Marc

**Comment by dpolasky** [comment]
Hi Marc,
Great, glad to hear it. The Hex(x) % [mass] is the best format to use (that's what we use internally now). I think the other format should work if you remove the mass and just say Hex_1 with no `%` (the `%` sign is what triggers it to think it's the new format right now). But I will make the parser more robust in the next update so this isn't an issue. 

There is an internal list of the allowed monosaccharides in PTM-Shepherd (you can find it at https://github.com/Nesvilab/PTM-Shepherd/blob/main/src/edu/umich/andykong/ptmshepherd/glyco/GlycanResidue.java). Currently, it is not possible to modify the list, but I am planning to change that in the next version so that you can specify whatever monosaccharides/adducts/modifications you want. 

Best,
Dan

**Comment by MarcD83** [comment]
Ok, regarding the Log-files, nevermind, I found the error - it wont accept tap-sepperation in my case. 
There was one in there that I missed - after changing everything to "space" sepperated  it worked!

**Comment by dpolasky** [comment]
Hi Marc,
Yes the issue is the tab separator in one of the lines - glad it's working now. The improved parsing code also handled it fine with the tab separator, so if you come across further issues let me know and I can send you the updated pre-release version. 

And yes, the glycan masses are always recalculated in PTM-Shepherd from the internal database and the mass provided in the database file is not used. You in fact do not need to provide the mass at all (e.g., HexNAc(1)Hex(1) works just fine as a composition instead of HexNAc(1)Hex(1) % 365.1322). If glycans without supported masses are provided, they are not included in the analysis currently (and a warning is printed), but in the future we will make it so that the internal list of glycans can be edited to support whatever monosaccharides/modifications/adducts/etc are needed. 

Best,
Dan

**Comment by MarcD83** [comment]
Thanks for the clarification - I found the explanation in the guide, but thought Id ask to be sure ;-) 

Last clarification: 

what you said means, that any glycan, as complex and crazy as I want (e.g. HexNac(37)Hex(52)Fuc(14)Phospho(12)Sulpho(10)) will be accepted, but if I use a monomer outside the list linked above, it will be rejected (e.g. SiaNAz(1)), both due to the mass-recalculation step? 

thanks a lot!
Marc
