### ISSUE TITLE
Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by Allen188** [Nesvilab/FragPipe#118]
![20190613170549](https://user-images.githubusercontent.com/50605360/59419575-c00f9600-8dfd-11e9-89d6-694266de26dc.png)
I only run Umpirese, have an error: 'Process returned non-zero exit code, stopping' . Can you help me solve it ? 

Process 'UmpireSe' finished, exit code: 1

Process returned non-zero exit code, stopping
UmpireSe
java -cp C:\Users\Administrator\Desktop\FragPipe.exe umich.msfragger.util.FileMove E:\GE\pulse dia\Fragpipe\mzXML\diaumpire_se.log E:\GE\pulse dia\Fragpipe\diaumpire_se.log

~~~~~~~~~~~~~~~~~~~~
Stopping 285/286 processes (1 already finished)
Processing interrupted, stopping UmpireSe

~~~~~~~~~~~~~~~~~~~~
Stopping 0/0 processes (0 already finished)

**Comment by chhh** [comment]
Can you please try to use a path without spaces in it?

**Comment by raphaelhtdi** [comment]
Hi, I have the same issue running fragpipe and philosopher
Don't think the spaces in the path are the issue as I do not have any
Can you help with this, please?
Thanks

System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190628
Philosopher version 20190418 (build 201904182204)


LCMS files:
  Experiment/Group: 
  - D:\mgf\TTP0041_20190506_raphael_PNGase_peptide_S1-H1_1_1694_5.2.211.mgf
  - D:\mgf\TTP0041_20190506_raphael_PNGase_peptide_S1-H2_1_1689_5.2.211.mgf

10 commands to execute:
Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe workspace --clean
Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe workspace --init
MsFragger [Work dir: D:\mgf]
java -jar -Dfile.encoding=UTF-8 C:\MSFragger-GUI-master\MSFragger-20190628.jar D:\mgf\fragger.params D:\mgf\TTP0041_20190506_raphael_PNGase_peptide_S1-H1_1_1694_5.2.211.mgf D:\mgf\TTP0041_20190506_raphael_PNGase_peptide_S1-H2_1_1689_5.2.211.mgf
ReportDbAnnotate [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe database --annotate D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta --prefix rev
PeptideProphet [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev --database D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta TTP0041_20190506_raphael_PNGase_peptide_S1-H2_1_1689_5.2.211.pepXML
PeptideProphet [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev --database D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta TTP0041_20190506_raphael_PNGase_peptide_S1-H1_1_1694_5.2.211.pepXML
ProteinProphet [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe proteinprophet --maxppmdiff 2000000 D:\mgf\interact-TTP0041_20190506_raphael_PNGase_peptide_S1-H2_1_1689_5.2.211.pep.xml D:\mgf\interact-TTP0041_20190506_raphael_PNGase_peptide_S1-H1_1_1694_5.2.211.pep.xml
ReportFilter [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev --pepxml D:\mgf --protxml D:\mgf\interact.prot.xml
ReportReport [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe report
Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe workspace --clean
INFO[15:18:31] Executing Workspace 20190418                 
WARN[15:18:32] There is a new version of Philosopher available for download: https://github.com/prvst/philosopher/releases 
INFO[15:18:32] Removing workspace                           
INFO[15:18:32] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe workspace --init
INFO[15:18:33] Executing Workspace 20190418                 
WARN[15:18:33] There is a new version of Philosopher available for download: https://github.com/prvst/philosopher/releases 
INFO[15:18:33] Creating workspace                           
INFO[15:18:33] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: D:\mgf]
java -jar -Dfile.encoding=UTF-8 C:\MSFragger-GUI-master\MSFragger-20190628.jar D:\mgf\fragger.params D:\mgf\TTP0041_20190506_raphael_PNGase_peptide_S1-H1_1_1694_5.2.211.mgf D:\mgf\TTP0041_20190506_raphael_PNGase_peptide_S1-H2_1_1689_5.2.211.mgf
MSFragger version MSFragger-20190628
MSFTBX version 1.9.10
(c) University of Michigan
RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved.

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 14535 MB memory


************************************MAIN SEARCH************************************
Parameters:
num_threads = 8
database_name = D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta
decoy_prefix = rev
precursor_mass_lower = -10.0
precursor_mass_upper = 10.0
precursor_mass_units = 1
precursor_true_tolerance = 10.0
precursor_true_units = 1
fragment_mass_tolerance = 10.0
fragment_mass_units = 1
calibrate_mass = 0
evaluate_mass_calibration = false
isotope_error = -1/0/1/2
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = false
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 200.0
digest_mass_range_high = 5000.0
max_fragment_charge = 4
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 3
min_matched_fragments = 4
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.9949 M
variable_mod_02 = 42.0106 [^
Number of unique peptides
	of length 7: 248423
	of length 8: 231332
	of length 9: 221326
	of length 10: 203777
	of length 11: 187589
	of length 12: 174265
	of length 13: 165004
	of length 14: 149301
	of length 15: 139418
	of length 16: 127424
	of length 17: 117132
	of length 18: 109156
	of length 19: 102467
	of length 20: 93448
	of length 21: 87360
	of length 22: 80159
	of length 23: 74664
	of length 24: 69831
	of length 25: 64831
	of length 26: 59624
	of length 27: 56619
	of length 28: 52784
	of length 29: 48497
	of length 30: 45091
	of length 31: 41659
	of length 32: 38955
	of length 33: 35941
	of length 34: 33358
	of length 35: 30545
	of length 36: 29052
	of length 37: 25784
	of length 38: 24115
	of length 39: 21684
	of length 40: 20700
	of length 41: 19272
	of length 42: 17194
	of length 43: 15120
	of length 44: 12267
	of length 45: 9722
	of length 46: 6680
	of length 47: 4312
	of length 48: 2619
	of length 49: 1429
	of length 50: 842
In total 3300772 peptides.
Generated 5135770 modified peptides.
Selected fragment tolerance 0.05 Da and maximum fragment slice size of 10.51 GB.
192424176 fragments to be searched in 1 slices (2.87 GB total)
Operating on slice 1 of 1: 
	001. TTP0041_20190506_raphael_PNGase_peptide_S1-H1_1_1694_5.2.211.mgf Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "564.07698	1600"
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at edu.umich.andykong.msfragger.l.a(Unknown Source)
	at edu.umich.andykong.msfragger.r.a(Unknown Source)
	at edu.umich.andykong.msfragger.p.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.NumberFormatException: For input string: "564.07698	1600"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at edu.umich.andykong.msfragger.m.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
ReportDbAnnotate [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher_windows_amd64.exe database --annotate D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta --prefix rev

~~~~~~~~~~~~~~~~~~~~
Stopping 8/11 processes (3 already finished)
Processing interrupted, stopping ReportDbAnnotate

**Comment by fcyu** [comment]
Hi,

Thanks for your interest in MSFragger. Since MGF format has many flavors in its TITLE, MSFragger only support few of them. We suggest you using mzML or mzXML format.

Thanks,

Fengchao

**Comment by raphaelhtdi** [comment]
thanks for your quick respnse. 
I have tried all formats from both thermo raw files as well as timsTOF data.
IT always comes up with exactly the same error as posted above

**Comment by fcyu** [comment]
Was msconvert the tool you were using to convert the raw format?

**Comment by anesvi** [comment]
See tutorials on how to convert the files on
https://msfragger.nesvilab.org/

you can also convert from mgf to mzML, also using proteowizard

**Comment by fcyu** [comment]
@raphaelhtdi BTW, the latest MSFragger supports Thermo raw file. You may direct use your files end with `.raw` if you want. For timsTOF files, you may converted them according to the tutorial that Alexey mentioned.

Best,

Fengchao

**Comment by raphaelhtdi** [comment]
thanks for your help.
Unfortunately, I do have the same issue with all file formats, including raw files (see below).




System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 9.4
MSFragger version 20190628
Philosopher version v1.4.4 (build 1562876687)


LCMS files:
  Experiment/Group: 
  - D:\HF481_MSQ_20190418_HeLa_digest_non.raw

10 commands to execute:
Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe workspace --clean
Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe workspace --init
MsFragger [Work dir: D:\mgf]
java -jar -Dfile.encoding=UTF-8 C:\MSFragger-GUI-master\MSFragger-20190628.jar D:\mgf\fragger.params D:\HF481_MSQ_20190418_HeLa_digest_non.raw
MsFragger
java -cp C:\MSFragger-GUI-master\FragPipe-9.4.jar umich.msfragger.util.FileMove D:\HF481_MSQ_20190418_HeLa_digest_non.pepXML D:\mgf\HF481_MSQ_20190418_HeLa_digest_non.pepXML
ReportDbAnnotate [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe database --annotate D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta --prefix rev
PeptideProphet [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev --database D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta HF481_MSQ_20190418_HeLa_digest_non.pepXML
ProteinProphet [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe proteinprophet --maxppmdiff 2000000 D:\mgf\interact-HF481_MSQ_20190418_HeLa_digest_non.pep.xml
ReportFilter [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev --pepxml D:\mgf --protxml D:\mgf\interact.prot.xml
ReportReport [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe report
Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe workspace --clean
INFO[17:31:29] Executing Workspace v1.4.4                   
INFO[17:31:29] Removing workspace                           
INFO[17:31:29] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: D:\mgf]
C:\MSFragger-GUI-master\philosopher.exe workspace --init
INFO[17:31:30] Executing Workspace v1.4.4                   
INFO[17:31:31] Creating workspace                           
INFO[17:31:31] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: D:\mgf]
java -jar -Dfile.encoding=UTF-8 C:\MSFragger-GUI-master\MSFragger-20190628.jar D:\mgf\fragger.params D:\HF481_MSQ_20190418_HeLa_digest_non.raw
MSFragger version MSFragger-20190628
MSFTBX version 1.9.10
(c) University of Michigan
RawFileReader reading tool. Copyright © 2016 by Thermo Fisher Scientific, Inc. All rights reserved.

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 14535 MB memory


************************************MAIN SEARCH************************************
Parameters:
num_threads = 8
database_name = D:\FASTA\UPR_HomoSapiens_20170118_decoyConcat.fasta
decoy_prefix = rev
precursor_mass_lower = -10.0
precursor_mass_upper = 10.0
precursor_mass_units = 1
precursor_true_tolerance = 10.0
precursor_true_units = 1
fragment_mass_tolerance = 10.0
fragment_mass_units = 1
calibrate_mass = 0
evaluate_mass_calibration = false
isotope_error = -1/0/1/2
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = false
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 200.0
digest_mass_range_high = 5000.0
max_fragment_charge = 4
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 3
min_matched_fragments = 4
minimum_ratio = 0.01
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
Selected fragment tolerance 0.05 Da and maximum fragment slice size of 10.51 GB.
192424176 fragments to be searched in 1 slices (2.87 GB total)
Operating on slice 1 of 1: 
	001. HF481_MSQ_20190418_HeLa_digest_non.raw Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.RuntimeException: Massoid Thermo gRPC server did not start
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.init(ThermoRawFile.java:172)
	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.<init>(ThermoRawFile.java:146)
	at edu.umich.andykong.msfragger.t.a(Unknown Source)
	at edu.umich.andykong.msfragger.r.a(Unknown Source)
	at edu.umich.andykong.msfragger.p.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp C:\MSFragger-GUI-master\FragPipe-9.4.jar umich.msfragger.util.FileMove D:\HF481_MSQ_20190418_HeLa_digest_non.pepXML D:\mgf\HF481_MSQ_20190418_HeLa_digest_non.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 8/11 processes (3 already finished)
Processing interrupted, stopping MsFragger

**Comment by anesvi** [comment]
Can you convert from raw to mzML to see if the same file is running when in mzML format?
The support was RAW has not been tested as well yet

If still get an error, please send us your RAW file
Thanks
Alexey

**Comment by fcyu** [comment]
@raphaelhtdi This is a different error. In order to make raw file parsing work, you need to download the zip file; put the MSFragger-20190628.jar and ext folder in the same folder.

Best,

Fengchao
