### ISSUE TITLE
Questions for modifications in the "psm.tsv" file

### ISSUE THREAD

**Issue by Kadewhilingtz** [Nesvilab/FragPipe#1183]
Hello!
We are doing open search for the TMT data. When checking the "psm.tsv" file, we have some quesetions:

1. We understand "PeakApex" as the mass shift detected for that psm, and "Theoretical" as the theoretical mass of the modification for which that mass shift was matched in the UNIMOD database. Why do some modifications have both "PeakApex" and "Theoretical" and some have only one?
![图片](https://github.com/Nesvilab/FragPipe/assets/75680807/c0488c22-3d57-4389-9897-1f7897a2b39f)
![图片](https://github.com/Nesvilab/FragPipe/assets/75680807/b39cc9d1-369d-4da8-9b55-fed80ecfd387)

 2. Modifications are the same, but the PeakApex is different.
For example, the delta mass of a PSM is 13.004 and the Observed Modifications are: Mod1: Loss of O2; nitro photochemical decomposition (PeakApex: 12.9954, Theoretical: 12.9952) ; Mod1: Loss of O2; nitro photochemical decomposition (PeakApex: 13.0032). Here for two identical modification combinations possible, why is PeakApex different.

3. Many PSMs have a large delta mass, but do not show the modification.
In the figure below, the red box shows a large delta mass, but no modification is matched. Why is it that such a large delta mass exists and no modification is identified, but it is counted as a match.
 
![图片](https://github.com/Nesvilab/FragPipe/assets/75680807/ac9529c6-1907-48ff-a4c6-13170d0571d7)

Best,
Ling.

**Comment by danielgeiszler** [comment]
Hi Ling,

For 1.: can you please share your psm.tsv? If you can't upload here, can you email it to me at geiszler@umich.edu?

For 2.: PeakApex is determined from your data. Sometimes a mass shift will be split into two separate peaks because the instrument can lose its calibration during a run. This is normal.

For 3: Sometimes mass shifts aren't annotated because they're combinations of modifications or artifacts from the open search process. For information about how this works, please read the original MSFragger paper (Kong 2017) or the Crystal-C paper.

**Comment by Kadewhilingtz** [comment]
Hi Geiszler,
Thank you very much!
For 1, I just send you psm.tsv by email.
For 3, I still have some questions: why modifications can't  be annotated when they are combinations even when those modifications match the mass shift?

Best,
Ling
