### ISSUE TITLE
Bimodal distribution of TMT intensities using TMT integrator

### ISSUE THREAD

**Issue by MP-MS-Spec** [Nesvilab/FragPipe#1185]
Dear FragPipe team,

we are observing a bimodal distribution, similar to an imputation distribution (see picture below) in the Log2 Protein intensity when using the TMT integrator quant columns from "abundance_protein_MD" table. 
This bimodal distribution disappear when using the raw intensities from the Protein.tsv table (see below).
Also, it is not there when using the same dataset in other TMT analysis software...
![Original TMT intensity](https://github.com/Nesvilab/FragPipe/assets/132456808/386714a1-346d-4f22-ac6e-da274156b7c1)
![TMTintegrator Intensity](https://github.com/Nesvilab/FragPipe/assets/132456808/dd8b27fd-a59d-43a4-9914-f835b9afc281)

We are using the TMT integrator default settings when loading the TMT16-MS3 workflow: 
                                                    Reference= Virtual
                                                    Normalization = MD
                                                    Group by = All (this is custom :) )

Can you please let us understand where this lower Protein intensity distribution might come from?
Thank you

Michele

**Comment by anesvi** [comment]
This is because of using precursor ms1 intensities for  estimating the absolute protein intensity for ratio to abundance table conversion. When there is no ms1 intensity due to software not being able to detect it in ms1 data, tmt-integrator imputes a small value. You can change it to using just MS2 data by unchecking 'use ms1 intensity' and 'usetop 3 peptide' options in TMT-integrator tab. I am traveling now, but I think it is explained somewhere, or I will do it better when I have time.
