### ISSUE TITLE
Different modification masses used as modification identifier in different columns of output

### ISSUE THREAD

**Issue by hollenstein** [Nesvilab/FragPipe#1191]
Dear developers,

**Describe the issue or question:**
I've run a standard LFQ-MBR workflow with PTM analysis and specified a variable modification on K with a mass mass delta of 114.04293. I've noticed that two different masses for representing the modification are used in different places, 114.0429 and 114.04293.
- Modification filename: K_**114.04293**.tsv
- "Assigned Modifications" column in combined_ion.tsv: "3K(**114.0429**)"
- "Modified Sequence" column in combined_ion.tsv: "EIK[**114.0429**]IEISELNR"
- "Localization" column in combined_ion.tsv: "K:**114.04293**@EIK(1.0000)IEISELNR;"

**Version info:**
FragPipe version 20.0
MSFragger version 3.8
IonQuant version 1.9.8
Philosopher version 5.0.0

Would it be possible to unify the modification identifier that is used in different places? It is quite inconvenient for processing the results as one might need to specify two different identifiers for a modification to be used in different places.

Thanks for the consideration and best wishes,
David

**Comment by fcyu** [comment]
Hi David,

Thank you very much to your feedback. 

Yes, the mass values in the site report (`K_114.04293.tsv`) and `Localization` column are not unified with the mass values in the `assigned modifications` and `modified sequence`. I will fix this in the next IonQuant version.

Best,

Fengchao

**Comment by hollenstein** [comment]
Hi Fengchao,

that's great. I believe to remember that there was a similar situation for phospho (79.9663 and 79.96633) but it was fixed in one of the recent releases. So I was wondering if it would make sense to have a general rule to use the modification mass as a modification tag with always exactly 4 decimal places in all columns of the tables and the filenames, (and add trailing zeros if less decimal places were specified in FragPipe). Then you could add this behavior to the documentation for clarity (Description about Assigned Modifications, Best Localization, ...). And maybe even to the FragPipe tool tips, somewhere in the region shown in the image.

![image](https://github.com/Nesvilab/FragPipe/assets/11833102/7499d786-08a1-45e6-bf13-71d8f2b58553)

I just realized that the situation is similar for the PSM table. With one of the columns being "K:114.04293 Best Localization", in the "Assigned Modifications" column the entry is "1K(114.0429)" and the "Modified Peptide" entry is "K[242]YEDEINKR" (which I assume is the modified amino acid mass as an integer).

Best,
David

**Comment by jossmi** [comment]
Hi, I came across this thread and second all the points David made, but also would like to get clarification and some help on the last point, the bracketed "Modified Peptide" modification ID in the psm.tsv output file. However, in addition to my curiosity of what that ID means, I think that this may also be causing some hiccups with other parts of FragPipe, notably EasyPQP and DIA-NN. Apologies for the length of the post. 

First, I have long wondered what these bracketed values are - they are clearly unique, but they don't seem to correspond to the modification mass or Unimod ID. David suggests that this is the mass of the modified, free amino acid. However, while this works for the modification he mentioned (128.09496 + 114.04293 = 242.13789), it doesn't work for others:

Cys carbamidomethylation (Unimod ID 4): modification ID is "[160]" in "Modified Peptide", but 121.0197 monoisotopic mass for Cys + 57.0214 = 178.0411
Cys trioxidation (Unimod ID 345): modification ID is "[151]", but 121.0197 + 47.9847 = 169.0044
Cys modification with C7H6O (Unimod ID 1254): modification ID is "[209]", but 121.0197 + 106.0419 = 227.0615

My examples with Cys residues all seem to be off by ~18 Da, but this is not always the case, and I am not sure how a gain/loss of water makes sense either. Why Cys and not Lys? Any clarification would be helpful, in case I am missing something with the significance of that ID. 


Secondly, the concern that this ID value may be causing errors with EasyPQP and DIA-NN. I have included several variable modifications in my MSFragger search (all of which are in Unimod, including the three Cys modifications mentioned above), and the search runs fine. Of course, the psm.tsv file contains the columns "Modified Peptide" and "Assigned Modifications", both of which display the position of the variable mods I specified (albeit, I can't decode the derivation of the [ID] values in "Modified Peptide", but they do appear to be on the correct residues and the values are unique to entries in the "Assigned Modifications" column). Fine so far.

I wanted to have DIANN quantify the precursor-level abundances of these variable modifications that were detected by MSFragger, which DIANN does as long as the modification was specified as variable. So I had EasyPQP generate a spectral library and I included the appropriate command-line options in DIANN for it to recognize all the desired variable modifications. The library is generated by EasyPQP without errors in the log and DIANN starts. However, DIANN keeps crashing because it says it does not recognize a modification that I did not tell it about (full log is attached):

"ERROR: C:\diann\src\diann.cpp: 2774: unknown modification: 209.05106"

While I did not specify any variable modification of 209.05106 in the search, note that this novel mystery modification is the same integer as the [ID] for C7H6O/Unimod 1254 I mentioned above (eg, "[209]"). In fact, this "[209]" ID is in "Modified Peptide" column of the psm file (eg, "ALVLIAFAQYLQQC[209]PFEDHVK"), corresponding uniquely to the correct mass shift that is listed in the "Assigned Modifications" (eg, "14C(106.0418)").

Moreover, the new mystery modification is inexplicably appearing on Cys residues in the spectral library produced by EasyPQP: "ALVLIAFAQYLQQC[209.05106]PFEDHVK", in the column "ModifiedPeptideSequence". The rest of the variable modifications are in the library, as expected. 

This particular error does not occur when I take out the C7H6O/Unimod 1254 variable modification from the search. I get similar errors about new "mystery" modifications that I did not specify when I try to include other various variable modifications (eg, a +712.3934 Da variable Cys modification (not listed in Unimod) produces psms with a Cys+712.3934 Da "Assigned Modification", a "[815]" modification ID in the "Modified Peptide" column, modified peptides in the EasyPQP library with modification masses of "[815.4026]" on Cys residues, and a DIANN error of "ERROR: C:\diann\src\diann.cpp: 2774: unknown modification: 815.4026").

Thus, I am thinking that this [ID] in the "Modified Peptide" column (which appears unrelated to the modification mass specified) seems to be being pulled into the spectral library built by EasyPQP (with extra decimals added?), and then this mystery modification is not recognized by DIA-NN (because I didn't specify it as a variable modification), causing the crash. Why it happens for some but not all variable modifications, I can't figure out. Maybe there is a short list of UniMod modifications recognized by EasyPQP and if it doesn't match to the list of [ID] values that have corresponding modification masses, it pulls the [ID] value directly, assuming it is the modification mass?

My thought would be that the issue might be solved by using the modification's monoisotopic mass (to 4 decimal places, as suggested by David) as the [ID] in the "Modified Peptide" column of the psm file or other MSFragger output. 


Josh


[log_2023-08-02_17-00-53.txt](https://github.com/Nesvilab/FragPipe/files/12254647/log_2023-08-02_17-00-53.txt)

[library.csv](https://github.com/Nesvilab/FragPipe/files/12254719/library.csv)
[psm.csv](https://github.com/Nesvilab/FragPipe/files/12254720/psm.csv)

**Comment by dpolasky** [comment]
Hi Josh,

The residue mass of Cysteine is 103, not 121 (http://www.matrixscience.com/help/aa_help.html) - you have the terminal H2O included in your calculations I think. The modified peptide masses reported are all correct (e.g., 160 is the correct mass for carbamidomethylated cysteine) and are indeed amino acid residue mass + modification mass. For context, the I think modified peptide format is from the pepXML standard, and is needed in that format to maintain compatibility with some older tools. 

I'm not sure what the issue is with easyPQP/DIANN, but it appears that easyPQP is not matching the C+106 modification to Unimod (reporting as delta mass of 209 instead) whereas all the others are matched to Unimod. EasyPQP does have an internal Unimod matching list, and it does contain the UniMod:1254 entry. Maybe try increasing the mass tolerance for Unimod matching in easyPQP. 

Best,
Dan

**Comment by jossmi** [comment]
Thanks for the quick reply, Dan. Residue mass does make sense, especially with the 18 Da difference I was seeing in my calculations for Cys (I used amino acid mass) and Lys (residue mass). 

I'll try the annotation tolerance settings next, thanks. Regarding the EasyPQP Unimod list - is it the full Unimod? Or a subset? How could I know/alter the Unimod list it uses, from within the FragPipe interface? I notice there is no command line option on the EasyPQP tab, as there is for other tools - could that be added in the future to facilitate some of these more bespoke library building commands?

Thanks,
Josh

**Comment by dpolasky** [comment]
I think it's the full Unimod, though I haven't looked at it carefully - this is the file I'm looking at: https://raw.githubusercontent.com/grosenberger/easypqp/master/easypqp/data/unimod.xml. You could actually change it by replacing the file in your installed easyPQP instance (in your local Python) if you wanted to, that would be easier I think than specifying it via FragPipe. I've also had problems before translating unusual mods from easyPQP to DIANN, but I'm not sure it's the necessarily the Unimod database that's at fault or some other issue. 

Best,
Dan

**Comment by fcyu** [comment]
Hi @jossmi ,

Thanks for the long feedback. And also thank Dan for the answers. Please let me clarify the confusions.

1. The "mystery ID" in `[]` is just the rounded **summation** of the amino acid **residue mass** (as Dan also pointed out) and the modification mass. For example, `160 = round(103.00919 + 57.0214)`. This is the format used by TPP, and has been used for decades.
2. It seems that EasyPQP did not match the modification mass to `UniMod:1254` (may be because the old EasyPQP used an old version of unimod). Thus, it put the **summation** of the residue mass and modification mass to the `[]` of `library.tsv`. To let DIA-NN recognize your modifications, could you try `--var-mod UniMod:1254,209.05106,C` rather than `--var-mod UniMod:1254,106.04186,C`?

Best,

Fengchao

**Comment by jossmi** [comment]
Thanks for the input, Fengchao. I'll definitely try the summation approach with the DIANN command.

**Comment by fcyu** [comment]
Hi @hollenstein ,

I have fixed the inconsistent modification masses bug. Please send an email to `yufe@umich.edu` if you want to have a beta version to test.

As to unifying all masses to 4 decimal points, it should have been done in the files generated by IonQuant. But it is hard to unify the masses for all other tools since some of them are out of my control. 

Best,

Fengchao
