### ISSUE TITLE
Question about MS1 quant

### ISSUE THREAD

**Issue by zelanis** [Nesvilab/FragPipe#1194]
Hello,

I am a new user of FragPipe and have a question about MS1Quant 

I have performed a dimethyl labeling experiment and, in order to proceed with some differential expression analysis, I would like to get the Light and heavy intensities individually (instead of H/L ratios). Is there any output file among the ones generated by FragPipe where I could find such a piece of information? (I noticed that the 'combined_ion_label_quant.tsv' file contains individual Light and Heavy peptide intensities, however, I'd like this information at the Protein level).

Many thanks in advance and congratulations on such a great, friendly, and robust software!
Cheers,

André.

**Comment by fcyu** [comment]
There is no intensities in the peptide-level and protein-level `combined label quant` table because the log-ratios are not directly from the ratios of intensities. They are from the median of the ion-level log-ratios. Thus, listing the intensities values are not very informative. 

If you really want some "intensity values", you can figure out the values by using the intensities in the `combined_protein.tsv` and the log-ratios. Solving simple linear equations can give you some "fake intensities" (the intensities you want are not the observed/real one in any way).

Best,

Fengchao

**Comment by zelanis** [comment]
Thanks for the information, Fengchao.
In fact, I was wondering whether I could have these values for each labeling pair (i.e light and heavy, separately, instead of a ratio).

Best,

André.
