### ISSUE TITLE
Percolator: Convert to pepxml

### ISSUE THREAD

**Issue by feng6544** [Nesvilab/FragPipe#1195]
My setting
Where did I set it up incorrectly? Why did I encounter this problem？
I just modified the intensity information of the input mgf file！
![image](https://github.com/Nesvilab/FragPipe/assets/93083550/b540d045-37a8-44c0-8637-70538e6f885a)
[log_2023-07-24_08-43-19.txt](https://github.com/Nesvilab/FragPipe/files/12140453/log_2023-07-24_08-43-19.txt)

**Comment by fcyu** [comment]
First of all, you are using a very old version of FragPipe (version 17.0). Please upgrade FragPipe, MSFragger, IonQuant, and Philosopher to the latest versions.

Second, we don't support MGF well because the format is too flexible. There could be may unknown flavors. Please use mzML format.

Best,

Fengchao
