### ISSUE TITLE
Error running default workflow in headless mode on a linux cluster

### ISSUE THREAD

**Issue by nitz1bug** [Nesvilab/FragPipe#1200]
Hi,

I am trying to get FragPipe running on a Linux cluster but I keep getting stuck with an error.

Below are the versions of all the software I'm using and I have uploaded a file with the error I am getting.
FragPipe: 20.0
Java Info: 17, OpenJDK 64-Bit
Python: 3.8.2
EasyPQP: 0.1.39
Philosopher: 5.0.0
MSFragger: 3.8

I am running FragPipe with your recommended command for Linux in headless mode, having specified paths to output directory and manifest and workflow files (with new database path in the file), as well as paths to configure Philosopher and MSFragger.

Thank you so much for your help!
[error_output.txt](https://github.com/Nesvilab/FragPipe/files/12185901/error_output.txt)

**Comment by fcyu** [comment]
Please check our environment variable configurations and if your JVM is in headless mode. It looks like your JVM config, such as `java.awt.headless` are not correctly configured. Since it is related to the config of your server, I suggest you contact your IT department to troubleshoot locally. 

Best,

Fengchao
