### ISSUE TITLE
Add Files is having numerous problems

### ISSUE THREAD

**Issue by Tlicknack** [Nesvilab/FragPipe#1208]
Hello. I wanted to make the team aware of some weird things that happen when you sort files, add files more than once, and perhaps other conditions I haven't tested. 

In my case, I added 9 files with names Wendy*-DIA.raw (1-3, 11-13, 21-23). Not too shockingly, when I loaded these all at once, Wendy1-DIA.raw is first, followed by 11, 12, 13, **2**, 21,22,23,**3** This is annoying but not the end of the world. If I add my Experiment and then sort of the Experiment (to make labeling the Bioreps easier), then the UI assigns Biorep numbers based on the original order of the files. 
![Fragpipe error part 1](https://github.com/Nesvilab/FragPipe/assets/35544671/c596c627-ad7f-417a-863b-a8f1e1d6f3d1)
![Fragpipe error part 2](https://github.com/Nesvilab/FragPipe/assets/35544671/9e63cca4-883b-4b29-a57d-f30489340fbf)
![Fragpipe error part 3](https://github.com/Nesvilab/FragPipe/assets/35544671/23cca46c-7db0-4b15-98d5-600edf77b735)
![Fragpipe error part 4](https://github.com/Nesvilab/FragPipe/assets/35544671/c1799b5e-14b1-4584-b4d6-169e216344d8)
*I'm not being permitted to attach screenshots, but I think you can reproduce this on your end*

On top of this, if I load the first 3 files (1-3), label their Experiment, then load the second 3 files, label their Experiment; the Experiment label for the second set goes to the first set. I then have to label the second set by highlighting the first set. 

The work around here is to just not sort any files before adding Experiment, Biorep, etc., and to upload all files at once, but I thought this was worth mentioning in case it affects other users.

This is the newest download on a brand new computer, by the way.

Thank you.

**Comment by Tlicknack** [comment]
OH, I guess the "error" message when copying+pasting was not an issue...

**Comment by fcyu** [comment]
First of all, for the current FragPipe version, you should NOT specify any experimental groups if you are analyzing DIA data. Because FragPipe needs to build a single spectral library using all files.

Second, it seems that the fundamental cause of your issue is that you named your files as 1, 2, 3, ..., 11, 12.... When sorting, 11 be ahead of 2 because the sorting is alphabetically. As far as I know, all operating systems sort the files in this way if you sort them by file names. Naming them to 01, 02,...., 11, 12 will make your life much easier.

Best,

Fengchao
