### ISSUE TITLE
ultrafast .params for msfragger

### ISSUE THREAD

**Issue by zachdwight** [Nesvilab/FragPipe#1231]
I'm working directly with the .jar for msfragger, but do you have an example or recommendations for 'ultrafast' in terms of how to set the parameters in the .params ?  Example .params would be appreciated that we can tune.  Thanks ~

**Comment by fcyu** [comment]
What is the "ultrafast" that you were referring? A params file makes MSFragger run untrafast or a params file example?

If you want some examples, here they are: https://github.com/Nesvilab/MSFragger/tree/master/parameter_files

Best,

Fengchao

**Comment by zachdwight** [comment]
Yep - saw those examples.  And y'all literally titled the publication with 'ultrafast' so I'm asking for what you would consider to be the fastest recommended .params settings.

**Comment by fcyu** [comment]
I think, nowadays, a good result is more important than the "fastest speed" since MSFragger is already fast enough to handle most searches. That was why we "slowed down" MSFragger by adding more steps to get better results. 

If you really want the "fastest" params, you can start by changing `calibrate_mass` to 0, setting missed cleavages to 0, removing all variable modifications, etc. But I am not sure if it is a good idea.....

Best,

Fengchao

**Comment by zachdwight** [comment]
Sure - completely understood.  Better results take time but for our group also important to think of these processes in a production environment.  For example, QC at the bench doesn't always require the most fine-tuned metrics or in-depth answer, but in reality can be more topical (to save time and computational resources).  So you say start with 'better results' which is completely fair and I say start with 'fastest / minimal resources' and some where in the middle is a good answer :)

Thanks for the pointers !

**Comment by anesvi** [comment]
If you are doing open searches or nonspecific searches params become more important and we can provide some additional suggestions (but be specific what searches you are doing)
