### ISSUE TITLE
Missing columns in FragPipe output file "combined_peptide.tsv"

### ISSUE THREAD

**Issue by RobAlbn** [Nesvilab/FragPipe#1234]
- Describe the issue or question:
I am using FragPipe for the analysis of a TMT dataset. However, the "combined_peptide.tsv" file does not contain all the columns that are listed here: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_peptidetsv. In particular, I would be interested in getting the information in the column "Mapped Proteins", which is missing. Do you have any idea about the reason why this column is missing from the output file? Are there any other methods to obtain the same information (i.e., all the proteins to which each peptide mapped) from other FragPipe output files?
Thank you for any help/suggestion

**Comment by dpolasky** [comment]
Some of the columns described in the documentation for the combined_peptide.tsv are added by IonQuant for label free analyses. For TMT analyses, IonQuant is not run (the quantitative information is in the tmt-report folder instead of the combined_*.tsv). Currently the mapped proteins are not propagated to the report files except by IonQuant, but you can check the individual peptide.tsv files (within each experiment folder) to find them for each experiment.  

Best,
Dan

**Comment by RobAlbn** [comment]
Thank you very much for your answer!
