### ISSUE TITLE
Automatic setting selection feature of FragPipe modifies saved workflows without notifying user

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/FragPipe#1258]
I tried running a DIA open search with a DIAUmpire-MSFragger-PeptideProphet workflow, which has worked well for me many times. However, after I had loaded my workflow, I realized I needed to add a couple more files. I did so, but FragPipe automatically switched PSM validation off entirely (unchecked PSM validation, and the whole section was grayed out) - however, I did not know it did that, I forgot to check that tab like I normally do, and so the search did not complete because there was no PSM validation option turned on. I'm not sure why FragPipe did this.

Unfortunately, it looks like I cannot restart the search at the PSM validation stage, because there is a limitation in PeptideProphet with line length and the number of files I am searching (342) - see issue at https://github.com/Nesvilab/FragPipe/issues/247. The DIAUmpire-MSFragger search took 4+ days, and it looks like I have to restart entirely now, unless the PeptideProphet issue can be resolved (please help!).

Thus, I would like to add the constructive criticism that while I understand (and appreciate) FragPipe's automatic setting selection feature, it can be, as currently implemented, quite a headache. In this case, I am very confused as to why PSM validation was turned off entirely, which is a new wrinkle. However, there have been other variations on this issue. For example, I load a workflow which includes PeptideProphet. I then load mzXML DIA files, but FragPipe thinks they are DDA for some reason, so I change the file type to DIA. FragPipe then decides I should be using Percolator and makes that switch automatically. However, there is no notification that FragPipe made that switch and it runs the pipeline with Percolator instead of PeptideProphet.

In general, these changes to my workflow are very frustrating because I am using a saved workflow that I know works (and which maintains reproducibility between experiments and runs), but then FragPipe modifies it without telling me. I then only find out after the run completes (or crashes). I would suggest that A) this feature be discontinued and FragPipe never modifies settings to a saved workflow, or B) at least there is a dialogue window that pops up, with the suggested feature changes vs ones currently selected, and the option to accept or decline. 

Overall, though, FragPipe and its constituents are critical tools for my research and I appreciate all the work that goes into developing and maintaining them. Just wanted to mention this because it has been a bit of a headache for a little while. 

Josh

**Comment by jossmi** [comment]
To clarify, I am not saying that the saved workflow file is altered, just that the settings loaded from the workflow are then modified by FragPipe without notifying the user

**Comment by fcyu** [comment]
Hi Josh,

Thanks for the long message. Let me respond them point-by-point:

> However, after I had loaded my workflow, I realized I needed to add a couple more files. I did so, but FragPipe automatically switched PSM validation off entirely (unchecked PSM validation, and the whole section was grayed out) - however, I did not know it did that, I forgot to check that tab like I normally do, and so the search did not complete because there was no PSM validation option turned on. I'm not sure why FragPipe did this.

I could not reproduce it. Please see my following screen recording. Please make sure that you did not mess up the settings or configurations.
![Animation2](https://github.com/Nesvilab/FragPipe/assets/6926299/d99fa1b9-e395-4484-a8c5-efbce38dc8b8)

> Unfortunately, it looks like I cannot restart the search at the PSM validation stage, because there is a limitation in PeptideProphet with line length and the number of files I am searching (342) - see issue at https://github.com/Nesvilab/FragPipe/issues/247. The DIAUmpire-MSFragger search took 4+ days, and it looks like I have to restart entirely now, unless the PeptideProphet issue can be resolved (please help!).

Please see my respond to the other issue (https://github.com/Nesvilab/FragPipe/issues/247#issuecomment-1730522564). You are doing something uncommon and untested. Also, I would not perform open search for the DIA pseudo MS/MS spectra because the spectra have fragment peaks from other peptides.

> Thus, I would like to add the constructive criticism that while I understand (and appreciate) FragPipe's automatic setting selection feature, it can be, as currently implemented, quite a headache. In this case, I am very confused as to why PSM validation was turned off entirely, which is a new wrinkle.

Again, I could not reproduce. See my previous comment.

> However, there have been other variations on this issue. For example, I load a workflow which includes PeptideProphet. I then load mzXML DIA files, but FragPipe thinks they are DDA for some reason, so I change the file type to DIA. FragPipe then decides I should be using Percolator and makes that switch automatically. However, there is no notification that FragPipe made that switch and it runs the pipeline with Percolator instead of PeptideProphet.

That is because we want users to use Percolator for the DIA data analysis. Using PeptideProphet is not recommended. We have designed rigorous dependency logic and workflows to let FragPipe performs in the optimal settings. If you really want to change the parameters to the uncommon or unrecommended setting, take all the risks by yourself.

> In general, these changes to my workflow are very frustrating because I am using a saved workflow that I know works (and which maintains reproducibility between experiments and runs), but then FragPipe modifies it without telling me. I then only find out after the run completes (or crashes). I would suggest that A) this feature be discontinued and FragPipe never modifies settings to a saved workflow, or B) at least there is a dialogue window that pops up, with the suggested feature changes vs ones currently selected, and the option to accept or decline.

For most users, we suggest loading the built-in workflow and making as little changes as possible (the reason has been mentioned in the above comment). If you think you are an advanced user, and know FragPipe well enough to make your own changes, you can do that, but you will also be response for your changes.

Best,

Fengchao
