### ISSUE TITLE
Process 'MSBooster' finished, exit code: 1 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by lianghao2023** [Nesvilab/FragPipe#1264]
Hi all,

I am using MSfragpipe's default LFQ-MBR workflow for analyzing global proteome data. Unfortunately, I met the following error:

"Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping"

I would greatly appreciate it if someone could let me know how to troubleshoot this error.

Best regards,
Lianghao
[log_2023-09-27_09-40-31.txt](https://github.com/Nesvilab/FragPipe/files/12736030/log_2023-09-27_09-40-31.txt)

**Comment by danielgeiszler** [comment]
Can you confirm that

 java.io.FileNotFoundException: D:\Qian_proteome\Fragpipe_Output\timsTOF2_4369_8-24-2023_Slot2-10_230823_TIMS02_LiMa_400ng_A31.pin (The system cannot find the file specified)

This file is in the location it is supposed to be? Also, is D:\ a network drive or local?

**Comment by lianghao2023** [comment]
Hi Daniel,

This file is not in that location but in the bottom file of same folder.  'D:\Qian_proteome\Fragpipe_Output\A31'
'D:\' is a local drive of PC.

Same for all the other generated 'XXX.pin' files. They are all in the individual folder but not 'D:\Qian_proteome\Fragpipe_Output\'.

Thanks for the help.

Best,
Lianghao

**Comment by fcyu** [comment]
Somehow MSBooster could not find the file `D:\Qian_proteome\Fragpipe_Output\timsTOF2_4369_8-24-2023_Slot2-10_230823_TIMS02_LiMa_400ng_A31.pin`. @yangkl96 could you take a look?

Thanks,

Fengchao

**Comment by yangkl96** [comment]
Hi Lianghao,

Could you please share with me the file at D:\Qian_proteome\Fragpipe_Output\msbooster_params.txt?

Thanks,
Kevin

**Comment by Monod79** [comment]
Hi Fengchao, 

I'm having a similar error while running an LFQ workflow on an HPC system. I'm running 48 different conditions (with duplicate) separately. 43 out of the 48 jobs completed without error. 

Any idea ? 

Thanks !

*****************************MAIN SEARCH DONE IN 0.392 MIN***************************

*******************************TOTAL TIME 2.928 MIN********************************
Process 'MSFragger' finished, exit code: 0
MSFragger move pepxml
java -cp /home/monod79/fragpipe/lib/fragpipe-21.1.jar:/home/monod79/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err /home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220125_COT_04.pepXML /lustre07/scratch/monod79/FragPipe_data/COTE/Laura/RAS/HeLa/DIRAS3_A46V/DIRAS3_A46V_1/QE_20220125_COT_04.pepXML
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pin
java -cp /home/monod79/fragpipe/lib/fragpipe-21.1.jar:/home/monod79/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err /home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220125_COT_04.pin /lustre07/scratch/monod79/FragPipe_data/COTE/Laura/RAS/HeLa/DIRAS3_A46V/DIRAS3_A46V_1/QE_20220125_COT_04.pin
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Process 'MSFragger move pin' finished, exit code: 0
MSFragger move pepxml
java -cp /home/monod79/fragpipe/lib/fragpipe-21.1.jar:/home/monod79/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err /home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220201_COT_02.pepXML /lustre07/scratch/monod79/FragPipe_data/COTE/Laura/RAS/HeLa/DIRAS3_A46V/DIRAS3_A46V_2/QE_20220201_COT_02.pepXML
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pin
java -cp /home/monod79/fragpipe/lib/fragpipe-21.1.jar:/home/monod79/fragpipe/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err /home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220201_COT_02.pin /lustre07/scratch/monod79/FragPipe_data/COTE/Laura/RAS/HeLa/DIRAS3_A46V/DIRAS3_A46V_2/QE_20220201_COT_02.pin
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Process 'MSFragger move pin' finished, exit code: 0
MSBooster [Work dir: /lustre07/scratch/monod79/FragPipe_data/COTE/Laura/RAS/HeLa/DIRAS3_A46V]
java -Djava.awt.headless=true -Xmx15G -cp /home/monod79/fragpipe/tools/msbooster-1.1.28.jar:/home/monod79/fragpipe/tools/batmass-io-1.30.0.jar Features.MainClass --paramsList /lustre07/scratch/monod79/FragPipe_data/COTE/Laura/RAS/HeLa/DIRAS3_A46V/msbooster_params.txt
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
MSBooster v1.1.28
Using 4 threads
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220325_COT_03.11591318.0.fragtmp
        at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
        at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.apache.commons.io.FileUtils.toList(FileUtils.java:3035)
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2150)
        at Features.PinMzmlMatcher.<init>(PinMzmlMatcher.java:78)
        at Features.MainClass.main(MainClass.java:546)
Caused by: java.nio.file.NoSuchFileException: /home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220325_COT_03.11591318.0.fragtmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
        at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
        ... 12 more
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 21 remaining tasks**

**Comment by fcyu** [comment]
It is a little weird. Why did MSBooster looked for the `/home/monod79/scratch/FragPipe_data/COTE/Laura/RAS/QE_20220325_COT_03.11591318.0.fragtmp` which is the temp file generated and used by MSFragger?

@yangkl96 , could you take a look?

Thanks,

Fengchao

**Comment by Monod79** [comment]
As always, I'm willing to share any required files

**Comment by Monod79** [comment]
To be more precise, I'm running FragPipe's latest version 21.1

**Comment by yangkl96** [comment]
Hello,

The issue arose because the temp files produced by MSFragger were still being deleted while MSBooster was running. MSBooster detected that file and then checked if it was an mzml file, but it was deleted in the middle of that check, hence the error.

We have changed our code to be more robust to an event like you encountered. If you rerun from the MSBooster step, unchecking the MSFragger box, you should be able to run through the rest of the code with no issue.

Let us know if that resolves the issue,
Kevin

**Comment by Monod79** [comment]
My situation involves 48 independent FragPipe process on an HPC system. Therefore, I want to prevent this kind of error in future processes without having to rerun everything a 2nd time without the MSFragger option.

If I cancel the "Delete temp files" option, would it prevent this error ?

**Comment by fcyu** [comment]
Hi @Monod79 ,

It is just a small bug that only be triggered when the file system has big latency which might happen on some HPC system. I have fixed it here https://github.com/Nesvilab/MSBooster/commit/7fab565387d22295f2f904ee7f487b10cfa1c71c

> If I cancel the "Delete temp files" option, would it prevent this error ?

No.

Best,

Fengchao

**Comment by Monod79** [comment]
Many thanks Fengchao for your quick response ! 

 The modification is in a java file, but how do I integrate this MSBooster modification into FragPipe ? How do I get the msbooster-x.x.xx.jar file containing the modification?

**Comment by fcyu** [comment]
@yangkl96 can send you a pre-released version. But remember that it is a pre-released version with many unstable changes. Use at your own risk.

Best,

Fengchao

**Comment by yangkl96** [comment]
https://www.dropbox.com/scl/fi/t8cce4wd4lkfs6iaiuuwr/MSBooster-1.2.7.jar?rlkey=xysbba9ppw8tulna8qcjp4wk4&dl=0

**Comment by yangkl96** [comment]
No problem, let us know if this works for you!

**Comment by Monod79** [comment]
Sure !

**Comment by Monod79** [comment]
Works like a charm!  

Thanks again @yangkl96 and @fcyu !
