### ISSUE TITLE
Problem building from scratch

### ISSUE THREAD

**Issue by baynec2** [Nesvilab/FragPipe#1307]
I am trying to build fragpipe from scratch so I can use it on the triton shared computing cluster (https://www.sdsc.edu/services/hpc/tscc/index.html), and I am running into a problem I am hoping someone can help with. 

I followed the instructions in the readme:

`cd ./MSFragger-GUI
./gradlew makeReleaseZipNoJre`

 but after doing so, I end up getting the error:

`Could not copy file '/home/chbayne/FragPipe/MSFragger-GUI/test/resources/fragpipe-incompatible-file-names/123-������������.mzml'`

The full build scan can be found here: https://scans.gradle.com/s/ufwhqanf63mw2. Would someone be able to help point me in the right direction with how to proceed here?

**Comment by fcyu** [comment]
Normally, you don't need to compile FragPipe by yourself. You just need to download the zip package from https://github.com/Nesvilab/FragPipe/releases/latest . Here has some tutorials in case you don't know: https://fragpipe.nesvilab.org/

Best,

Fengchao

**Comment by baynec2** [comment]
Great! Thanks so much for the info.

**Comment by fcyu** [comment]
You are welcome.

I took another looks at the error message, it should be due to the incompatible character sets in the test file names (`123-привет.mzml`). If you still want to compile FragPipe by yourself, you can delete that file in `FragPipe/MSFragger-GUI/test/resources/fragpipe-incompatible-file-names` and `FragPipe/MSFragger-GUI/test/resources/fragpipe-incompatible-file-names-2`, and try again. Those files are just for unit test.

Best,

Fengchao

**Comment by baynec2** [comment]
That worked! Thanks again.
