### ISSUE TITLE
PTM-Shepherd: %PSMs to go above 100%

### ISSUE THREAD

**Issue by MHBI2018** [Nesvilab/FragPipe#1316]
Hello, 

How can I interpret localization level data from extended reports? The values that I'm getting from combined enrichments for each residue is a range or two numbers. For example: Combined_A_enrichment is reported as 0.8730 - 198.0446.

Another question in regards to the PSM counts: the percentages don't add up to 100%. When it's under 100%, is it for PSMs being filtered out? Also, what causes the reported %PSMs to go above 100%?

Thank you

**Comment by dpolasky** [comment]
Hi,
You can find descriptions of the output files for PTMShepherd here: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#globalprofiletsv

I would guess the enrichment range is the min/max across experiments, but I'll leave that one for Danny. 

I believe the PSM percentages don't add up to 100% because of filtering - peaks with too few PSMs (based on your Peak minimum PSMs setting) are not reported, so PSMs from those peaks will not appear in the report. I have not seen the percentage above 100% - I don't think that should be possible. 

Best,
Dan

**Comment by MHBI2018** [comment]
Thank you Dan for the quick response! I understand that filtering can reduce PSMs, but I noticed when searching different DDA files under the same experiment that the total percentage went up to 106% which was odd.

**Comment by danielgeiszler** [comment]
Hi, 

Really sorry about the delay, I missed this notification. Can you please share the file where there is >100% PSMs and I'll get back to you as soon as I can.

**Comment by MHBI2018** [comment]
Hi Danny,

No worries. This is not urgent, but good to know why that happened. Here are the two files. The %PSMs exceeds 100% in the global mod profile. 
[global.modsummary.xlsx](https://github.com/Nesvilab/FragPipe/files/13443917/global.modsummary.xlsx)
[global.profile.xlsx](https://github.com/Nesvilab/FragPipe/files/13443918/global.profile.xlsx)

**Comment by danielgeiszler** [comment]
The % PSMs can go above 100 in that file because peptides can have multiple modifications, thus being assigned to multiple rows.

Imagine if 50% of your peptides are phosphorylated, 25% are methylated, and 25% are methylated and phosphorylated.

That table will show 75% phosphorylated and 50% methylated.

**Comment by MHBI2018** [comment]
Thank you Danny!
