### ISSUE TITLE
RT deviation of DIA data is about 4min. Whether it can be analyzed correctly?

### ISSUE THREAD

**Issue by Liu-jie8** [Nesvilab/FragPipe#1323]
- Describe the issue or question:

The sample retention time deviation of DIA data is about 4min due to instrument maintenance. Is there any problem when analyzing with fragpipe v17.1 (workflow is DIA SpecLib Quant)? What special parameter Settings are required for release?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
First of all, could you upgrade FragPipe to the latest version (20.0)? 17.1 is too old. Second, what kind of RT deviation do you have? All injection are different from each other? At any rate, I still think FragPipe can handle it because the RTs in the generated library is in iRT scale, the DIA-NN quant will scale it for each run, and FragPipe doesn't run DIA-NN quant in MBR mode.

Best,

Fengchao

**Comment by Liu-jie8** [comment]
Thank you. It's the overall RT deviation between samples before and after instrument maintenance.
