### ISSUE TITLE
unique peptides in the peptide.tsv file

### ISSUE THREAD

**Issue by Me9atron** [Nesvilab/FragPipe#1330]
- Describe the issue or question:
Hello Developers,

In the results file peptide.tsv, I do not find any columns that specify if a peptide is a unique peptide for a protein or a protein group. Do you know if there are some ways to know whether each identified peptide is "unique peptide"? Thank you.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
psm.tsv files have the "Is Unique" column. I can let IonQuant write those columns in the other tsv files in the future for the DDA MS1 quant workflow.

Best,

Fengchao

**Comment by fcyu** [comment]
> I do not see REV proteins in protein.tsv, have they already been removed before writing result file?

Correct. Decoy IDs (proteins, peptides, and PSMs) are not included in the tsv reports.

> What would you suggest deal with proteins "Only Identified by Sites" (Oxidation and Deamidation)? 

We don't have such thing: "Only Identified by Sites". So, you don't need to bother filtering them in the FragPipe output.

BTW, if you are doing label-free or isotopic-labelling quantification, maybe you should use the "combined_*.tsv" files because the intensities are normalized and there are "MaxLFQ intensity" (similar to the "LFQ intensity" in MaxQuant).

If you are doing the isobaric-labeling quantification, you should use the tsv reports in the "tmt-report" folder because the intensities are normalized.

The intensities in the psm.tsv, ion.tsv, peptide.tsv, and protein.tsv of the individual experimental folders are not normalized. They are just "raw" intensity.

Best,

Fengchao

**Comment by Me9atron** [comment]
Thank you, Fengchao, your answers are very detailed and useful. I am doing isobaric-labelling (TMTpro 16plex), I will use the tsv reports in the "tmt-report" folder.
