### ISSUE TITLE
Error removing Proteinprophet.exe "Access is denied" on virtual machine

### ISSUE THREAD

**Issue by hottestdude** [Nesvilab/FragPipe#1353]
- Describe the issue or question:

Hi! I'm trying to configure fragpipe to work on a virtual machine but keep running into this error (attached). I've tried tweaking all the access and control properties of the temp folders and fragpipe/philosopher but nothing is able to affect this error. 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2023-11-29_19-03-36.txt.zip](https://github.com/Nesvilab/FragPipe/files/13506880/log_2023-11-29_19-03-36.txt.zip)

**Comment by fcyu** [comment]
It seems that the program couldn't read some file due to the file permission configurations: `C:\Research\fragpipe\temp\c418a671-7e8c-4bde-856b-aae705d5bfd2\ProteinProphet.exe: Access is denied.`. I think you need to troubleshoot your folders' read and write permission configuration locally. 

Best,

Fengchao

**Comment by hottestdude** [comment]
Fengchao,

Thanks, I was able to get past the error by adding permissions to the "everyone" object to the entire Local Disk (C:) drive.

**Comment by fcyu** [comment]
You are welcome.
