### ISSUE TITLE
Fragpipe Error DDA StringIndex Out of Bounds

### ISSUE THREAD

**Issue by DrDee79** [Nesvilab/FragPipe#1363]
- I am trying to run a batch of DDA phosphopeptide data, and every time I get to Slice 2 I get a odd StringIndex error. This has happened with versions 19.2 and 20, on multiple computers. It isn't the same file every time, so I'm at a loss as to what to do. Apologies I don't have the whole log, but I hope this might be informative. Thanks for any help! 

Operating on slice 2 of 2: 
	Fragment index slice generated in 30.16 s
	001. DOA310Px_Hu13_A10__500nM_Polqi_10uM_Bleomycin_A_r1_DIA_112723_S1-A10_1_7152.mzBIN_calibrated 0.5 s
		[progress: 25245/25245 (100%) - 31360 spectra/s] 0.8s | remapping alternative proteins and postprocessing 10.1 s
	002. DOA310Px_Hu13_A10__500nM_Polqi_10uM_Bleomycin_A_r2_DIA_112723_S1-A10_1_7202.mzBIN_calibrated 0.4 s
		[progress: 17072/17072 (100%) - 30004 spectra/s] 0.6s | remapping alternative proteins and postprocessing 9.1 s
	003. DOA310Px_Hu13_A11_LPSCytostim_DMSO_10uM_Bleomycin_A_r1_DIA_112723_S1-A11_1_7156.mzBIN_calibrated 0.6 s
		[progress: 29416/29416 (100%) - 30674 spectra/s] 1.0s | remapping alternative proteins and postprocessing 10.7 s
	004. DOA310Px_Hu13_A11_LPSCytostim_DMSO_10uM_Bleomycin_A_r2_DIA_112723_S1-A11_1_7207.mzBIN_calibrated 0.4 s
		[progress: 18943/18943 (100%) - 31415 spectra/s] 0.6s | remapping alternative proteins and postprocessing 9.1 s
	005. DOA310Px_Hu13_A12_LPSCytostim_500nM_Polqi_10uM_Bleomycin_A_r1_DIA_112723_S1-A12_1_7161.mzBIN_calibrated 0.7 s
		[progress: 30290/30290 (100%) - 33618 spectra/s] 0.9sjava.lang.StringIndexOutOfBoundsException: start 226, end -1, length 234
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.replace(Unknown Source)
	at java.base/java.lang.StringBuilder.replace(Unknown Source)
	at z.b(Unknown Source)
	at z.b(Unknown Source)
	at p.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
I need your files to reproduce this bug. Could you upload everything including mzML files, fasta files, and workflow files to https://www.dropbox.com/request/WrsiUmZhGh3aeo91n80o

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi @DrDee79 , 

I see that you uploaded several files. I am not sure if you have finished the uploading, but just want to let you know the one causing the problem: `DOA310Px_Hu13_A12_LPSCytostim_500nM_Polqi_10uM_Bleomycin_A_r1_DIA_112723_S1-A12_1_7161` was not uploaded. 

Also, it seems that your input is .d folder. Could you upload `DOA310Px_Hu13_A12_LPSCytostim_500nM_Polqi_10uM_Bleomycin_A_r1_DIA_112723_S1-A12_1_7161.d` ? Other runs might not needed if I can reproduce the issue with that single .d folder.

Best,

Fengchao

**Comment by DrDee79** [comment]
Thanks I'll upload that one shortly-but I want to add though the log shows
the issue was with this file, I tried other permutations of this file set
without it (just a few) and still had this error.

Thanks, Dorothy

**Comment by fcyu** [comment]
Hi Dorothy,

Thanks for the hint. I reproduced the error using your other mzML files. 

It looks like your fasta file is the combination of the human proteins from different sources, including UniProt, NCBI, Ensembl, PEFF from nextprot, and decoys. The following are some examples and the PEFF one broke MSFragger.

1. `>DECOY_A0A077GZU2 Decoy sequence`
2. `>DECOY_NX_Q9BU79-1 Decoy sequence`
3.  `>rev_A0A076MDE1 UPTr tr|A0A076MDE1|A0A076MDE1_HUMAN ATP synthase protein 8 OS=Homo sapiens OX=9606 GN=ATP8 PE=3 SV=1`
4. `>rev_DECOY_A0A0C4DFS1 Decoy sequence`
5. `>A0A023HN28 UPTr tr|A0A023HN28|A0A023HN28_HUMAN SRSF3/USP6 fusion protein (Fragment) OS=Homo sapiens OX=9606 PE=2 SV=1`
6. `>ENSP00000334805.1 pep chromosome:GRCh38:12:48328980:48330279:1 gene:ENSG00000187166.1 transcript:ENST00000335017.1 gene_biotype:protein_coding transcript_biotype:protein_coding gene_symbol:H1-7 description:H1.7 linker histone [Source:HGNC Symbol;Acc:HGNC:24893]`
7. `>NP_001128410.1 NP_001128410.1 pre-mRNA 3'-end-processing factor FIP1 isoform 3 [Homo sapiens]`
8. `>O75154 nP20K \PName=Rab11 family-interacting protein 3 isoform Iso 1 \GName=RAB11FIP3 \NcbiTaxId=9606 \TaxName=Homo Sapiens \Length=756 \SV=1 \EV=178 \PE=1 \ModResPsi=(52|MOD:00046|O-phospho-L-serine)(88|MOD:00046|O-phospho-L-serine)(102|MOD:00046|O-phospho-L-serine)(281|MOD:00046|O-phospho-L-serine)(348|MOD:00046|O-phospho-L-serine)(488|MOD:00046|O-phospho-L-serine)(538|MOD:00046|O-phospho-L-serine)(647|MOD:00046|O-phospho-L-serine)(648|MOD:00046|O-phospho-L-serine) \VariantSimple=(3|L)(3|T)(7|S)(9|S)(9|T)(11|V)(12|W)(15|R)(19|R)(21|R)(21|S)(24|L)(26|A)(27|R)(28|V)(29|S)(29|V)(30|S)(31|R)(33|T)(33|V)(34|L)(35|D)(36|L)(36|T)(37|E)(37|V)(39|P)(39|R)(40|C)(42|R)(47|S)(48|R)(48|T)(52|F)(55|Q) \Processed=(1|756|PEFF:0001020|mature protein)`

No. 1~4 seems to be decoys. I guess your original database has the decoy proteins with `DECOY_` prefix, and then, you let FragPipe generate another version of decoys with prefix `rev_`, which is not good because two version of decoys will break the scoring and FDR model.

No. 5~8 seems to be targets from different sources. It is also not good because there are a lot of redundant proteins, which break protein grouping algorithm.

I suggest you use FragPipe to download a new database by using the function in the "database" tab and try again.

I will also change MSFragger to make it more robust to the PEFF format.

Best,

Fengchao

**Comment by DrDee79** [comment]
Thanks for taking a look. That's really really odd as what you suggested is
exactly what I did... Downloaded and added decoys. I'll try a new one and
see if that fixes it!

**Comment by fcyu** [comment]
The file name, "2023-12-07-decoys-Homo_sapiens.fasta.fas", does not looks like downloaded by FragPipe. It should be from FragPipe adding the decoys using your original "Homo_sapiens.fasta" file. 

BTW, to download a new fasta file, you should click "Download". The other one, "Add decoys", just add decoys to your given target-only fasta file.

Best,

Fengchao
