### ISSUE TITLE
Percolator issue

### ISSUE THREAD

**Issue by MargaAC** [Nesvilab/FragPipe#1374]
Hello! We are new using MS Fragger and we have some problems. Can anyone help us, please?

Percolator [Work dir: C:\Users\SCIEXProc\Documents\GEMAT\RVA\MS_FRAGGER\OUTPUT]
C:\Proteomica\FragPipe-20.0\fragpipe\tools\percolator-306\percolator.exe --only-psms --no-terminate --post-processing-tdc --num-threads 5 --results-psms 231213_602_1a10_231213_1a_percolator_target_psms.tsv --decoy-results-psms 231213_602_1a10_231213_1a_percolator_decoy_psms.tsv --protein-decoy-pattern rev_ 231213_602_1a10_231213_1a.pin
Process 'Percolator' finished, exit code: -1073741819
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks

**Comment by fcyu** [comment]
This is a known issue: https://github.com/Nesvilab/FragPipe/issues/1160, https://github.com/Nesvilab/FragPipe/issues/1211, https://github.com/Nesvilab/FragPipe/issues/1227, https://github.com/Nesvilab/FragPipe/issues/1269, https://github.com/Nesvilab/FragPipe/issues/1270, and https://github.com/Nesvilab/FragPipe/issues/1313. Has been fixed in version 21.0: https://github.com/Nesvilab/FragPipe/releases/tag/21.0

Best,

Fengchao
