### ISSUE TITLE
Question about change in usage of psm-only flag in Percolator for DIA workflows

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#1380]
- Describe the issue or question:
In FragPipe v21 noticed that the --only-psms flag in Percolator was removed for DIA workflows, but is retained for a few of the typical DDA workflows I looked at, e.g., LFQ-MBR.  I have been using the DIA_SpecLib_Quant workflow to generate spectral libraries, but using DDA files so quant aspect is not used. I am analyzing Bruker .d.  Since I am not using DIA data, would you recommend to add back the psm-only flag?  If so, then perhaps to avoid confusion it might be useful to create a built-in workflow for only SpecLib generation with DDA and no Quant, e.g., DDA_SpecLib. 

Todd

**Comment by fcyu** [comment]
Hi Todd,

With or without `--only-psms` doesn't matter much regarding the spectral library building because EasyPQP, the spectral library building tool, remove the redundant PSMs and pick the highest probability one in any way. Without `--only-psms`, FragPipe just tosses out redundant PSMs in an earlier stage, which results in fewer PSMs  and smaller file sizes.

Best,

Fengchao

**Comment by enonimos** [comment]
When EasyPQP discards redundant PSMs, does it write in the library how many total SPC were associated with that ion?  If it has that function, then without --only-psms, there is no redundant info provided to EasyPQP and so it would record 1 for all ion in the library?

Todd

**Comment by fcyu** [comment]
> When EasyPQP discards redundant PSMs, does it write in the library how many total SPC were associated with that ion?

No, it does not.

Best,

Fengchao
