### ISSUE TITLE
Question about how to convert pepxml to psm.tsv: use FragPipe!

### ISSUE THREAD

**Issue by NormanRog** [Nesvilab/FragPipe#1386]
For my project, I need to be able to reproduce/filter the spectra of the psm.tsv from a pepxml file.
I tried it by filtering for the expectation value, or using the fdr filtering of the pyteomics pepxml module.
Also I tried to reproduce the spectra from the interact-pep.xml files by filtering for the peptideprophet_propability score
with the threshold mentioned in the filter.log file, which also didn't work.

Is there a way to reproduce the spectra in the psm.tsv from the pepxml files?

**Comment by fcyu** [comment]
Yes, using FragPipe! We have plenty of tutorial here for you to learn: https://fragpipe.nesvilab.org/

BTW, I don't think reinventing the wheel by writing your own script using pyteomics is a good idea. It is waste of the time since FragPipe already can do all the job for you within one click.

Enjoy,

Fengchao
