### ISSUE TITLE
Continue running DIA-umpire extracted signal

### ISSUE THREAD

**Issue by LKittinun** [Nesvilab/FragPipe#1408]
I have run the DIA-DIA-umpire-speclib-quant workflow but get errors in some parts. I want to rerun since from the msfragger part, but when I unchecked DIA-umpire, it seemed not to recognize the extracted library I ran earlier. What should I do in this case? Should I add the extracted signal files as DIA-lib?

Sincerely,

**Comment by fcyu** [comment]
> it seemed not to recognize the extracted library I ran earlier.

I am not sure if I follow it. If you want to rerun from the MSFragger, there is no library generated because it was generated by EasyPQP which is the second last step.

> What should I do in this case? Should I add the extracted signal files as DIA-lib?

You can load both `*_Q1/2/3.mzML` file and the original mzML files. And then, specify the `*_Q1/2/3.mzML` files as `DIA-lib` and the original mzML files as `DIA-Quant`. It is a tricky approach. If you can't get it work, please re-run from scratch.

Best,

Fengchao

**Comment by LKittinun** [comment]
I mistakenly wrote it as a library. What I meant was extracted signal as you have anticipated. So my point was clearly answered.

Sincerely,
Kittinun
