### ISSUE TITLE
Labile_phospho workflow in hybrid mode 

### ISSUE THREAD

**Issue by Martavamo** [Nesvilab/FragPipe#1433]
I have been going through the tutorials for "Offset search for PTMs with FragPipe" and "Labile Search in MSFragger and FragPipe" to set my own workflow to search for phosphorylations in hybrid mode.

I had included:
- Variable modifications -> M (15.5949), [^ (42.0106), STY (79.96633)

- Mass offsets -> 0/79.96633
- Restricted delta to mass -> STY
- Labile modification search mode -> labile
- Remainder fragment masses -> -18.01056

To my understanding, with these parameters the presence of the modification will be accounted by the "variable modifications" settings, the possible loss of the modification by the "mass offset", and the additional possible loss of a H2O by the "remainder fragment masses".

 However, in the Fragpipe workflow "Labile_phospho" we can find:
- Remainder fragment masses -> -18.01056 79.96633

I imagine adding the mass of the modification as a "remainder fragment masses" would account for the nonlabile cases but, since we are already considering those cases through the variable modifications, isn't it redundant? If not, in which cases the mass of the modification should be added as "remainder fragment masses" if we want to perform a hybrid search?

Thank you!

**Comment by dpolasky** [comment]
Hi,
Yes, you are correct that adding the remainder fragment mass accounts for the nonlabile case, and so is partially redundant with a variable modification. The reason to consider both remainder ions is for peptides that have a mix of phosphate loss and retention, as including both -18 and +79 means both ion series are considered instead of just one. Considering multiple ion series adds a lot of noise, so often isn't helpful unless there are a lot of peptides with a mixed loss and retention - so you can certainly remove the 79.96 remainder fragment for the hybrid search, particularly if the data you're analyzing has relatively high collision energy. 

Best,
Dan

**Comment by Martavamo** [comment]
Got it 👍 

Thanks a lot, Dan!
