### ISSUE TITLE
Localisation with open search

### ISSUE THREAD

**Issue by Cajac102** [Nesvilab/FragPipe#1451]
Hello,

I'm having difficulties with interpreting the output of open search runs in terms of localisation as well. What I want to extract in the end are mass shifts that could be unambiguously localised at 1% PSM level FDR, and their position in the protein. Preferably using the localisation with the highest score after PTMShepherds rescoring.

I had a look at the protein.tsv file, but as Fengchao already said, it does not include localisation info.
According to the output column descriptions, the "MSFragger Localisation" column in the psm.tsv encodes the localisation information via lower case letters, and "Observed Modifications" shows the mapped UniMod entries (I assume that's one of the PTMShepherd post processing steps, since this column is empty when I don't run PTMShepherd). 
How do I read these? For example:

Assigned Modifications: "7C(57.0214)"
Observed Modifications: 
"Mod1: Unannotated mass-shift -3.8728 (PeakApex: -3.8822); 
Mod1: Unannotated mass-shift -0.9296, Mod2: Unannotated mass-shift -2.9672 (PeakApex: -3.8906); 
Mod1: Unannotated mass-shift -0.9296, Mod2: Unannotated mass-shift -2.9672 (PeakApex: -3.8960)"
MSFragger Localization: "vASTGVCHSDIHHMK"

I would assume that there was a modification that could be unambiguously mapped to the N-Term, since it's the only lower case letter.
1) Are the mass shifts within one ";" combinations that add up to the original mass shift?
2) Why is the second entry in there twice, except for a swapped number in the PeakApex entry?
3) How would a peptidoform show up that contains two modifications at different amino acids? (How would the Localization String differ from a peptidoform that has one modification, but the scores were equal across two sites?)

The example was from a run with FragPipe 21.1, MSFragger v. 4.0, PTMShepherd v2.0.6, PeptideProphet v5.1.0 on Windows 10.

Best,
Caro

**Comment by dpolasky** [comment]
Hi Caro,

The MSFragger localization column indeed shows the position(s) that had the best hyperscore from placing the modification there - but it may only be the best by a small amount, so seeing only one lower case letter doesn't necessarily imply a highly confident localization. In the next release, there will be additional columns in the PSM table providing more information about the scores with the delta mass at each position. If the main thing you're looking for is confident localization for a particular modification (or set of modifications), a mass offset or closed search would be preferable to an open search since you can use PTMProphet to provide specific localization probabilities for the modifications of interest for each PSM. 

I believe the three entries in the Observed Modifications column in your example are all possible explanations PTM-Shepherd came up with to explain the delta mass (different explanation options are separated by ';'). The first is a single delta mass of -3.87 and the others are combinations of -0.92 and -2.97. It looks like the peak has been split in the annotation step, leading to two essentially duplicate entries - you can try to prevent this by changing the PTM Profiling settings on the PTMs tab (increasing the smoothing and peak picking width, for example). But really the PTM-Shepherd annotations are intended as a general guide to understanding the open search mass shifts rather than a definitive explanation. 

Open search assumes that the delta mass is from a single site on the peptide - it will not attempt to score multiple modifications in different places on the peptide. Even if a delta mass is actually from two mods on different sites, the localization score reported is only from considering the full delta mass at each position, so it would be lower than the score for a peptidoform that really only has one modification since modification mass would not be correct for many of the fragment ion positions.

Best,
Dan

**Comment by Cajac102** [comment]
Hi Dan,
Thanks for the extensive answer! 
Having information on the localisation confidence would be really helpful. Do you have an estimate when the next version is going to be released?

Best,
Caro

**Comment by dpolasky** [comment]
Probably within a few months, but if you would like to try it out now as a pre-release version (with the caveat that there may be some unresolved issues) you can - just send me an email at dpolasky [at] umich.edu and I'll share it with you. 

Best,
Dan
