### ISSUE TITLE
questions in open search

### ISSUE THREAD

**Issue by ibphuangchen** [Nesvilab/FragPipe#1468]
Dear FragPipe team,

I am interested in using your tool for open search in identifying unknown PTMs. When using your tools, I've noticed that in the final output **psm.txt**, the column of the "**Modified Peptide**" does not match the column "**Assigned Modifications**", for example, I have a row with "**Modified Peptide**" : **Q[111]ASDTGSNDAHNKK**, and **Assigned Modifications** : **1Q(-17.0265)**. I guessed that mass shift caused by the PTM is 111, but this is very different from **Assigned Modifications**. Could you explain how the  **Assigned Modifications** is generated?

Attached please find the param setting and the running logs.

Thank you for the kind help.

Chen

[fragger.params.txt](https://github.com/Nesvilab/FragPipe/files/14440109/fragger.params.txt)
[log_2024-02-26_17-04-41.txt](https://github.com/Nesvilab/FragPipe/files/14440110/log_2024-02-26_17-04-41.txt)

**Comment by fcyu** [comment]
`111 = round(residue_mass_of_Q - 17.0265)`

Best,

Fengchao

**Comment by ibphuangchen** [comment]
Hi Fengchao, - thank you for the explanation.

So 111 is the mass of the amino acid residue at that position. However, I saw that some values are negative. For example, there is a row: SGFEPASLKEEVGEEAIVELVEN[-13]GKK, why this N is mass negative?

Thanks!

**Comment by ibphuangchen** [comment]
Also, another question regarding to **Q[111]ASDTGSNDAHNKK**,  - based on your equation, _111 = round(residue_mass_of_Q - 17.0265)_, the residue_mass_of_Q is close to 128, which is the number without adding back the N terminal hydrogen atom. Just want to confirm this for the C terminal, the number is also the residue mass **without** _OH_, is that right?

**Comment by ibphuangchen** [comment]
_Could you share the spectral library file_

Could you inform me how to obtain this file? mzML?

**Comment by ibphuangchen** [comment]
https://drive.google.com/drive/folders/1W3kqbyK3m1hzLatkwntjSWexWRCWBw4I?usp=drive_link

In the psm.txt, you can see row # 62559 63674 63747.

Thank you for the help!

**Comment by fcyu** [comment]
Thanks for sharing the files.

First of all, what you have shared used the parameters different from the log file you shared in the first message. 

In your latest files, there are  `mass_diff_to_variable_mod=2`, which puts the delta mass as variable modifications. Basically, the delta masses from open search were placed to the localized amino acids as variable modifications. Since the localization is not 100% accurate, the delta mass might be on an amino acid with residue mass smaller than the delta mass. That was why you saw the negative values.

Most of the time, you don't need or should not change the `Report mass shift as a variable mod` option in MSFragger tab. If you are not sure, select the "Open" workflow and click "Load", and redo the search from scratch.

Best,

Fengchao

**Comment by ibphuangchen** [comment]
@fcyu  Hi Fengchao, I probably need to have some more explanation :(

Is the only difference between **mass_diff_to_variable_mod=0** vs **mass_diff_to_variable_mod=2** is that the '0' setting will not have the location? Will it still report [111] or [-13], the "residual amino acid mass"? 

I don't know what does this "keep delta mass" mean in **"# Put mass diff as a variable modification. 0 for no; 1 for yes and remove delta mass; 2 for yes and keep delta mass."**. Does it mean the file would literately list the delta mass or the values are resulted from delta mass subtraction?

The psm.txt and interact.pep.xml you've just inspected were indeed run by **unselecting** "Report mass shift as a variable mod" (i.e., default setting). I have now uploaded the log and fragger.params files.

The only change I made after loading the the Open workflow is removing the Cysteine Carbamidomethylation from the fixed modification, because my label-free samples were not processed with this modification.

**Comment by fcyu** [comment]
> Is the only difference between mass_diff_to_variable_mod=0 vs mass_diff_to_variable_mod=2 is that the '0' setting will not have the location? Will it still report [111] or [-13], the "residual amino acid mass"?

`0` means not put the delta mass as variable modification, so there will be no `[111]` or `[-13]` in the modified peptide column.

> I don't know what does this "keep delta mass" mean in "# Put mass diff as a variable modification. 0 for no; 1 for yes and remove delta mass; 2 for yes and keep delta mass.". Does it mean the file would literately list the delta mass or the values are resulted from delta mass subtraction?

Yes. I think you should not change that value (and other values that you are not sure about the meaning, otherwise, you will get weird results).

> The psm.txt and interact.pep.xml you've just inspected were indeed run by unselecting "Report mass shift as a variable mod" (i.e., default setting). I have now uploaded the log and fragger.params files.

No, they have `mass_diff_to_variable_mod=2`. And the `modified peptide` column in the psm.tsv also supports that.

<img width="530" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/6926299/dd15bbda-0c1e-4e69-8c66-737fa39186f1">

> The only change I made after loading the the Open workflow is removing the Cysteine Carbamidomethylation from the fixed modification, because my label-free samples were not processed with this modification.

The enzyme was also changed from stricttryptin to trypsin and `-17.0265 nQnC 1` was added as variable modification. I also noticed that your data has low-resolution MS2, which is not good for open search.

Best,

Fengchao

**Comment by ibphuangchen** [comment]
@fcyu But I checked fragger.params and log file, both showing **mass_diff_to_variable_mod = 0**. I am re-runing it to see whether it can be reproduced. (you're all right about my other params setting, and yes, the MS2 is ITMS with low resolution)

If the  **mass_diff_to_variable_mod = 0**, the informative results would only be global.profile.tsv, which is the PTM summary from all peptides.  I would imagine there are lots of cases where users want to know the delta mass and the location for each peptide, right?

**Comment by fcyu** [comment]
> I would imagine there are lots of cases where users want to know the delta mass and the location for each peptide, right?

Yes. Those information can be found in the `delta mass` and `MSFragger Localization` columns. But note that the localization is not always accurate due to the limitation of mass spectrometry.

Best,

Fengchao

**Comment by ibphuangchen** [comment]
> Yes. Those information can be found in the `delta mass` and `MSFragger Localization` columns. But note that the localization is not always accurate due to the limitation of mass spectrometry.

The **delta mass** column is confusing, and I don't think it reflects the mass difference between wildtype AA mass and AA mass after PTM. For example in my psm.txt, row 6, - I have GDRGDAGPKGADGSP[113]GK, so the delta mass should be 113- mass_of_P(97.1) = 15.9, but the delta mass column shows 0.        In other words, without setting **mass_diff_to_variable_mod = 2**, is there a way users can tell the mass shift is 15.9? 

Thanks,
Chen

**Comment by fcyu** [comment]
> The delta mass column is confusing, and I don't think it reflects the mass difference between wildtype AA mass and AA mass after PTM. For example in my psm.txt, row 6, - I have GDRGDAGPKGADGSP[113]GK, so the delta mass should be 113- mass_of_P(97.1) = 15.9, but the delta mass column shows 0. In other words, without setting mass_diff_to_variable_mod = 2, is there a way users can tell the mass shift is 15.9?

I am pretty sure that this example is with  `mass_diff_to_variable_mod = 2`. Open your pep.xml file with a text editor and search for "mass_diff_to_variable_mod". I believe you will agree with me after doing that.

In case you don't know, you need to click "load" after you select the workflow in the dropdown menu. We saw some users forget clicked that button.

Best,

Fengchao

**Comment by ibphuangchen** [comment]
@fcyu Hi Fengchao, I just rerun the pipeline and now I can see mass_diff_to_variable_mod=0 in all the files, including **interact.pep.xml**. The results started make sense to me, but I just wanted to confirm my understanding with you -

For the "known" modifications (are they the ones I set on the parameters?), for example, one row is **VM[147]DVHDGK** (column 'Modified Peptide'), **2M(15.9949)** (column 'Assigned Modifications'), **0.000** (column 'Delta Mass'). In this case, the total mass shift is 15.9949+0.00

For the psms with unknown modifications, their column 'Modified Peptide' is empty, and the total mass shifts are equal to the values in the column 'Delta Mass'.

When I compare the two results 'mass_diff_to_variable_mod=0' vs 2, it looks to me the 2 have still more information, for example:
<img width="1082" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/10239447/b0a55a9d-43e6-4b23-b697-8c78cbb4701c">

<img width="914" alt="image" src="https://github.com/Nesvilab/FragPipe/assets/10239447/d25b1c55-0c3d-4f5e-87a2-52ad2c712566">

i can see for the first results with 'mass_diff_to_variable_mod=2', the psm report the second modification is in the first amino acid E[623], which can not be known from the second results with 'mass_diff_to_variable_mod=0'. Is that right?

Thanks!!

**Comment by fcyu** [comment]
> For the "known" modifications (are they the ones I set on the parameters?), for example, one row is VM[147]DVHDGK (column 'Modified Peptide'), 2M(15.9949) (column 'Assigned Modifications'), 0.000 (column 'Delta Mass'). In this case, the total mass shift is 15.9949+0.00
>
> For the psms with unknown modifications, their column 'Modified Peptide' is empty, and the total mass shifts are equal to the values in the column 'Delta Mass'.

Correct. The **variable modification** in the MSFragger will be shown in "modified peptide" and "assigned modification", and the "unknown" modification from the open search will be shown as delta mass. This reflects how open search works.

For the variable modification case, I would not say the total mass shift is 15.9949+0.00 because 15.9949 technically is not a mass shift. And the "delta mass" might be not exactly 0 because of the mass errors.

> One more question, - when I compare the two results 'mass_diff_to_variable_mod=0' vs 2, it looks to me the '2' has still more information, for example:
>
>i can see that from the first results ('mass_diff_to_variable_mod=2'), a second modification (besides the known 2M(15.9949)) is in the first amino acid E[623], which can not be known from the second results with 'mass_diff_to_variable_mod=0'. Is that right?

Actually, no. No matter which mass_diff_to_variable_mod is, there is always a "MSFragger localization" column indicate all possible localized sites with lower case characters for the "unknown" modification. When `mass_diff_to_variable_mod > 0`, MSFragger will try to put the delta mass to the peptide but the site might be misleading when it can't be localized on a single site.

Best,

Fengchao

**Comment by ibphuangchen** [comment]
Thank you so much!!
