### ISSUE TITLE
No TMT channel columns in fragpipe

### ISSUE THREAD

**Issue by calmnine** [Nesvilab/FragPipe#1473]
- Describe the issue or question:

Hi. 
I ran TMT11-plex file using fragpipe.
There's no TMT channel columns of intensity in protein.tsv.
When I use fragpipe 21.1 with using msfragger 4.0 using sample file, workflow, manifest, there's a channel column in protein.tsv
Is there any update in TMT quantification?

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

[log_2024-03-04_16-50-33.txt](https://github.com/Nesvilab/FragPipe/files/14478671/log_2024-03-04_16-50-33.txt)

**Comment by fcyu** [comment]
Your log shows that MSFragger stopped due to not enough memory. 

I guess you uploaded the wrong log file. What you did maybe use IonQuant, that only writes the intensity to `psm.tsv`, as the "intensity extraction tool". For TMT analysis, you'd better use the intensity tables in the `tmt-report` folder because they are normalized. If you still want to have the TMT intensity in the `protein.tsv`, you could switch the "IonQuant" to "Philosopher" in the "Quant (Isobaric)" tab.

Best,

Fengchao
