### ISSUE TITLE
open search filtering by different FDR

### ISSUE THREAD

**Issue by ibphuangchen** [Nesvilab/FragPipe#1481]
Dear @fcyu ,

After the open search by MSFragger, is it possible to perform the filtering with a series of FDR values (like 0.05, 0.01, 0.005) without start all over from MS search? It looks to me that the interact.pep.xml contains all the prefiltered PSMs, but does it have the values to manually perform the filtering? If you could let me know which score or expectation value is used for the filtering, I can parse the interact.pep.xml and filter it myself. Thanks!!

Best,
Chen

**Comment by fcyu** [comment]
> After the open search by MSFragger, is it possible to perform the filtering with a series of FDR values (like 0.05, 0.01, 0.005) without start all over from MS search? 

Unfortunately, no. Because the FDR filtering in FragPipe is multi-layers. It filters the result using PSM-, ion-, peptide-, and protein-level FDRs combined. Before the FDR filtering, it also filter the PSMs with > 0.5 probability (by default). As you can see, it does not use a single FDR threshold to filter the results.

Even if you run FragPipe twice, you need to decide which FDR thresholds to change, which is not trivial.

>  It looks to me that the interact.pep.xml contains all the prefiltered PSMs, but does it have the values to manually perform the filtering?

No. 

Best,

Fengchao

**Comment by ibphuangchen** [comment]
I see, thanks!
