### ISSUE TITLE
Unrecognized mass causes error in DIA analysis but results from incorrect calculation of adduct mass

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/FragPipe#1515]
- Describe the issue or question:
I analyze DIA data from MZml files (generated from .raw files using msconvert). I am searching for several cysteine modifications. Towards the end I receive an error message indicating an unrecognized modification (mass 383.1991). However, when I open the psm file and look at peptide sequences identified with 383 modification, the observed mass shift is really 280 (which corresponds to the modification I was looking for). The same happens with other modification: peptides labeled with 460 modification are really shifted 357, and peptides labeled with 160 modification are really shifted 57. I am attaching the log file and the psm file. 

- Upload your log file

[log_2024-04-04_14-07-44.txt](https://github.com/Nesvilab/FragPipe/files/14865802/log_2024-04-04_14-07-44.txt)

[psm.txt](https://github.com/Nesvilab/FragPipe/files/14865808/psm.txt)

**Comment by fcyu** [comment]
The values in the `modified peptide` column is the summation of the modification mass and the amino acid mass.

The `unknown modification: 383.1991` error was due to DIA-NN not knowing the modification. In the `cmd line opts` of the `Quant (DIA)` tab, you need to use `--mod` flag to add your modification to DIA-NN's list: https://raw.githubusercontent.com/vdemichev/DiaNN/master/README.md#:~:text=of%20missed%20cleavages%0A*%20**-,%2D%2Dmod,-%5Bname%5D%2C%5Bmass%5D%2C%5Boptional

Best,

Fengchao
