### ISSUE TITLE
MSFragger searches for diagnostic ion peaks

### ISSUE THREAD

**Issue by liangxiao023** [Nesvilab/FragPipe#1559]
**- Describe the feature:**
Thank you for developing the excellent tool fragpipe. I would like to further localize the citrullination modification by adding diagnostic fragmentation peaks and I would like to ask if MSFragger can perform a search for neutral loss of isocyanate (HNOC, 43.01 Da) and ammonium ions (H11C5N3O, 129.09 Da)? If I can set the parameters, how should I do it? I hope the answer will be soon, thank you very much.

Best,
liangxiao

**Comment by danielgeiszler** [comment]
You can use the labile mode in FragPipe, described here:

https://fragpipe.nesvilab.org/docs/tutorial_labile.html

**Comment by liangxiao023** [comment]
![图片](https://github.com/Nesvilab/FragPipe/assets/74865902/943c85c9-2f09-40d9-b34e-61017b89cc79)

Thank you very much for your reply. But I still have some questions for you. In order to see the isocyanate dissociation that is often seen with citrulline. I used the following parameters to set up the detection of the HNOC diagnostic ion peak and the H11C5N3O citrulline dissociation residue (129.09 Da).I am not sure if this is the correct setting?

![图片](https://github.com/Nesvilab/FragPipe/assets/74865902/bed28a8e-4021-47df-8d07-3ae9eabf53d6)
![图片](https://github.com/Nesvilab/FragPipe/assets/74865902/3646e431-012b-408c-bad3-f041355431e7)

Other than that, I don't seem to see the delta mass column in my psm.tsv file with any information related to the diagnostic ion peaks, etc. that I've set up. Is it possible that I've set it up incorrectly?Very much looking forward to your reply and thank you for your selfless help!

Best,
liangxiao



> You can use the labile mode in FragPipe, described here:
> 
> https://fragpipe.nesvilab.org/docs/tutorial_labile.html

**Comment by dpolasky** [comment]
Hi liangxiao,

It looks like you need a couple of changes to the parameters. The m/z of the immonium ion should be specified as a diagnostic ion, and needs to include the mass of the charging proton since it needs to be m/z rather than mass (so 130.0975 not 129.09). The fragment remainder ion is calculated starting from the mass offset, so for isocyanate loss, it would be 0.984 - 43.01 = -42.026 (it's negative because the loss is larger than the original modification mass). 

I would also suggest that you specify deamidation as a variable modification (0.984 on NQ) and then restrict the mass offset 0.984 just to R, as that will link the diagnostic and remainder ions only to citrullination and not deamidation. 

Finally, you will see the modifications in the Assigned Modifications column in the psm.tsv table, not the Delta Mass column, because you have opted to remove delta masses ("Yes, remove delta mass"). 

Best,
Dan

**Comment by liangxiao023** [comment]
> Hi liangxiao,
> 
> It looks like you need a couple of changes to the parameters. The m/z of the immonium ion should be specified as a diagnostic ion, and needs to include the mass of the charging proton since it needs to be m/z rather than mass (so 130.0975 not 129.09). The fragment remainder ion is calculated starting from the mass offset, so for isocyanate loss, it would be 0.984 - 43.01 = -42.026 (it's negative because the loss is larger than the original modification mass). You also need to turn on "Localize mass shift (LOS)."
> 
> I would also suggest that you specify deamidation as a variable modification (0.984 on NQ) and then restrict the mass offset 0.984 just to R, as that will link the diagnostic and remainder ions only to citrullination and not deamidation.
> 
> Finally, you will see the modifications in the Assigned Modifications column in the psm.tsv table, not the Delta Mass column, because you have opted to remove delta masses ("Yes, remove delta mass").
> 
> Best, Dan

Thank you very much, I reset the parameters as you suggested and the results appeared. 

Best,
liangxiao

**Comment by douyue623** [comment]
After search, how to check which peptide including the diagnostic ion in output files?

**Comment by fcyu** [comment]
@douyue623 I think you have posted a new issue here https://github.com/Nesvilab/FragPipe/issues/1651 . Please do not abuse this issue page.

Best,

Fengchao
