### ISSUE TITLE
the protein FDR filter didn't reach the desired threshold, try a higher threshold using the --prot parameter 

### ISSUE THREAD

**Issue by Luc2702** [Nesvilab/FragPipe#1591]
Hello,

I am trying to perform label-free quantification with LFQ-MBR on mzML converted files. I am getting an error regarding FDR threshold.
Would you have any idea how to fix this issue ? I have attached the log report.

Thanks for your help!
[log_2024-05-14_11-54-23 (1).txt](https://github.com/Nesvilab/FragPipe/files/15434369/log_2024-05-14_11-54-23.1.txt)

**Comment by fcyu** [comment]
You have submitted the same issue two times: https://github.com/Nesvilab/FragPipe/issues/1578 and https://github.com/Nesvilab/philosopher/issues/493#event-12924483133. 

I think is is a waste of everyone's time if you submit the same question multiple times. I will close this one and reopen the one you closed on https://github.com/Nesvilab/philosopher/issues/493#event-12924483133 since it is a bug in Philosopher.

Best,

Fengchao

**Comment by Luc2702** [comment]
Sorry about that ... I had closed by accident my previous post and was not sure how to reopen it ...
Thank you for reopening it and once again sorry for the inconvenance.

Best
