### ISSUE TITLE
N-glyco DDA workflow and Skyline export

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#1601]
Hi,

I am trying to analyze view the results of an N-glycopeptide analysis in Skyline (using latest version of Skyline daily). The search results look fine in PDV viewer, and there are glycan modifications populated in the Skyline Peptide settings but there are no glycopeptides in the resulting library.

Regards,

Matt

[log_2024-05-30_14-23-18.zip](https://github.com/Nesvilab/FragPipe/files/15504350/log_2024-05-30_14-23-18.zip)

**Comment by fcyu** [comment]
Maybe Dan knows it better than me since he has played the glyco mode a lot. To make it work when using interact.pep.xml as Skyline input for the glyco mode, you need to
1. Set "report mass shift as a variable mod" to "yes, remove delta mass"
2. Turn off/uncheck "run PTM-Shepherd" in the "PTMs" tab;
3. Turn off/uncheck "assign Glycans with FDR" in the "Glyco" tab.

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/1843f43f-d9b3-4805-bd97-23985aab353b)

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi Matt,

For DDA glyco data, to use Skyline you currently need to do a bit of a workaround by using the "Report mass diff as a variable mod" setting in MSFragger because the pepxml file does not have glycan information (which prevents doing the glycan composition assignment/FDR). For DIA data, you can use the speclib file from DIA-NN which has the glycan mods propagated to it, but the speclib is only generated by DIA-NN. We are working with the Skyline team to support a more streamlined workflow soon. 

Best,
Dan
