### ISSUE TITLE
Fragpipe 22 doesn't generate MSStats csv output file

### ISSUE THREAD

**Issue by bnewt2k** [Nesvilab/FragPipe#1612]
Hi,
Running DIANN w Fragpipe
Fragpipe 22 doesn't generate msstats.csv even though box is checked.
Fragpipe 21.1 did write csv.

Thanks
Bill

[log_2024-06-05_10-05-51.txt](https://github.com/user-attachments/files/15594862/log_2024-06-05_10-05-51.txt)

**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

**Comment by fcyu** [comment]
I think you need to specify the experiment and bioreplicate groups in the workflow tab enable msstats.csv, because MSstats needs the experiment structure.

Best,

Fengchao

**Comment by bnewt2k** [comment]
Hi,
I did that already
Thanks

**Comment by fcyu** [comment]
No, you didn't.

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/09d09d0d-68bd-40e4-8d09-98823a1a69d9)

**Comment by bnewt2k** [comment]
Hi,
I am not sure what to say. I may have not entered it incorrectly.  Here is
the annotation file.

I will try again with more screenshots
Thanks for your help.

Thanks
Bill

**Comment by bnewt2k** [comment]
Hi Fengchao,

Just tried again.  No msstats.csv

[log_2024-06-05_15-02-56.txt](https://github.com/user-attachments/files/15597091/log_2024-06-05_15-02-56.txt)
![FP_22_Workflow](https://github.com/Nesvilab/FragPipe/assets/171856888/7bcf9fde-3484-4045-86e9-21be664fca9e)
![FP_22_QuantDIA](https://github.com/Nesvilab/FragPipe/assets/171856888/24eb2a10-a67a-4f56-8ae0-159fed8b9521)

Thanks,
Billy

**Comment by fcyu** [comment]
Hi Billy,

I think the files are messed up because 
1) Although you specified the experiment and bioreplicate groups, they were not well recorded when running the jobs:
```
LCMS files:
  Experiment/Group: 
  (if "spectral library generation" is enabled, all files will be analyzed together)
  - C:\Champions_10AML_MZML\Ana\20230728_SJMS_Eclipse_FAIMS_Champ_Reg_DIA_Ana_2of20ul_Sample_01.mzML	DIA
  - C:\Champions_10AML_MZML\Ana\20230728_SJMS_Eclipse_FAIMS_Champ_Reg_DIA_Ana_2of20ul_Sample_02.mzML	DIA
  - C:\Champions_10AML_MZML\Ana\20230728_SJMS_Eclipse_FAIMS_Champ_Reg_DIA_Ana_2of20ul_Sample_03.mzML	DIA
  - C:\Champions_10AML_MZML\Ana\20230728_SJMS_Eclipse_FAIMS_Champ_Reg_DIA_Ana_2of20ul_Sample_04.mzML	DIA
  - C:\Champions_10AML_MZML\Ana\20230728_SJMS_Eclipse_FAIMS_Champ_Reg_DIA_Ana_2of20ul_Sample_05.mzML	DIA
  - C:\Champions_10AML_MZML\Ana\20230728_SJMS_Eclipse_FAIMS_Champ_Reg_DIA_Ana_2of20ul_Sample_06.mzML	DIA
```

2) You did not enable the spec lib generation step, but DIA-NN quant still worked. It implies that there are old files (`C:\May7_Test2\Old_Library\library_Hum_Panc_Ecl.tsv`) from the previous job.....
```shell
    Cmd: [START], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [CheckCentroid], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [WorkspaceCleanInit], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [MSFragger], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [MSBooster], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [Percolator], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [ProteinProphet], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [PhilosopherDbAnnotate], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [PhilosopherFilter], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [PhilosopherReport], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [WorkspaceClean], Work dir: [C:\Jun05_frag22_test_simple]
    Cmd: [DIA-NN], Work dir: [C:\Jun05_frag22_test_simple]

...

speclibgen.run-speclibgen=false

...

[0:00] Loading spectral library C:\May7_Test2\Old_Library\library_Hum_Panc_Ecl.tsv
[0:05] Finding proteotypic peptides (assuming that the list of UniProt ids provided for each peptide is complete)
[0:05] Spectral library loaded: 9693 protein isoforms, 9693 protein groups and 205632 precursors in 178396 elution groups.
[0:05] Encoding peptides for spectra and RTs prediction
[0:05] Predicting spectra and IMs
[0:43] Decoding predicted spectra and IMs
[0:46] Saving the library to lib.predicted.speclib
[0:46] Initialising library
...
```

Could you
1. Delete all files related to FragPipe
2. Download FragPipe, and other tools to a new folder (DO NOT put them to a folder having any files).
3. Load the built-in workflow, your LC-MS files
4. Specify your fasta file 
5. Go to the run tab, specify the output folder to a new one, and run

Thanks,

Fengchao

**Comment by bnewt2k** [comment]
Thank You,
Fengchao

I still need guidance on the library usage, and generation or not..?
I can still reuse the old library right? 
(I would rather not rebuild library from 30+ DDA runs); also won't that inhibit the grouping just showed

Or do I have to generate a library from every time I want to export a msstats.csv ?  

I will put the old library into the new folder without any other files.

Thanks
Billy

**Comment by bnewt2k** [comment]
*** Update  ***

Hi All,

So I did get FP_22  to output a msstats.csv file .

I deleted all fragpipe versions and tools I had been using from folders on C drive. ( although I did NOT go into c:\windows\users\Appdata\ etc.. and delete anything) 
I reinstalled FP 22_jre and all tools including python.
I did not reinstall java or C, I thought those should be fine.

[log_2024-06-06_14-12-28.txt](https://github.com/user-attachments/files/15686606/log_2024-06-06_14-12-28.txt)

I did not not use the existing spectral library I had been using.  
I did add experiment and bioreplicate values in workflow tab.
I added 8 DDA files I had used to make that library.
I selected to generate a new library file.
I used a new download of uniprot human reviewed fasta file.

I suspect that the old library caused most problems...
AND / OR that selecting generate new library fixed them.

I will test with new library alone minus DDA files to confirm.  It would be common to use an existing library without building a new one each time.

Thanks all
Billy

**Comment by Jacobluke-** [comment]
Hi Billy, have you tested with DIA files with existing library and minus the DDA files?

I also encounter similar problem.

**Comment by Jacobluke-** [comment]
[log_21.1_no_existing_lib.txt](https://github.com/user-attachments/files/19870032/log_21.1_no_existing_lib.txt)
[log_21.1_with_exisiting_lib.txt](https://github.com/user-attachments/files/19870033/log_21.1_with_exisiting_lib.txt)
[log_22.0_no_existing_lib.txt](https://github.com/user-attachments/files/19870031/log_22.0_no_existing_lib.txt)
[log_22.0_with_exisiting_lib.txt](https://github.com/user-attachments/files/19870030/log_22.0_with_exisiting_lib.txt)

![Image](https://github.com/user-attachments/assets/1a39f9ce-8ba7-4394-9aa7-915e661f0534)
![Image](https://github.com/user-attachments/assets/4d8d6ee8-2c09-4d24-95e6-3b8784517bad)
![Image](https://github.com/user-attachments/assets/0b66db19-ffa9-4f1c-acb4-ddaecbbd32a1)
![Image](https://github.com/user-attachments/assets/4164f0f3-42de-407a-8caa-f72e7a67277c)

Hi @fcyu , thank you for your prompt reply. The attachments are a bit messy, but they are the dry runs logging and the screenshots. 

You can see that for two versions of FragPipe, when existing library is attached, 21.1 still has the command of converting msstats.csv while 22.0 doesn't. 

For the screenshots, the resolution is a bit off but I think the essential elements are visible.

Once again, thank you.

Regards,
Jacob

**Comment by fcyu** [comment]
Hi Jacob,

Thanks for sharing the screenshots. I think the reason is that you are using DIA-NN 2.0+ in the "config" tab. It has a new format of the report that FragPipe hasn't support (FragPipe was released before DIA-NN 2.0). If you change is back to the default version bundled with FragPipe by deleting the DIA-NN path, it should work.

Best,

Fengchao

**Comment by Jacobluke-** [comment]
Hi Fengchao,

I tried changing it back to the bundled version, but the command still didn't appear. Also, I don't think it's a problem for the DIA-NN, because it's currently in Dry Run mode, also, it's FragPipe not putting up the msstats command. (You can see from the second last command, the DIA-NN is the stock version and the command is not showing. It's expected to be 
```
DIA-NN: Convert DIA-NN output to MSstats.csv [Work dir: C:\Users\jacobluke\Desktop\fragpipe_test\diann-output]
java -cp C:\Users\jacobluke\Developer\fragpipe\lib\commons-io-2.15.1.jar;C:\Users\jacobluke\Developer\fragpipe\lib\fragpipe-22.0.jar;C:\Users\jacobluke\Developer\fragpipe\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.diann.DiannToMsstats report.tsv ./ C:\Users\jacobluke\Desktop\fragpipe_test\psm.tsv 0.01 1 0.01 0.01 C:\Users\jacobluke\Desktop\fragpipe_test\fragpipe-files.fp-manifest
```
)

One thing I have in mind is to run the command by myself to ensure the file is properly generated. 

[log_22.0_with_existing_lib_stock_diann.txt](https://github.com/user-attachments/files/19870492/log_22.0_with_existing_lib_stock_diann.txt)

Regards,
Jacob

**Comment by Jacobluke-** [comment]
[log_no_lib.txt](https://github.com/user-attachments/files/19870850/log_no_lib.txt)
[log_with_lib.txt](https://github.com/user-attachments/files/19870849/log_with_lib.txt)

Are these two sufficient?

**Comment by fcyu** [comment]
Thanks for sharing the file. 

I digged into the details and found this https://github.com/Nesvilab/FragPipe/commit/fbd161cc90511806ebdecc20aa3fb56a0b98a494

It looks like I let FragPipe not generate the MSstats file when users provided a library file because there might not be psm.tsv, which is required when generating the MSstats file, available.

BTW, your workflow has MSFragger, MSBooster,....., EasyPQP enabled, but you also provide an existing spectral library, which doesn't make any sense. You should either enable the whole workflow without providing an existing spectral library, or skip all the steps except for DIA-NN and provide a spectral library.

Best,

Fengchao

**Comment by Jacobluke-** [comment]
Thank you for locating the problem. For now, running the command in the powershell is a workaround right?
'''
DIA-NN: Convert DIA-NN output to MSstats.csv [Work dir: C:\Users\jacobluke\Desktop\fragpipe_test\diann-output]
java -cp C:\Users\jacobluke\Developer\fragpipe\lib\commons-io-2.15.1.jar;C:\Users\jacobluke\Developer\fragpipe\lib\fragpipe-22.0.jar;C:\Users\jacobluke\Developer\fragpipe\lib\fragpipe-22.0.jar com.dmtavt.fragpipe.tools.diann.DiannToMsstats report.tsv ./ C:\Users\jacobluke\Desktop\fragpipe_test\psm.tsv 0.01 1 0.01 0.01 C:\Users\jacobluke\Desktop\fragpipe_test\fragpipe-files.fp-manifest
'''

Regards,
Jacob

**Comment by fcyu** [comment]
It may or may not work. Depend on your library and psm.tsv (this is exactly why FragPipe doesn't do it if there is a library as input).

Best,

Fengchao

**Comment by Jacobluke-** [comment]
So I get my library.tsv and psm.tsv during generating the library from DDA files. For my understanding, I should be able to generate msstats.csv after running DIA-NN with existing library supplied.

Would you consider adding supplying psm.tsv as an requirement when ticking the box?

Please don't hesitate to point out any misunderstanding.

Regards,
Zinan

**Comment by fcyu** [comment]
> So I get my library.tsv and psm.tsv during generating the library from DDA files. For my understanding, I should be able to generate msstats.csv after running DIA-NN with existing library supplied.

That's correct.

> Would you consider adding supplying psm.tsv as an requirement when ticking the box?

I am not sure if I fully follow this question. psm.tsv is required when generating the MSstats file.

Best,

Fengchao
