### ISSUE TITLE
Change UI Scaling

### ISSUE THREAD

**Issue by tjlundgren** [Nesvilab/FragPipe#1646]
Hello Fragpipe team!

I have an odd issue. Sometimes Fragpipe will scale the text very small on my screen...
![image](https://github.com/Nesvilab/FragPipe/assets/63795294/89c40799-e647-43b0-a627-697b29bab139)
I have a hard time reproducing it, have only observed it on one specific workstation, and has persisted through at least 2 versions of Fragpipe now.

Would you kindly consider adding the ability to manually scale the UI?

**Comment by fcyu** [comment]
It happens when you are using a 4K monitor. Windows somehow can't figure out the right font size for the UIs. You could change the configuration to resolve this problem.

1. Right click `fragpipe.exe`
2. Click `Properties`
3. Click `Compatibility` tab
4. Click `Change high DPI settings`
5. Check the `Use this setting to fix scaling problems for this program instead of the one in Settings` box
6. Click `OK`, and then `OK` in the `Properties` window.

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/a4891145-74d2-4663-bdf8-c8e569f521e8)

Best,

Fengchao

**Comment by tjlundgren** [comment]
Thank you!
