### ISSUE TITLE
Filelist-Diann generation?

### ISSUE THREAD

**Issue by ako81818** [Nesvilab/FragPipe#1668]
Hello,
Is there a way to configure a workflow to set a specific order of the loaded files when generating the filelist-diann file used by diann to arrange columns in the matrix outputs?  I've tried loading files into the Workflow tab in the desired order, making the file names numerically ordered, adding bioreplicates numbering to the desired order, but in generating the filelist-diann, FragPipe seems to ignore all that. Or is the order that FragPipe arranges intentional - set to result in the most comprehensive quant output perhaps (i've read that the size of the Diann output is dependent on file load order)? 

Separately, is there a max file path and/or file name length to be aware of?

Regards,
Andrew

**Comment by fcyu** [comment]
> is the order that FragPipe arranges intentional - set to result in the most comprehensive quant output perhaps (i've read that the size of the Diann output is dependent on file load order)?

That's correct. The files are sorted by the file size because DIA-NN uses the first one to estimate the mass errors and retention time tolerance window, which would be better to use the largest file.

> Separately, is there a max file path and/or file name length to be aware of?

Windows command line interface has the maximum length limitation. That is why we put the paths in the file list txt file to avoid long command.

Best,

Fengchao
