### ISSUE TITLE
Y ion information for constructing glycoproteomic spectral library

### ISSUE THREAD

**Issue by sqian49** [Nesvilab/FragPipe#1674]
Hello FragPipe team,

Thank you for your work on building this spectacular tool for the whole community.

Currently I am focusing on N-Glycoproteomics and currently I would like to build a spectral library based on our glycopeptide results. I used the "Spec Lib" panel with Glyco mode "N-glyco+HexNAc", however, only b and y ions could be generated. Could you please tell me if there is a way to extract Y (big y) ions information? Thank you for your help.

**Comment by dpolasky** [comment]
Hi,
There is not currently a way to add big Y ions to the spectral library, mostly because none of the tools we use that read the spectral libraries (DIA-NN, Skyline, etc.) currently support these ions. 

But if you are just looking for the intensities of the Y ions from identified spectra, you can use the PTM-Shepherd diagnostic feature extraction module to get them by placing the masses (e.g., 203.079 for pep+HexNAc) in the Peptide remainder fragments box. It generates a diagnosticIons.tsv file that shows the intensity of each provided ion for all PSMs - not a spectral library, but maybe useful depending on what you're trying to do. 

Best,
Dan

**Comment by sqian49** [comment]
Hi Dan,

Thank you so much for your information. I followed your instruction and it worked. There are two small questions following: 1, are the column names started with 'ox' in diagnosticlons.tsv are capital B ions? 2, the intensity values are quite small. Are they log2 scaled?

**Comment by dpolasky** [comment]
Yes, the columns starting with "ox" are B ions for glycans - it means an ion found as [M+H]+ at the m/z listed in the column header. 

And the intensity values are not log2, but rather relative intensity as a percentage of the base peak in the spectrum (so a value of 100 means it is the base peak). For the peptide remainder ions (Y ions), all charge states found are summed together, so it is possible to get a value greater than 100, meaning that the sum of the charge states for this ion was greater than the height of the base peak. 

Best,
Dan

**Comment by sqian49** [comment]
Hi Dan,

Got it. Thank you so much for your explanation. I will leave comments here if I have questions in the future. Thank you and your team members again for building this amazing software.

**Comment by dpolasky** [comment]
You are very welcome!
