### ISSUE TITLE
Paths longer than the Windows limitation broke Percolator

### ISSUE THREAD

**Issue by vincentroyrichard** [Nesvilab/FragPipe#1678]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-07-17_12-55-30.txt](https://github.com/user-attachments/files/16270679/log_2024-07-17_12-55-30.txt)

**- Describe the issue or question:**

Hello,

I am trying to perform precursor based quantitation of some data acquired in DDA-PASEF mode. I am getting the following error saying that the file could not be opened? I thought the raw data file in question may have been corrupted so I've actually reacquired the data and it still happens. Any assistance would be greatly appreciated.

Thanks very much,
Vincent

**Comment by fcyu** [comment]
Hi Vincent,

The error should be because of the maximum command length restriction in windows. Could you move both FragPipe and your data to the folders with shorter name. 

Currently, the path like `D:\Users\VR\FragPipe_searches\2024-0705_SCPC043-03_Darren_Soleimani_LFQ_labelled_mouse_remeasured\EV003657_VR_SCPC043_03_Darren_labeled_mouse_EV1137_40C_30SPD_DDA_PASEF_400ng_HM2_s4_a2_1_4463\EV003657_VR_SCPC043-03_Darren_labeled-mouse_EV1137_40C_30SPD_DDA-PASEF_400ng_HM2_s4-a2_1_4463_percolator_target_psms.tsv` is longer than the default limitation: 256

You could also change the Windows configuration to enable longer path but you need to contact your IT department to do that.

Best,

Fengchao

**Comment by vincentroyrichard** [comment]
Ah okay! I will give this a shot.. Thanks so much for the quick help Fengchao!
