### ISSUE TITLE
Search DIA files with separate libraries

### ISSUE THREAD

**Issue by vindr20** [Nesvilab/FragPipe#1681]
**- Describe the feature:**
For some method optimization experiments, it would be convenient to be able to do library free searches of multiple DIA files by searching each file with it's own generated library (as opposed to creating one library from all of them to search all of them). I remember this used to be possible by designating each file to is own experiment, but that doesn't seem to be the case in the current version.

**Comment by fcyu** [comment]
That's correct. In the very old version of FragPipe, if you assigned the files to experiments, each experiment would have their own spectral library. However, with the recent changes, we made FragPipe always generate a single spectral library because most people configure the experiment groups mostly for the downstream analysis purpose.

For your application, you could run FragPipe with your samples individually.

Best,

Fengchao
