### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Ulianafederico** [Nesvilab/FragPipe#1684]
Hi,
running DIA-NN with MSFragger I have the following error:

java.lang.ArrayIndexOutOfBoundsException: Index 39 out of bounds for length 38
	at com.dmtavt.fragpipe.tools.diann.Propagation.propagate(Propagation.java:169)
	at com.dmtavt.fragpipe.tools.diann.Propagation.main(Propagation.java:69)
Process 'DIA-NN: Propagate information' finished, exit code: 1
Process returned non-zero exit code, stopping
[report.log.txt](https://github.com/user-attachments/files/16321269/report.log.txt)
[log_2024-07-20_15-45-45.txt](https://github.com/user-attachments/files/16321271/log_2024-07-20_15-45-45.txt)

In this case I just loaded a library for DIA-NN, DIA-NN can make the search and write all tables but I don't know if I can trust the results.

Thank you for the help!
Federico

**Comment by fcyu** [comment]
Thanks for the bug report. It was caused by an empty gene in the psm.tsv file. I have fixed it in https://github.com/Nesvilab/FragPipe/commit/f23daa00934ee24db29415ab4a6410bc31b2f65c.

The output files are still trustworthy. Some of the files just don't have the additional `All Mapped Proteins` and `All Mapped Genes` columns. 

Best,

Fengchao

**Comment by Ulianafederico** [comment]
Thank you Fengchao!

Great support!

Federico

________________________________
