### ISSUE TITLE
Question on variable modifications vs offset search

### ISSUE THREAD

**Issue by tretyacv** [Nesvilab/FragPipe#1703]
Hello, I would like to clarify what would be a better way to proceed with the PTM search. In case I have 10 different modifications (some on the same amino acid, some on the different, I expect only one modification per peptide). Would it be better to perform 10 closed searches with different variable modification each and then to merge the search results or to perform one offset search with provided mass shifts? In manual page I read:

"The key difference between mass offset (and open) searches vs closed search is that only one mass offset is allowed per peptide, whereas multiple variable modifications can be searched on a peptide. This prevents combinatorial expansion of the search space and allows searching for many masses (e.g., PTMs) at once."

I interpret this as that the offset search is the way to go in my case. However, closed and offset search differ in validation steps so I wonder what would be a better strategy to maximize the identification number?

**Comment by fcyu** [comment]
Generally, you could set all of those 10 modifications as variable modifications or mass-offsets. If those modifications are not labile and because "only one modification per peptide", setting them as variable modifications seems to be more straightforward and easier to perform downstream analysis. If some of them are labile, you could set them as mass-offset searches and perform a labile search.

Best,

Fengchao

**Comment by tretyacv** [comment]
I see, thank you. So there is no difference from using MSbooster/Percolator in closed search+varmods vs CrystalC/PeptideProphet in offset search?

**Comment by fcyu** [comment]
> I see, thank you. So there is no difference from using MSbooster/Percolator in closed search+varmods vs CrystalC/PeptideProphet in offset search?

These two won't have identical results but very similar in your case.

> Also, do you think that two-pass search as described here https://fragpipe.nesvilab.org/docs/tutorial_two_pass_search.html could improve the offset search detection rate as it did for the searches with the second-pass database of variants?

Yes, it should be for some samples. You could also take a look at the group FDR https://fragpipe.nesvilab.org/docs/tutorial_group_fdr.html that better controls the FDR for variant peptides.

Best,

Fengchao

**Comment by anesvi** [comment]
Just to add a bit to this, since it is a common issue. It is important to control the group specific FDR for less common/rare modifications, especially when there are many of them. We should probably explain this on our help pages better. In short, for open search, we still have PeptideProphet enabled (and not Percolator) and still use Crystal-C  to remove some artifacts.  For a mass offset search with a few mass shifts, it is OK to change to Percolator and Crystal-C is not needed. For large mass offset search, it's a grey zone. I go with PeptideProphet when I want to be more conservative. Furthermore, when doing mass offset search and regardless of whether PeptideProphet or Percolator is used, I  recommend using  --mods option in Philosopher (validation tab) to explicitly filter PSMs to 1% FDR separately for each of the following three group (unmodified peptides, peptides containing common modifications [common = specified after the mods tag], peptides containing any other modification).

**Comment by anesvi** [comment]
I need to add that --mods option to filter unmodified/common/other PTMs separately should also be done for variable modification searches, not just the mass offset searches. Mass offset and variable mods are just different search modes, but FDR control is a separate issue.

**Comment by tretyacv** [comment]
Thank you both! I will go with PeptideProphet and set --mods  in FDR filter since I do search for a rare modifications (ribosomal errors). Also, is there any information on "Iterative Localization of PSMs" from PTMs tab? I could not find any info on that

**Comment by anesvi** [comment]
'Iterative Localization of PSMs' is an experimental option added by a former student Danny Geiszler. We have not tested it yet. I suggest you wait for his paper to come out, or evaluate your results carefully if you decide to try it.

**Comment by tretyacv** [comment]
Ah I understand. And more regarding variable PTM search - as my variable modification is just a rare SAAV (ribosomal error) and thus PTMs are normal peptides, wouldn't it be beneficial to use MSBooster which can predict peptide properties well? I mean is there a way to set in fragpipe that varmod E:-14.0156 means specifically Glu ->Asp and so I would like to search for P**D**PTIDE instead of P**E**PTIDE

**Comment by anesvi** [comment]
Yes, it would probably be beneficial for your analysis. But you are now asking interesting questions that go a bit beyond what this support forum is for, and something that we typically look closer at as collaborations.
