### ISSUE TITLE
IndexError: list index out of range (library could not be built)

### ISSUE THREAD

**Issue by trungttt** [Nesvilab/FragPipe#1711]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-08-06_17-47-14.txt](https://github.com/user-attachments/files/16514255/log_2024-08-06_17-47-14.txt)

**- Describe the issue or question:**
Hi, 
I was running some Immunopeptidomics samples and I couldn´t build a library using EasyPQP. I even tried setting "RT lowess fraction" to 0.05 instead of 0 but still did not work. Could you please help me take a look at this?
Best,
Trung

**Comment by fcyu** [comment]
Hi Trung,

I think it was due to the mixture of the UniProt format and non-UniProt format in the protein headers. I will change the Python script to make it more robust in this case.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Trung,

I just notice that you selected to use `psm.tsv` rather than `pepXML` as input for the spectral library building, which is not our default setting. Could you change it back to `pepXML` for the current versions? It is also much faster than loading from the `psm.tsv`.

![image](https://github.com/user-attachments/assets/6904b95a-7c53-4b75-8c35-29787d4c6ef1)

I have also pushed a new commit to fix it https://github.com/Nesvilab/easypqp/commit/a80f6e5d7d6ffdfac65301ea5ad7b6ec58cdce0e. If you want to try the pre-released version, please uninstall and install EasyPQP using the following commands

```shell
pip uninstall easypqp
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

Best,

Fengchao

**Comment by trungttt** [comment]
Hi Fengchao,

Thank you very much for your super quick response. I appreciate your help. I will try it out right away. Have a great day.
Best,
Trung
