### ISSUE TITLE
Error running Glyco-N-HCD workflow - corrupt files error

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/FragPipe#1736]
[log_2024-08-19_22-48-50.txt](https://github.com/user-attachments/files/16669882/log_2024-08-19_22-48-50.txt)
 Hi,
I'm getting the following error trying to run the set on glyco-N-HCD workflow. If I understand correctly, the claim is that the files are corrupt. I've opened them manually, and they ran well using other software, so I'm not sure where the problem is. the analysis was run on the same computer as the one in issue #1735.

Thanks!
David.

**Comment by fcyu** [comment]
It was due to the Thermo library was not correctly loaded: `2024-08-19 22:48:50 ERROR - Could not find Batmass-IO Thermo binary BatmassIoThermoServer.exe from C:\Users\protolab\Downloads\MSFragger-4.1\ext\thermo, C:\Users\protolab\Downloads\MSFragger-4.1\.\ext\thermo, C:\Users\protolab\Downloads\MSFragger-4.1\..\ext\thermo, C:\Users\protolab\Downloads\MSFragger-4.1\..\..\..\..\ext\thermo, C:\Users\protolab\Downloads\MSFragger-4.1\..\..\..\..\..\ext\thermo`.  

Could you check if the `ext` folder is in one of the folder mentioned above? Most likely, you should put it in the folder where `MSFragger-4.1.jar` is.

Thanks,

Fengchao

**Comment by Dmorgen** [comment]
Hi Fengchao,

The folder indeed lacked the files. I've corrected that and it's working well now.
Thanks!
David.

**Comment by fcyu** [comment]
No problem. I will close this issue but feel free to contact us if you have any questions in the future.

Best,

Fengchao
