### ISSUE TITLE
Bad parameters broke FragPipe

### ISSUE THREAD

**Issue by bingnanzhao** [Nesvilab/FragPipe#1744]
[log_2024-08-22_13-41-59.txt](https://github.com/user-attachments/files/16719063/log_2024-08-22_13-41-59.txt)
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
Hi, I just encountered this issue twice and don't know how to address it. Could you give me any suggestions?

Thanks,
Bingnan

**Comment by fcyu** [comment]
You skipped many steps in FragPipe. 

```shell
Cmd: [START], Work dir: [P:\Projects\BZ_BJA_DualColumnDataProcessing\RetentionTimeShift\Search_results\MSFragger\Zoe250_CM500_HC_DIA_NoFDR]
Cmd: [CheckCentroid], Work dir: [P:\Projects\BZ_BJA_DualColumnDataProcessing\RetentionTimeShift\Search_results\MSFragger\Zoe250_CM500_HC_DIA_NoFDR]
Cmd: [UmpireSe], Work dir: [P:\Projects\BZ_BJA_DualColumnDataProcessing\RetentionTimeShift\Search_results\MSFragger\Zoe250_CM500_HC_DIA_NoFDR]
Cmd: [MSFragger], Work dir: [P:\Projects\BZ_BJA_DualColumnDataProcessing\RetentionTimeShift\Search_results\MSFragger\Zoe250_CM500_HC_DIA_NoFDR]
Cmd: [DIA-NN], Work dir: [P:\Projects\BZ_BJA_DualColumnDataProcessing\RetentionTimeShift\Search_results\MSFragger\Zoe250_CM500_HC_DIA_NoFDR]
```


As a beginner, please load one of the built-in workflows and only make necessary changes such as fixed/variable modifications and enzymes.

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Hi Fengchao, thanks for your quick response. I tried to use both the default and DIA-Umpire-DIA-Speclib-Quant workflow without any other changes, but I encountered this error.:
[log_2024-08-23_21-46-05.txt](https://github.com/user-attachments/files/16735290/log_2024-08-23_21-46-05.txt)

**Comment by fcyu** [comment]
You need to install [Thermo MS File Reader](https://thermo.flexnetoperations.com/control/thmo/login?nextURL=%2Fcontrol%2Fthmo%2Fdownload%3Felement%3D6306677) to let DIA-NN load the raw format files: https://github.com/vdemichev/DiaNN#raw-data-formats

Or, you could convert the raw files to mzML format: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Thanks it works! However I met with a new problem. 
[log_2024-08-24_22-45-41.txt](https://github.com/user-attachments/files/16739147/log_2024-08-24_22-45-41.txt)
I converted .raw file into mzML format and used it as my input.

**Comment by fcyu** [comment]
The program couldn't find the Percolator file. It seems that something was wrong with your computer because your previous log ([log_2024-08-23_21-46-05.txt](https://github.com/user-attachments/files/16735290/log_2024-08-23_21-46-05.txt)) showed that there was no issue finding it.

You probably need to contact your IT department to troubleshoot it locally.

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Thanks and I changed to use the 'DIA_DIA-Umpire_SpecLib_Quant' workflow without any changes, but now I met with this:
[log_2024-08-26_08-10-26.txt](https://github.com/user-attachments/files/16750453/log_2024-08-26_08-10-26.txt)
All the files is stored in this folder which looks like:
![Screenshot (180)](https://github.com/user-attachments/assets/360c3fcc-72c2-406f-a322-0c47521f98d0)
It looks like there misses a file in the output folder.

Thanks,
Bingnan

**Comment by fcyu** [comment]
I don't think you were using the "DIA_DIA-Umpire_SpecLib_Quant" workflow. Did you click the "load" after selecting the workflow?

Thanks,

Fengchao

**Comment by bingnanzhao** [comment]
Yes, because before that I used the defult (which unchecked the DIA-Umpire SE module) to make it faster, but now after I changed to "DIA_DIA-Umpire_SpecLib_Quant" workflow the DIA-Umpire SE module is checked. 

Thanks,
Bingnan

**Comment by fcyu** [comment]
I am sorry for the miscommuncation. I meant the "load workflow" button

![image](https://github.com/user-attachments/assets/1b07bcd1-7509-47e2-abb9-94e12eb47fd3)

The reason of asking this is because the PeptideProphet but not Percolator was enabled, which is not the configuration in  "DIA_DIA-Umpire_SpecLib_Quant". I suggest you load the workflow and start from scratch.

BTW, since you are performing a tryptic search, may I ask why did you use the "DIA_DIA-Umpire_SpecLib_Quant" but not the "DIA_SpecLib_Quant"?

Thanks,

Fengchao

**Comment by bingnanzhao** [comment]
I think it's a good point to use this workflow without any changes. And the reason why I did not use "DIA_SpecLib_Quant" is because I used it before and I met with the problem presented above reporting some issue with percolator, but this workflow doesn't allow me to uncheck percolator or to check peptideprophet option. 

Thanks,
Bingnan

**Comment by fcyu** [comment]
Let me clarify the issues so far.

1. You had issues running PeptideProphet according to your previous log file
2. You should not use PeptideProphet but not Percolator for the "DIA_SpecLib_Quant" or "DIA_DIA-Umpire_SpecLib_Quant" workflows in most cases
3. You had issues running Percolator?
> And the reason why I did not use "DIA_SpecLib_Quant" is because I used it before and I met with the problem presented above reporting some issue with percolator, but this workflow doesn't allow me to uncheck percolator or to check peptideprophet option.

Back to my previous comment, you DID NOT load the "DIA_DIA-Umpire_SpecLib_Quant" workflow successfully, if that was what you wanted, because the parameters in your log files do not match it. If you still want to use the "DIA_DIA-Umpire_SpecLib_Quant" workflow, please click "load workflow" button to load it.

BTW, neither "DIA_SpecLib_Quant" nor "DIA_DIA-Umpire_SpecLib_Quant" doesn't allow you to check PeptideProphet

Best,

Fengchao

**Comment by bingnanzhao** [comment]
Thanks for your suggestions and I am currently running a "DIA_SpecLib_Quant" workflow on my server now. We will see if it would succeed this time! I will update if the percolator failed again. 


By the way, another reason I prefer to use "DIA_DIA-Umpire_SpecLib_Quant" workflow is that it allow me to have pseudo-MS/MS result, which can help me identify if some peptides has been identified twice. However, I looked up the filename_rank1.pepXML result from 'Default' workflow I found this may be the solution to me! But I am not sure if this is all the highest ranking PTMs I need. If you are interested to have a look at the this file I'd like to share with you via email since here does not allow me to post it.

Thanks,
Bingnan

**Comment by bingnanzhao** [comment]
Hi Fengchao,

Thanks for your help and finally I succeeded for DIA_SpecLib_Quant! I met the same problem for percolator again last time, the log is here:
[log_2024-08-26_10-14-20.txt](https://github.com/user-attachments/files/16763464/log_2024-08-26_10-14-20.txt)
I solved this by replacing the percolator 3_6_5 with the latest version: v3_07 and rename some folders after download. 

Thanks,
Bingnan

**Comment by fcyu** [comment]
Glad to hear that the issue was resolved. I will close this issue now but feel free to contact us if you have any questions in the future.

Best,

Fengchao
