### ISSUE TITLE
Missing TMT reporter ion abundances for protein.tsv and peptide.tsv files.

### ISSUE THREAD

**Issue by xiaojingsui** [Nesvilab/FragPipe#1749]
**- Upload your log file**
[log_2024-08-22_19-47-08.txt](https://github.com/user-attachments/files/16744127/log_2024-08-22_19-47-08.txt)

**- Describe the issue or question:**

My question is that for Ub search, information on 'TMT channels, each contains relative reporter ion abundances' is missing for files such as 'protein.tsv', 'peptide.tsv'. The TMT reporter ion abundance information is present in 'psm.tsv', as well as files in 'TMT report folder'.

FYI, for FragPipe v21.0, TMT report ion abundances information is present in files such as 'protein.tsv' or 'peptide.tsv'. Is there any setting I missed for FragPipe v22.0?

Thank you for your time.

Xiaojing

**Comment by fcyu** [comment]
I suggest you use the tables in the "tmt-report" folder because they are normalized and outlier removed.

The intensities in psm.tsv, peptide.tsv, ion.tsv, and potein.tsv are raw intensities without any normalization or other processing. But if you still want to use them, you can change "intensity extraction tool" to "Philosopher":

![image](https://github.com/user-attachments/assets/b3f5e9ea-0b85-4b50-aec8-33426db8edd2)

Best,

Fengchao

**Comment by xiaojingsui** [comment]
OK.  Philosopher works. Thanks.

**Comment by nyin01** [comment]
Hi @fcyu , 

I'm running the TMT10 workflow in headless and would like to set the extraction tool from IonQuant to Philosopher. 

Besides `tmtintegrator.extraction_tool=Philosopher`, are there any other parameters I need to change?

Thanks!
