### ISSUE TITLE
glyco-N-DIA workflow crashing

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#1755]
Hi,

I have successfully run the glyco-N-DIA workflow on these files but now can't get it to run. The DDA files process fine with the glyco-N-LFQ workflow but getting an error when I use the DIA workflow with 3 additional DIA files. Prefer N-terminal semitryptic or semitryptic search if possible. Log is attached.
[log_2024-08-27_20-22-54.txt](https://github.com/user-attachments/files/16771629/log_2024-08-27_20-22-54.txt)

Thanks,

Matt

**Comment by fcyu** [comment]
Hi Matt, 

There are one warning and one error according to your log file.

1. PTM-Shepherd printed a bunch of warnings, such as `Spectra file ID112496_Pool01_MA10140C_6010_031524 not found! PSM ID112496_Pool01_MA10140C_6010_031524.00828.00828.4 ignored!`. I am not sure if it affected the results, but I will let Dan @dpolasky to take a look.
2. The spectral library generation part crashed due to a know bug (https://github.com/Nesvilab/FragPipe/issues/1685#issuecomment-2265609118). We have fixed it in our fork of EasyPQP. If you want to try the pre-released version, please open the command line interface and run the following commands to uninstall and install the EasyPQP. You need to have git installed.

```shell
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi Matt,
I think the issue is from the spectral library generation based on the messages about the spectra files not being found - can you share the file `I:\6010\Astral_glyo\DIA_wetblood\variants\filelist_speclibgen.txt`? There are a bunch of [spectrum file]_temp-psm.tsv files that should generated but apparently aren't there or aren't being found. 

Just FYI, the second run had a separate issue with PTM-Shepherd, but I don't think it would cause this problem. We require the filter/report command on the validation tab to be rerun before rerunning PTM-Shepherd - because PTM-S removes the delta masses in the psm.tsv and assigns them as glycans, rerunning the report regenerates a fresh psm table for PTM-S to use. But in this case it shouldn't affect the spectral library generation. 

Best,
Dan

**Comment by fcyu** [comment]
Hi Dan,

I actually just reproduced this error using a random DIA file. I guess some recent changes broke the program. Let's communicate offline to get it fixed.

Best,

Fengchao

**Comment by dpolasky** [comment]
Okay, I think we have a fix now @mwfoster - if you update easyPQP again (with the same commands Fengchao posted above), it should resolve the issue. 

Best,
Dan

**Comment by mwfoster** [comment]
Confirmed it's working now. Thanks much, Matt
