### ISSUE TITLE
PTM-Sheperd Crash for Variable Citrullination Search

### ISSUE THREAD

**Issue by petersclarke** [Nesvilab/FragPipe#1795]
[log_2024-09-24_19-12-25.zip](https://github.com/user-attachments/files/17123520/log_2024-09-24_19-12-25.zip)

Hello - I'm processing fractionated data for arginine citrullination. No matter the combination of files I try to search, I receive the following error. It could be related to variable/fixed modifications being attributed to the same site. Thanks for any help you can provide!

"Finding spectral data
	Indexing data from 129
Fatal error: In dataset "129" could not find mzData for run 20240920..."

**Comment by fcyu** [comment]
It seems to be a bug. 

My guess is that the `_calibrated` prefix in the file name broke the logic of locating the files because the `_calibrated` is a key word to mark a calibrated mzML file. Maybe PTM-Shepherd didn't expect the `_calibrated_calibrated` prefix after generating the calibrated mzML file.

Best,

Fengchao

**Comment by dpolasky** [comment]
Based on the run settings, I think you should not run PTM-Shepherd at all because there are no mass offsets in the search (so it will not do anything), and disabling it will avoid the crash. Though I think Fengchao is right about the source of the crash being the "_calibrated" in the raw file name, and we will still fix that for the next version.

Also it looks like you set the fragment mass tolerance to 0.3 Da, but (at least some of) the MS2 scans are high resolution so high res settings were used for the search. However, deisotoping was disabled automatically because of the low res initial setting, so fixing that setting should improve the results. 

Best,
Dan

**Comment by dpolasky** [comment]
Fixed in d5edb47

**Comment by petersclarke** [comment]
Great, thanks for the quick help. Clearing up those issues solved it for me.
