### ISSUE TITLE
Fragpioe not creating Skyline file for glyco-DIA workflow

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#1819]
Hi,

I am trying to process parallel DDA/DIA files through FragPipe using the glyco-DIA workflow. It is generating a DIA-NN output but not a Skyline document.

Thanks,

Matt

[log_2024-10-10_10-24-06.txt](https://github.com/user-attachments/files/17330199/log_2024-10-10_10-24-06.txt)

**Comment by fcyu** [comment]
Hi Matt, 

It is a known bug https://github.com/Nesvilab/FragPipe/issues/1684 and has been fixed in the pre-released version. Let me know me you want to try that version.

We are also working with the Skyline team to make the whole process more robust and smooth, especially for the Glyco workflows. I guess you might want to wait for a little bit until we have a better version.

Best,

Fengchao

**Comment by mwfoster** [comment]
OK thanks.. Regards, Matt

**Comment by fcyu** [comment]
Hi Matt,

We have overhauled the Skyline module in FragPipe with the help of the Skyline team. Could you try the pre-released version frm [https://www.dropbox.com/t/wx0xvqGE2MO3zbAz](https://www.dropbox.com/l/AABSkUzGmELRMqJrrof7u4A2BVCDfxMfTFA)? 

If you see any weird errors from MSFragger, it might be due to the incompatibility of some libraries. Then, I need to send you the the pre-released MSFragger. Just send an email to `yufeATumich.edu` (replace `AT` with `@`).

Thanks,

Fengchao

**Comment by mwfoster** [comment]
Thanks it did generate a Skyline file that might take some time to manually curate but not unexpected. Can try to summarize and post here, but might be easiest to provide the input/output over Box. Let me know what you prefer. Regards, Matt

**Comment by fcyu** [comment]
Sure. Here is the link to upload the files https://www.dropbox.com/request/oxwyJ7PLxFt0hTipAXIa

Could you elaborate more about "might take some time to manually curate but not unexpected"? The fragpipe.sky file generated by FragPipe should be ready to open and visualize using Skyline.

Best,

Fengchao

**Comment by mwfoster** [comment]
Could be something with my local SkylineDaily but, for example, most peptides have red X (not matching library), but it does suggest correct match after re-integration.
[Skyline_screenshots.pptx](https://github.com/user-attachments/files/17558226/Skyline_screenshots.pptx)
