### ISSUE TITLE
[question]: Docker image or Dockerfile for MSFragger

### ISSUE THREAD

**Issue by tamuanand** [Nesvilab/FragPipe#1888]
Hi

I had a question: Is there a docker image available for this or some Dockerfile guidelines. The nearest I could find was this - https://fragpipe.nesvilab.org/docs/tutorial_docker.html and this - https://github.com/nkbaim/MSFragger-docker

I also saw this - https://github.com/Nesvilab/FragPipe/issues/1600#issuecomment-2176919961
- I have MSFragger license

Thanks in advance.

**Comment by fcyu** [comment]
First of all, I have no idea what the https://github.com/nkbaim/MSFragger-docker is about. Looks like someone created an Dockerfile with a very old version of MSFragger.

Please follow the instruction in https://fragpipe.nesvilab.org/docs/tutorial_docker.html to get the FragPipe Docker image running. Then, download MSFragger, IonQuant, and diaTracer by yourself due to the license restriction.

Best,

Fengchao

**Comment by tamuanand** [comment]
Hi Fengchao,

Thanks a lot. My main aim is to run MSFragger using docker on linux cli. Is it possible to have only MSFragger in docker? 

If I were to follow this, what's the recommended path inside the container to download/install MSFragger.

> Please follow the instruction in https://fragpipe.nesvilab.org/docs/tutorial_docker.html to get the FragPipe Docker image running. Then, download MSFragger, IonQuant, and diaTracer by yourself due to the license restriction.

**Comment by fcyu** [comment]
> My main aim is to run MSFragger using docker on linux cli. Is it possible to have only MSFragger in docker?

If you just want to run MSFragger but not FragPipe, there is actually no need to use Docker, which is cumbersome and slow down the IOs. MSFragger is just a Jar file and an `ext` folder. A single command can run it.

If you really want to have the MSFragger Docker, you could create and use it by yourself, but you can't redistribute it due to the license restrictions.

> If I were to follow this, what's the recommended path inside the container to download/install MSFragger.

You could put the MSFragger anywhere in the container as long as you give the correct path to FragPipe.

Best,

Fengchao

**Comment by tamuanand** [comment]
Thanks a lot
