### ISSUE TITLE
Assinged modification were not displayed in psm.tsv under offset search

### ISSUE THREAD

**Issue by Bin-cc** [Nesvilab/FragPipe#1917]
Hi, I followed the tutorial of [offset search](https://fragpipe.nesvilab.org/docs/tutorial_offset.html) to complete my work with a custom modification of +640.223. However, the output file, psm.tsv, didn't display such modification even though it could be observed in .pepXML.

I also noticed that no intensity information were reported in both protein.tsv and psm.tsv. One of MS raw data even could not identify any proteins and peptides, but it could identify some proteins if I used LFQ-MBR workflow.

What should I do to fix these issues?

Here are the log file and parameter file:
log file: [log_2024-12-05_17-58-25.txt](https://github.com/user-attachments/files/18021433/log_2024-12-05_17-58-25.txt)
parameter file: [fragger.txt](https://github.com/user-attachments/files/18021453/fragger.txt)

All the best,
Bin

**Comment by dpolasky** [comment]
Hi Bin,

The pepXML file is not FDR filtered, while the psm.tsv is - most likely the PSM(s) with your modification did not pass FDR control. When one of the raw MS files does not have any results, it usually means something went wrong with that sample or acquisition. You will need to troubleshoot your sample/data acquisition, as it does not appear to be an issue with the software. 

There is no intensity information in the mass offset search because LFQ was not run, according to your log. To use LFQ with a mass offset search requires setting "Report mass diff as a variable mod" to "Yes, remove delta mass" on the MSFragger tab in addition to enabling IonQuant on the Quant (MS1) tab. You can look at the "LFQ-MBR" workflow for an example of how to set the parameters for quantification. 

Best,
Dan

**Comment by Bin-cc** [comment]
Hi dpolasky,

Thanks for your quick and kindly respond. According to your suggestions, it did work for the intensity problem.

I am still confused about the result of mass offset search for no proteins and peptides being reported in one of MS raw files. These two files also underwent "LFQ-MBR" workflow with some specified amino acid modifications instead of all amino acid. Under such condision, both files could identify peptides and some of them have custom modification (+640.223).

Besides PTMs, are there any differences between "LFQ-MBR" and "Mass-Offset-CommonPTMs" workflow during spectrum matching validation or something else?

Best regards,
Bin

**Comment by dpolasky** [comment]
Hi Bin,

There are several differences between the workflows which could make a difference, like using MSBooster to rescore with deep learning in the LFQ-MBR workflow. Also the modifications will be reported in the Delta Mass column of the psm.tsv in the offsets workflow instead of the Assigned Modifications column as they are in the LFQ-MBR workflow. 

But maybe more importantly, there is a big difference between considering modifications on only a few specified amino acids vs on all amino acids. The latter results in a much bigger search space, which means a higher score is required to report a PSM at a given FDR threshold, which could cause no PSMs to be reported for the one file. You can restrict the modification to just a few amino acids in the mass offset search, to be similar to the search space of the LFQ-MBR search (instructions are on the tutorial page). 

Best,
Dan

**Comment by Bin-cc** [comment]
Hi Dan,

Thanks a lot for your patience. I reduced the search space of mass offset search, focusing on some amino acids, and got proteins from both files.

All the best,
Bin

**Comment by dpolasky** [comment]
Great, glad to hear you got it working. I will close this issue now, but feel free to contact us if you have any questions in the future.

Best,
Dan
