### ISSUE TITLE
Can't repeat the results of the previous search. Error with cache?

### ISSUE THREAD

**Issue by huongtran182** [Nesvilab/FragPipe#1929]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
[log_2024-12-09_15-47-05.txt](https://github.com/user-attachments/files/18086276/log_2024-12-09_15-47-05.txt)
[log_2024-12-10_13-52-49.txt](https://github.com/user-attachments/files/18086305/log_2024-12-10_13-52-49.txt)

I was searching my Timstof data (.d)  yesterday (Dec 9) and get the peptide results file with many peptides (473kB). But today (Dec 10) I performed exactly the same search (same workflow, database, MSFragger parameters, Validation), but my peptide file is empty (1 kB). Not sure why. I attached the 2 log files for your reference. The Dec 10 file at the beginning saying that 15:45:30 ERROR: Error saving ui cache. It won't affect the results. 15:45:30 ERROR: Error saving runtime cache. It won't affect the results. Not sure if this is the issue, since it said it won't affect the results.

Thank you for your help!

**Comment by fcyu** [comment]
Your fasta files are different.

Best,

Fengchao

**Comment by huongtran182** [comment]
Hi! The fasta files are the same. One is the decoy file which is after I upload the database on Fragpipe and add decoy. I tried to upload the original database fasta and click add decoy as well, but still didn't work. The search was fast, only 1.3 min and it said all job done, but the peptide file is still empty...

**Comment by fcyu** [comment]
I am pretty sure that the fasta file are different because the [log_2024-12-09_15-47-05.txt](https://github.com/user-attachments/files/18086276/log_2024-12-09_15-47-05.txt) one (the one gives more IDs) doesn't have decoys, which explained why you got much more (false) IDs.
<img width="1853" alt="image" src="https://github.com/user-attachments/assets/acc410d7-c9de-4ab4-8699-7ef63b982b4a">
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/fd5fdba6-abb4-4766-a760-30d057ad58c8">

Best,

Fengchao

**Comment by huongtran182** [comment]
Oh wow I see now. Now I can repeat the search result. Add decoy after uploading the database is necessary right, to get a more "true" IDs?

**Comment by fcyu** [comment]
Yes, the database must contain decoys to perform the FDR estimation and filtering.

Best,

Fengchao
