### ISSUE TITLE
No combind_protein file

### ISSUE THREAD

**Issue by MariaStensland** [Nesvilab/FragPipe#1932]
Hi,
We are running MSfragger with dia-files and are interested in peptide intensities in individual samples. As result output we now get
 the diaNN folder and no combind_protein and combind_peptide files as in the DDA search. Is it possible in MS fragger dia search to get a similar output file as the combind_peptide file, with separated columns with intensities for each sample and merged charge states? How do we do that? I attach a log file from our search. Thanks! /Maria

[log_2024-11-13_17-28-15.txt](https://github.com/user-attachments/files/18091555/log_2024-11-13_17-28-15.txt)

**Comment by fcyu** [comment]
Hi Maria,

No, there are no `combined_*.tsv` tables from the MSFragger-DIA search. But we will add in the future.

Best,

Fengchao

**Comment by a-indra** [comment]
Hi Fengchao,
To clarify:
If one is using DIA workflow (Specifically I'm using DIA_SpecLib_Quant), is there any way to combine fractions? In my case, I have two .mzML per LC-MS run, due to using FAIMS with two CVs. Example below:


Path | Experiment | Bioreplicate | Data type
-- | -- | -- | --
/…/File1_-45.mzML |   |   | DIA
/…/File1_-65.mzML |   |   | DIA
/…/File2_-45.mzML |   |   | DIA
/…/File2_-65.mzML |   |   | DIA
/…/File3_-45.mzML |   |   | DIA
/…/File3_-65.mzML |   |   | DIA


I have tried various combinations of labelling the these such as:


Path | Experiment | Bioreplicate | Data type
-- | -- | -- | --
/…/File1_-45.mzML | 1 |   | DIA
/…/File1_-65.mzML | 1 |   | DIA
/…/File2_-45.mzML | 2 |   | DIA
/…/File2_-65.mzML | 2 |   | DIA
/…/File3_-45.mzML | 3 |   | DIA
/…/File3_-65.mzML | 3 |   | DIA

and

Path | Experiment | Bioreplicate | Data type
-- | -- | -- | --
/…/File1_-45.mzML |   | 1  | DIA
/…/File1_-65.mzML |   | 1  | DIA
/…/File2_-45.mzML |   | 2  | DIA
/…/File2_-65.mzML |   | 2  | DIA
/…/File3_-45.mzML |   |  3 | DIA
/…/File3_-65.mzML |  |  3 | DIA

and combinations of the above.

However, the DIA-NN and protein.tsv output files still seem to treat them as separate samples. In particular I tend to use the pg_matrix.tsv file from DIA-NN and it would be great to combine the CVs so there are only 3 columns rather than 6. Is this possible?

Thank you!

**Comment by fcyu** [comment]
No, it is not supported currently.

Best,

Fengchao
