### ISSUE TITLE
DIA data aquired from Astral is always failed

### ISSUE THREAD

**Issue by zoe1985** [Nesvilab/FragPipe#1934]
Dears, 

I'm not sure the issue about quantification on DIA data from Astral. My experiment derived from lipms. Firstly, trypsin-digest protein quantification is fine, but PK-diget peptide quantification is alwasys stopped. This DIN-NN template runs very fine with other orbitrap-derived data whether lipms or normal.
To reduced possible storage problem, I tried new different computers or numbers of files, but still failed. 
Here is log. If any needs, pls tell me.
Thanks

Rui
[log_2024-12-11_19-39-39.txt](https://github.com/user-attachments/files/18104258/log_2024-12-11_19-39-39.txt)

**Comment by fcyu** [comment]
Hi Rui,

It was due to not enough memory. There are 23 GB memory available according to your log file, which might not be enough for the Astral data. We have improved the memory footprint recently. Send an email to `yufeATumich.edu` (replace `AT` with `@`) if you want to try the pre-released version.

Best,

Fengchao

**Comment by zoe1985** [comment]
Thanks so much!
