### ISSUE TITLE
Process 'PhilosopherFilter' finished, exit code: 2 Process returned non-zero exit code, stopping

### ISSUE THREAD

**Issue by talithar-star** [Nesvilab/FragPipe#1937]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-12-12_10-55-29.txt](https://github.com/user-attachments/files/18116252/log_2024-12-12_10-55-29.txt)

**- Describe the issue or question:**
Non-zero exit code

**Comment by dpolasky** [comment]
Hi,
It looks like you're running a database with just one protein, so you need to disable protein inference and protein-level FDR (the error is because the protein FDR filter couldn't could not reach the desired 1% with only one protein). You can uncheck the Run ProteinProphet button on the validation tab. 

Best,
Dan
