### ISSUE TITLE
issue 229 return in philosopher 3.3.11

### ISSUE THREAD

**Issue by merbllab** [Nesvilab/FragPipe#248]
Hi , I just have the same problem described in issue 229 with Philosopher version 3.3.11. the IonQuant stop working on an error. the protein.tsv contains a protein with zero intensity in all samples and that cause the IonQuant to quit.

2020-10-07 14:36:28 [ERROR] - Protein sp|O75448|MED24_HUMAN from D:\PXD003790-fragpipe_test\analysis_2\PXD003790-fragpipe_test/protein.tsv cannot be found from any psm.tsv.
Process 'IonQuant' finished, exit code: 1
[log_2020-10-07_14-43-47.txt](https://github.com/Nesvilab/FragPipe/files/5346889/log_2020-10-07_14-43-47.txt)

**Comment by fcyu** [comment]
Hi @merbllab ,

Sorry for the trouble. I thought this bug was fixed in Philosopher. I will check with Felip.

Hi @prvst ,

Could you take a look when you have time? I think these it is related to these two issues:
https://github.com/Nesvilab/FragPipe/issues/229#issuecomment-705435780
https://github.com/Nesvilab/Project-Management/issues/209

Thanks,

Fengchao

**Comment by prvst** [comment]
@merbllab Can you share your database file?

**Comment by anesvi** [comment]
Fengchao, what happens now? IonQuant crashes? Since this philosopher bug keep re-occurring, should we just ignore those peptides in IonQuant? But yes, need to fix in philosopher. I also thought it was fixed

**Comment by fcyu** [comment]
IonQuant has already ignored some non-critical errors, such as
```
2020-10-07 14:36:28 [WARNING] - Ion GEASRLAHY@3 was assigned to different razor proteins: sp|Q6DN03|H2B2C_HUMAN and sp|O60814|H2B1K_HUMAN. Skip this in MSstats.tsv.
2020-10-07 14:36:28 [WARNING] - Ion GIM[15.9949]KKAYEL@3 was assigned to different razor proteins: sp|Q14814|MEF2D_HUMAN and sp|P11831|SRF_HUMAN. Skip this in MSstats.tsv.
```

But this one 
```
2020-10-07 14:36:28 [ERROR] - Protein sp|O75448|MED24_HUMAN from D:\PXD003790-fragpipe_test\analysis_2\PXD003790-fragpipe_test/protein.tsv cannot be found from any psm.tsv.
```
will cause other errors in calculating protein intensities and other stuff. So, IonQuant has to stop.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @merbllab 

Could you please share your files with us, including mzml, fasta, parameters, logs, and tsv files? I can give you a link to upload if it is appropriate.

Thanks,

Fengchao

**Comment by merbllab** [comment]
Hi 
Yes!! I can share all the relevant files. 
I will arrange it share through google drive. 
Assaf 


נשלח מה-iPhone שלי

**Comment by merbllab** [comment]
Hi Fengchao ,

 

Please let me know if you received the link for the files.

Regards

Assaf

**Comment by fcyu** [comment]
Hi Assaf,

No, I didn't. Did you send them to my email (yufe@umich.edu)?

Best,

Fengchao

**Comment by merbllab** [comment]
I reshared it with your email

**Comment by fcyu** [comment]
Hi Assaf,

I received files. Will investigate them and get back to you soon.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Assaf,

After looking into your files, we found that it is because the protein FDR threshold is 1 in filtering (which is the default setting in nonspecific search). We have "muted" the error in IonQuant and now everything should work well. 

Please find a fixed FragPipe from [https://umich.box.com/s/6u6mm070133bs6onkyxh3ay4vwhluwvn](https://umich.box.com/s/6u6mm070133bs6onkyxh3ay4vwhluwvn)

Please feel free to contact us if there is any further question.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Assaf,

Could you please also share your fasta with us?

Thanks,

Fengchao
