### ISSUE TITLE
IonQuant for novel PTMs

### ISSUE THREAD

**Issue by pieeye75** [Nesvilab/FragPipe#256]
First off, thanks for making such great software freely available!

We are using FragPipe to search for novel PTMs and we want to quant those using IonQuant. From my searches so far, it appears to me that I need to do an Open search and then pick which PTMs I want to quant and specifically list those as variable PTMs in MSFragger in order to get quant values. Is this correct, or am I doing something wrong? The only modified peptides I get quant values on are those that were first specified in MSFragger as fixed/variable. This was using FragPipe V14. I’ve just read through your latest MCP paper (MSFragger/IonQuant) and checked the settings and the supplementary info.

Thanks,
Peter

**Comment by fcyu** [comment]
Hi Peter,

Thanks for your interest in our tools. Your approach is correct in general. However, there are some alternatives:

1. You can select 'yes' for 'Report mass shift as a variable mod' in MSFragger tab. With this setting, the mass shifts will be reported as variable modifications so that IonQuant can catch them. But there is an issue in open search: the mass shifts are not theoretical masses, which will inflate the ion numbers with different observed masses.
2. You can use mass offset search (loading the 'common-mass-offsets' workflow and adjust 'Mass Offsets' according to your data) coupled with 'Report mass shift as a variable mod'. In this way, the above issue will gone because we know the theoretical value of the mass shifts.

Hopefully my explanation is clear enough.

Best,

Fengchao

**Comment by pieeye75** [comment]
Thanks for the advice, I'll give that a go.
