### ISSUE TITLE
Open searches -> combined.peptide file missing observed mods

### ISSUE THREAD

**Issue by kabalak** [Nesvilab/FragPipe#273]
Hi,

we are performing open searches on QE data from mouse and I feel that something is missing in FragPipe: if I label several experiments, then I get a nice peptide.tsv in each experiments' directory featuring the Assigned & Observed Modifications for each peptide.

But the global combined.peptide file for the whole search does **not** feature this information which is very annoying, as we want to survey the differences in putative modifications among the different experiments with several replicates...
In the combined.peptide file we just have the assigned modifications but not the observed modifications; somehow this feels like a missing point.

Thanks for the great work,
Fatih

**Comment by prvst** [comment]
@kabalak, I'm sorry that you are feeling annoyed. I do not include the observed modifications to the combined peptide table because it would probably be impractical to consume the column's information. On open-search reports from single experiments, we often see peptides containing dozens of possible mapped modifications. If we pull that information from multiple experiments into one table, there would be so much text in that column that your spreadsheet viewer would most likely break. You can still find that information in the individual reports though.
