### ISSUE TITLE
DIA-Umpire SE spectral library + DIANN

### ISSUE THREAD

**Issue by ekvall93** [Nesvilab/FragPipe#319]
Hi,

I have a question using DIA-Umpire SE spectral library.tsv for relative quantification between two experimental groups. When using:

diann --lib library.tsv --f A_r1.mzML -f A_r2.mzML -f B_r1.mzML -f B_r2.mzML ...

DIAnn manages to run. However, the following columns become NaN:

"Protein.Names", "Genes", "Genes.Quantity", "Genes.Normalised", "Genes.MaxLFQ", "Genes.MaxLFQ.Unique".

So I suspect something is wrong. I'm not sure if this is one of the Fragpipe-part or on the DIAnn-part. 

Are you aware of this problem?

One last note, I'm not specifying experimental group and replicate groups in Fragpipe to attain one spectral library instead of one for each replicate.

Best regards,

Markus Ekvall

**Comment by anesvi** [comment]
You need to check Protein Inference: Off

Here are the steps in DIA-NN:


1.      Load library.tsv from FragPipe

2.      Chose where to save the report

3.      Select Protein Inference: Off.

This is because we already did protein inference as part of spectral lib building. With this option, you also do not need to load fasta file in DIA-NN.

4.      I recommend Quantification strategy: Robust LC (high accuracy)

5.      Check ‘Quantities matrices’ box (if not by default), that will give a matrix (protein x sample) output


Best
Alexey

**Comment by ekvall93** [comment]
Great, than you so much
