### ISSUE TITLE
Create a tutorial dataset

### ISSUE THREAD

**Issue by chhh** [Nesvilab/FragPipe#35]
- [ ] a fasta file
- [ ] two mzml files
- [ ] one fragger params file for closed search and one for open search
- [ ] maybe correct parameters for Prophets and Reports? Hopefully the current defaults in the GUI are good enough for that
- [ ] instructions on what to do

This also needs to be hosted somewhere and the link should be included in the Fragger manual.

This is the same as #14

**Comment by chhh** [comment]
Same as #14

**Comment by tomthun** [comment]
Looking forward for the tutorial! 👍

**Comment by tomthun** [comment]
A short explanation of the result tables would also be appreciated!

**Comment by jspaezp** [comment]
(Feature request?)

I would also be nice .. in these regards:

>     * [ ]  one fragger params file for closed search and one for open search
> 
>     * [ ]  maybe correct parameters for Prophets and Reports? Hopefully the current defaults in the GUI are good enough for that

Maybe adding as well annotations on how to change the params file when using high-high res data and high-low, comet has something similar that could be used as a template http://comet-ms.sourceforge.net/parameters/parameters_201901/.

Also some additional info on the parameters for the Prophets would be nice, in particular some  stuff like specifying on what ms-level some things are done (ie: `--accmass`, `--ppm`), although that might be something for philosopher rather than fragpipe ...

**Comment by fcyu** [comment]
@jspaezp 

Following are three parameter templates for closed, open, and non-specific search, respectively:
[https://github.com/Nesvilab/MSFragger/tree/master/parameter_files](https://github.com/Nesvilab/MSFragger/tree/master/parameter_files)

Following script has the parameters/command for Prophets and Reports:
[https://msfragger.nesvilab.org/tutorial_linux.html](https://msfragger.nesvilab.org/tutorial_linux.html)

For open search, we strongly sugress using high-high res data. For closed search, you may use high-low res data with fragment tolerance equals roughly 300 PPM or 1.5 Da.

Best,

Fengchao
