### ISSUE TITLE
java heap space error for non-specific search

### ISSUE THREAD

**Issue by BhaveshMS** [Nesvilab/FragPipe#361]
Hello,

I'm using fragpipe with timstof pro data for a nonspecific peptidome search.
Even with one file I seem to get the java heap space error that has been reported here before.
I have tried to split the database into 50, no success.

The java heap space is set to -Xmx40g and fragpipe ram is set to 60gb (available on system 63gb) but it still doesn't seem to work.
The fragpipe was re-installed only last week so I presume it's the latest version but somehow splitting database doesn't work..
Is there a way to solve this error?

**Comment by fcyu** [comment]
Can you send us your log file?

Thanks,

Fengchao

**Comment by BhaveshMS** [comment]
[log_2021-04-26_10-12-29.txt](https://github.com/Nesvilab/FragPipe/files/6375729/log_2021-04-26_10-12-29.txt)

Thanks for the prompt reply Fengchao! Here is the log file.

**Comment by fcyu** [comment]
First of all, your variable modification setting is not correct (see the bold ones):

variable_mod_01 = 15.994900 M 3
variable_mod_02 = 42.010600 [^ 1
variable_mod_04 = -17.026500 nQnC 1
variable_mod_05 = -18.010600 nE 1
variable_mod_10 = 57.021460 **C (cysteine)** 2
variable_mod_11 = 0.984000 NQ 2
variable_mod_12 = -0.984000 **c*** 1

Second, setting so many variable modifications in non-specific peptidome search would need **huge** memory, with 62 GB memory (your log shows `-Xmx62G`), I don't think 99 split is enough. We will increase the maximum limit in the next release.

Third, with so many variable modifications in non-specific peptidome search, your sensitivity would be low and there might be a lot if false positives. I suggest you remove unnecessary ones. At least `0.984000 NQ 2` and `-0.984000 **c*** 1` can be removed because 50 ppm with `0/1/2/3` isotope errors will cover them.

Best,

Fengchao

**Comment by anesvi** [comment]
Yes, please remove variable_mod_11 = 0.984000 NQ 2

I suggest you start with our default “Nonspecific-peptidome” workflow first
