### ISSUE TITLE
IonQuant Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by jinyi12** [Nesvilab/FragPipe#435]
[log_2021-08-21_22-23-03.txt.zip](https://github.com/Nesvilab/FragPipe/files/7026422/log_2021-08-21_22-23-03.txt.zip)
- Describe the issue or question:
I am new to proteomics, and am trying to run a closed search workflow with quantification on a toy data sent by my lab mates. I have occurred the error during the IonQuant stage, I am not sure what is the issue and appreciate it if help is given.

I have attached my log file here.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2021-08-21_22-23-03.txt.zip](https://github.com/Nesvilab/FragPipe/files/7026423/log_2021-08-21_22-23-03.txt.zip)

**Comment by fcyu** [comment]
Can you send me your mzML file? I can give you a link to upload the data if you need.

Thanks,

Fengchao

**Comment by jinyi12** [comment]
@fcyu Sure. Thanks for the prompt reply! Can you give me the link as the mzML file is 13gb in size.

Best,
Jin Yi

**Comment by fcyu** [comment]
Thanks. Here it is https://www.dropbox.com/request/yLFXH6B23Po3wHNzaOCo

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Jin Yi,

Your file is well received. Followings are the reasons of the error.
1. Your mzML file was converted from .d (ddaPASEF) with msconvert.
2. mzconvert used the tag with ID `MS:1002816` to store the ion mobility array, but it seems to be changed to `MS:1003006` recently according to your mzML. That is why our tools cannot read the file (we are still looking for `MS:1002816`).

Following are those two tags' explanations from the schema in case you are interested in.
```
[Term]
id: MS:1002816
name: mean ion mobility array
def: "Array of population mean ion mobility values (K or K0) based on ion separation in gaseous phase due to different ion mobilities under an electric field based on ion size, m/z and shape, corresponding to a spectrum of individual peaks encoded with an m/z array." [PSI:MS]
xref: value-type:xsd\:float "The allowed value-type for this CV term."
is_a: MS:1002893 ! ion mobility array
relationship: has_units UO:0000028 ! millisecond
relationship: has_units UO:0000010 ! second
relationship: has_value_type xsd\:float ! The allowed value-type for this CV term

[Term]
id: MS:1003006
name: mean inverse reduced ion mobility array
def: "Array of population mean ion mobility values based on ion separation in gaseous phase due to different ion mobilities under an electric field based on ion size, m/z and shape, normalized for the local conditions and reported in volt-second per square centimeter, corresponding to a spectrum of individual peaks encoded with an m/z array." [PSI:MS]
xref: value-type:xsd\:float "The allowed value-type for this CV term."
is_a: MS:1002893 ! ion mobility array
relationship: has_units MS:1002814 ! volt-second per square centimeter
relationship: has_value_type xsd\:float ! The allowed value-type for this CV term
```

We need to investigate the difference of those two tags and change our tools accordingly.

However, **we recommend you directly use the raw folder ending with `.d` for our tools** because it is easier to use and has better results compared to mzML according to our test.

Best,

Fengchao

**Comment by jinyi12** [comment]
Hi Fengchao,

Thank you very much for the help, explanation and suggestions. 
I'll get the raw file from my lab members and run the tools again.

Thanks again for the help.

Best,
Jin Yi
