### ISSUE TITLE
Format Output in the same way as Maxquant possible?

### ISSUE THREAD

**Issue by Peer2011** [Nesvilab/FragPipe#446]
Dear Alexey and Fengchao, 

Is it possible to create output files that look similar to MaxQuant output files? We would like to test IcER R package to reduce missing data in our datasets. However, this porgram currently accepts only files in MaxQuant Output format. 

Best regards, 
Peer

**Comment by giorgiolivi** [comment]
Dear All, maybe here some good news:

Dear All,
I was recently in contact with IceR's group.

Here the link for the new IceR (R package)  
https://github.com/mathiaskalxdorf/IceR/tree/develop

I was wondering if fragpipe outcome (result file) could be similar to MaxQuant in order to run IceR.

Any chanse for fragpipe to accomodate this request? 

Or any Idea to know/or sort fragpipe's files for lauch IceR search?

Thanks in advance, 
Kind Regards,
Giorgio

**Comment by fcyu** [comment]
We have psm.tsv, peptide.tsv, ion.tsv, and protein.tsv in each experiment folder. We also have combined_peptide.tsv and combined_protein.tsv with all experiments. 

If you want to add FragPipe support in IceR, please go ahead. But I don't think we can help much because we never used IceR. If you think IceR is significantly better than FragPipe (especially IonQuant with MBR), could you please provide some data for us to take a look?

Thanks,

Fengchao
