### ISSUE TITLE
Write `native_id` to the mzML file from DIA-Umpire

### ISSUE THREAD

**Issue by asepsiswu** [Nesvilab/FragPipe#497]
the same question is in skyline.ms forum. 
https://skyline.ms/announcements/home/support/thread.view?rowId=51433

As the author stated "The gist was that BiblioSpec doesn't currently work with FragPipe DiaUmpire because their mzMLs use the wrong nativeID for their pepXMLs. I'm looking into adding a hack so if the nativeID lookup fails for "index=N".

Is there a workaround to sovle this? such as replacing index or scan in the mzML file.

**Comment by fcyu** [comment]
Thank you for the message. I replied the thread in the Skyline forum.

Best,

Fengchao

**Comment by asepsiswu** [comment]
> The mzML from DIA-Umpire does not have any native_id attribute. Then, MSFragger writes the index=N, where N = scan number - 1, as the native_id in the pepXML. Hope it helps.

However, I have changed lines in PepXML such as below, but the skyline  did not find spectra. 

DDA pepxml
> \<spectrum_query start_scan="5" uncalibrated_precursor_neutral_mass="913.47906" assumed_charge="2" native_id="controllerType=0 controllerNumber=1 scan=5" spectrum="BGS_D_D170717_S416-Library-samples-1of6_MSG_R01_T0.00005.00005.2" end_scan="5" index="1" precursor_neutral_mass="913.4794" retention_time_sec="0.5205014906823635">
</spectrum_query>

DIA pepxml
> \<spectrum_query start_scan="2" uncalibrated_precursor_neutral_mass="2251.132" assumed_charge="2" native_id="index=1" spectrum="DIAlib_Q3.2.2.2" end_scan="2" index="2" precursor_neutral_mass="2251.1326" retention_time_sec="764.8413848876953">
</spectrum_query>

The *native_id* in output mzML is also different from DDA SpecLib and DIA-Umpire_SpecLib workflow.

DDA mzML
> \<spectrum index="4" id="controllerType=0 controllerNumber=1 scan=5" defaultArrayLength="28">
\<cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="BGS_D_D170717_S416-Library-samples-1of6_MSG_R01_T0.5.5.2 File:&quot;BGS_D_D170717_S416-Library-samples-1of6_MSG_R01_T0.raw&quot;, NativeID:&quot;controllerType=0 controllerNumber=1 scan=5&quot;"/>

DIA mzML
> \<spectrum index="1" id="index=1" defaultArrayLength="245">
\<cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="DIAlib_Q3.2.2.2"/>


"No spectra were found" happens  immediately  without native id.
After changing native_id,  the skyline spends one more seconds to search, but still no specta.

Maybe, there are still some differences in mzML and pepXML from DDA and DIA specLib workflow.

**Comment by fcyu** [comment]
The `native_id` from normal DDA and DIA-Umpire's pseudo DDA are different. The normal DDA is from the instrument but the DIA-Umpire's pseudo DDA is from our program because there is no such ID in the original DIA data.

Regarding changing the `native_id` still does not work for Skyline, I think it is better to report this to the Skyline forum.

Best,

Fengchao

**Comment by chambm** [comment]
If you're talking about trying to preserve the Thermo nativeID in the DIA-Umpire output (for Thermo input), I wouldn't bother. That doesn't make much sense for pseudo-spectra. DIA-Umpire spectra are usually combinations of many input spectra, right? Theoretically you could list the constituent spectra in the mzML <scanList> but that would probably get REALLY verbose so I'm not sure it's worth it. ProteoWizard does that with --combineIonMobility for Bruker ddaPASEF spectra grouped by precursor within a single frame, but for combining all the scans in a frame/block (like in MS1 or Waters/Agilent data), we don't list all the constituent drift scans because it would be too verbose.

(Please do not add a native_id attribute to the mzML because that would be redundant with the spectrum::id attribute which must be the nativeId.)

**Comment by fcyu** [comment]
Hi Matt,

Thanks for your suggestion. Then, we won't make any changes.

Best,

Fengchao
