### ISSUE TITLE
question about BLAS Bad memory unallocation

### ISSUE THREAD

**Issue by jadv12** [Nesvilab/FragPipe#521]
Hi,

I recently ran my full cohort with 226 samples. Near the end of the log, I saw the following lines:

BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)
BLAS : Bad memory unallocation! :  128  (nil)

I just wanted to get your thoughts on what this might be, so that I could avoid it in the future. Nevertheless, the run seemed to finish successfully in spite of this BLAS/bad memory since it did say "DONE."

[log_2021-11-09_06-32-10.txt](https://github.com/Nesvilab/FragPipe/files/7507000/log_2021-11-09_06-32-10.txt)

**Comment by fcyu** [comment]
I see that you have 128 threads, which seems too many for BLAS. Here (https://github.com/xianyi/OpenBLAS/issues/1882) is a discussion in the OpenBLAS repository. 

Can try with, say 64 threads? I don't think there is much difference in terms of the run time because 1) IO is the bottleneck, not CPU; 2) Philosopher is single-thread except for the PeptideProphet (FragPipe runs multiple PeptideProphet in parallel).

Best,

Fengchao

**Comment by jadv12** [comment]
Thanks for the feedback. I'll give the 64 thread a try. Would it matter though since the run was successful completed with the usual "DONE" and citations message?

**Comment by fcyu** [comment]
Can you help to check if there are nonzero intensities in the MaxLFQ intensity columns? But just in case, it would be better to re-run IonQuant. You can disable all other tools except for IonQuant.

Best,

Fengchao

**Comment by jadv12** [comment]
I can confirm that there are non-zero intensities in the MaxLFQ intensity columns (for the intensity, total, and unique). When I rerun it without ionquant, should I go with 64 threads?

This was my first time running the FragPipe v17.0. Since there is now distinction between intensity and Maxlfq, what do the intensity columns represent? In previous versions, was I correct to believe that intensity was the normalized maxlfq intensity?

**Comment by fcyu** [comment]
You can go with 64 even without IonQuant since IO is the bottleneck for the closed search analysis. However, if you want to perform open search or DIA analysis, can use 128 threads.

Yes, we write both intensity (which is from top-N algorithm) and MaxLFQ intensity to the file. In the previous version, if the `MaxLFQ` box in `Quant (MS1)` tab is checked, the intensity is from MaxLFQ. If it is unchecked, the intensity is from top-N.

Best,

Fengchao

**Comment by jadv12** [comment]
Thanks for answering. I finally ran it again with 64. No error and it wasn't much slower (or slower at all) like you said.
