### ISSUE TITLE
Download DIA-NN on the fly?

### ISSUE THREAD

**Issue by chambm** [Nesvilab/FragPipe#541]
DIA-NN is adding about 300MB to the FragPipe download, which seems excessive if one doesn't plan to use that feature. Have you considered downloading it on the fly when it's needed?

**Comment by fcyu** [comment]
Thanks for your suggestion. We think that it is easier for most users if we bundle it together with FragPipe. As many users and friends told me, file size is not an issue most of the time.

Best,

Fengchao

**Comment by chambm** [comment]
Perhaps, but isn't that true for Philosopher too? The download could (should) be opaque to the user, not requiring any interaction, so I'm not really sure it's harder than the bundled way.

**Comment by fcyu** [comment]
Yes, we will probably bundle Philosopher too. I don't think the download can be opaque to users since it takes time. Even letting it download in the background is not problem-free: what if the users start to run DIA-NN when it is downloading or what if something is wrong (e.g., Internet or disk issues) during the downloading. To cover all these possibilities and make it perfectly smooth (if it is possible), we need to write a lot of codes. Also, downloading and unzipping files programmingly is more or less different from downloading them by a human clicking buttons. Not sure if it would trigger some anti-virus or firewall.

In my opinion, no matter from the aspect of easy to maintain or easy to use, bundling DIA-NN is a better choice. I think 300 MB is not a big deal to the modern disk and Internet. 

Best,

Fengchao

**Comment by chambm** [comment]
I was thinking it would just be a workflow step which only needs to execute if it's not already downloaded (or is somehow incomplete). So users would already be sitting back and waiting for the Run to finish.

**Comment by fcyu** [comment]
It is possible, but I really don't think it worth the time to implement and maintain if it is just for 300 MB less file size. There are other more important features to implement.

Best,

Fengchao
