### ISSUE TITLE
MSFragger Glyco

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#547]
Greetings,

I am currently exploring MSFragger N-Glyco workflow (glyco-N-HCD). 
When I was analyzing the output PSM.tsv file to look for glycosylated peptides, some the peptides had glyco-score of negative values. (Does the negative values mean less confidence glyco peptides?).
By any chance could your direct me to a link on how to interpret the glyco output data?
Currently, I am using - "https://fragpipe.nesvilab.org/docs/tutorial_glyco.html" as my guide.

Regards,
Ben

**Comment by dpolasky** [comment]
Hi Ben,
We are in the process of improving the tutorial info, but for the moment the tutorial_glyco page that you're looking at is all we have. The two columns to look at in evaluating quality of a match are the glycan score and glycan q-value. A lower score indicates a less confident match, but a negative score doesn't necessarily mean it's a bad/low-confidence match. Depending on the quality of the fragmentation and complexity of the glycans being searched, I have seen negative scores down to -5 or so that still pass glycan FDR.
You can filter the table using the q-value column to only show PSMs that have passed glycan FDR (for example, filtering to only PSMs with a glycan q-value less than 0.01 corresponds to those that pass a 1% glycan FDR). 

If you have other questions or anything that seems like it would be helpful to have in the tutorial, please do let us know! 
Best,
Dan

**Comment by anesvi** [comment]
I think maybe we want to change the scale of our score in the future as it is indeed a bit misleading to have a negative score and may scare people, when the Q-value is actually the most relevant metric.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
