### ISSUE TITLE
Big difference of precursor identification  with MBR or without MBR.

### ISSUE THREAD

**Issue by andyzim111** [Nesvilab/FragPipe#550]
- Describe the issue or question:
I used FragPipe (17.1) to analyze 18 phospho-ddaPASEF files with MBR or without MBR to generate a spectral library.
In MBR search, I assigned all runs to the same experiment.
With MBR, psm.tsv contains 544618 PSMs, ion.tsv contains 50963 ions, peptide.tsv contains 35627 sequences, and protein.tsv contains 5029 proteins. 
Without MBR, psm.tsv contains 544618 PSMs, ion.tsv contains 40885 ions, peptide.tsv contains 35627 sequences, and protein.tsv contains 5029 proteins.

Why the identified precursors are so different?

 

[log_noMBR.txt](https://github.com/Nesvilab/FragPipe/files/7649629/log_noMBR.txt)
[log_MBR.txt](https://github.com/Nesvilab/FragPipe/files/7649631/log_MBR.txt)
[filter_noMBR.log](https://github.com/Nesvilab/FragPipe/files/7649632/filter_noMBR.log)
[filter_MBR.log](https://github.com/Nesvilab/FragPipe/files/7649633/filter_MBR.log)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
OK, there are something that need to be clarified. Let me try to explain it as clear as I can. Please feel free to ask if you have further questions.

First of all, your "without MBR" is not only without MBR. You disabled the whole IonQuant in the `Quant (MS1)` tab. Thus, the difference is with and without IonQuant. Without IonQuant, your tsv files are from MS/MS identification (generated by Philosopher), which have zero intensities for all entries (because there is no quantification step) and no MBR. With IonQuant, your tsv files are from label-free quantification (generated by IonQuant), which have non-zero intensities and MBR (if you enable it). 

Second, you assigned all your runs to a single experiment. Thus, the entries in `psm.tsv`, `ion.tsv`, `peptide.tsv`, and `protein.tsv` are from the combination of all runs. Thus, with or without IonQuant, with or without MBR, it always has the same number of PSMs, ions, and peptides, and proteins. That is also why you see the same numbers from `psm.tsv`, `peptide.tsv`, and `protein.tsv`.

As to the `ion.tsv`, without IonQuant, the file is from Philosopher, who collapses the ions with the same sequence but different modifications together. Please check this (https://github.com/Nesvilab/FragPipe/issues/279) for detail. (Oh, this issue was also from you! Thank you!). Ideally, we should list different peptideforms in different rows. Thus, IonQuant re-write it in the right way. That is why you see more entries in `ion.tsv`.

If you assigned your runs to different experiments and enable MBR. There won't be more PSMs in psm.tsv because they are from MS/MS identification, not include transferred ions. But, you will see more non-zero ions, peptides, and proteins from the `combined_*.tsv`, `ion.tsv`, `peptide.tsv`, and `protein.tsv` files.

Best,

Fengchao

**Comment by anesvi** [comment]
We should make a more extended tutorial on lfq workflows …

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyzim111** [comment]
Ok. Only if I enabled ionquant, I can get the correct number of identified precursors.  This issue is not serious for non-phos data, but has a big effect on phos data as it contain a large number of the same sequences with different PTMs.
Another question is whether library.tsv generated by easypQp contained the same number of ions with ionquant or without ionquant ?

**Comment by fcyu** [comment]
The library does not collapse the same sequence with different modifications. This issue only exists in the `ion.tsv` without IonQuant. 

But it is filtered with 1% peptide and protein FDR, which is more stringent than the ion.tsv (it is filtered with 1% PSM and protein FDR). Thus, you are supposed to see slightly fewer ions in the library.

Best,

Fengchao
