### ISSUE TITLE
DIA_DIA-Umpire_SpecLib_Quant Spec library output incompatible with DIA-NN

### ISSUE THREAD

**Issue by jiyoungyoun** [Nesvilab/FragPipe#552]
Hi Nesvilab, 

I have a format issue with spectra library output generated from DIA_DIA-Umpire_SpecLib_Quant workflow.
I would like to use this spectra library generated from DIA (via DIA-umpire) and DDA data acquired for the sample sample. This will be used as spectra library for DIA-NN analysis of the DIA file.

Input files are DIA raw file, corresponding DIA mzML file and DDA raw file of the same biological material. (e.g. A_DIA. raw, A_DIA.mzML, A_DDA.raw).

I obtained a TSV file from output, which I presume is the spectra library file. 

This .tsv file is missing columns required for DIA-NN:
Modified & labelled peptide sequence
Precursor charge
Precursor m/z
Reference retention time - arbitrary RT scale can be used
Fragment ion m/z
Relative intensity of the fragment ion)

I'd much appreciate your input.

Best,
Ji-Young

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2021-12-03_11-28-03.txt](https://github.com/Nesvilab/FragPipe/files/7651464/log_2021-12-03_11-28-03.txt)

**Comment by fcyu** [comment]
Hi Ji-Young,

It is not about the library incompatible with DIA-NN because the analysis crashed at a very early stage. Before generating the library.

There are several mistakes in your settings:
1. Please select `PEPXML_PIN` here
![image](https://user-images.githubusercontent.com/6926299/144650695-89f59247-0473-40c1-b9e0-5a525a801dc4.png)
2. Please remove your `K562_DIAtest_FixedWin_Olsen_20210920.raw` since ` K562_DIAtest_FixedWin_Olsen_20210920.raw` and `K562_DIAtest_FixedWin_Olsen_20210920.mzML` are basically the same. No need to load both.

In case there are other incorrect parameters that I didn't capture, you should load the `DIA_DIA-Umpire_SpecLib_Quant` workflow, load your data and specify the data type, load your fasta file, adjust digestion and variable modifications, and **DO NOT** change other parameters if you are not 100% sure.

Best,

Fengchao

**Comment by jiyoungyoun** [comment]
Thank you very much, Fengchao. I'll try this.

**Comment by jiyoungyoun** [comment]
Hi again, 

I have used the default setting that appears on the DIA_DIA-Umpire_SpecLib_Quant_Default to use DIA file and DDA file to generate a spectral library and run DIA-NN. (I ensured that the advanced output option is PEPXML_PIN as well)

I see FP stopped early and cancelled the job, but cannot see the source of the issue. Would you be able to take a look at the log file?

Thanks,
Ji-Youn
[log_2021-12-06_12-13-24.txt](https://github.com/Nesvilab/FragPipe/files/7662409/log_2021-12-06_12-13-24.txt)
g

**Comment by fcyu** [comment]
Can you put FragPipe to a folder where there is no space in the path? Also, please do not put FragPipe in the folder that has access restrictions, such as `C:\Program Files\`.

Best,

Fengchao
