### ISSUE TITLE
Improved Post Processing with further Deep learning

### ISSUE THREAD

**Issue by Peer2011** [Nesvilab/FragPipe#555]
Dear Fengchao, 

Could you briefly elaborate what it is all about the option Min Prob Spin which you added to the percolator Options in the dev trunk? Do you plan to implement further deep learning models for rescoring. For the sake of rescoring would it make sense to increase FDR in the intial MSFragger search if peptides are rescored with the MSBoost algorithm and Percolator afterwards. Do you think that ProteoTorch, Prosit or any other deep learning based rescoring method could further improve the search results? Thanks for your time. 

Best, Peer

**Comment by fcyu** [comment]
Hi Peer,

> Could you briefly elaborate what it is all about the option Min Prob Spin which you added to the percolator Options in the dev trunk?

Philosopher needs a lot of memory when there are a lot of data. Then, we filter out low probability PSMs, which is never used, to reduce the file size so that the memory issue can be mitigated. You can find the detailed discussion here: https://github.com/Nesvilab/FragPipe/issues/538

> Do you plan to implement further deep learning models for rescoring. 

I cannot say much about it since, technically, MSBooster is still an unpublished work.

>  Do you plan to implement further deep learning models for rescoring. For the sake of rescoring would it make sense to increase FDR in the intial MSFragger search if peptides are rescored with the MSBoost algorithm and Percolator afterwards. 

There is no FDR threshold from MSFragger. The FDR is applied after rescoring and modeling.

> Do you think that ProteoTorch, Prosit or any other deep learning based rescoring method could further improve the search results?

Maybe. Our tool will support Prosit.

Best,

Fengchao
