### ISSUE TITLE
Open search issue

### ISSUE THREAD

**Issue by peterfaull** [Nesvilab/FragPipe#557]
- Describe the issue or question:
Good morning. We are trying to run an open search to look for a +765 (a PTM called "co-alation") but the searches are not completing. The log file is attached. Any assistance would be most appreciated. Best, Peter.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2021-12-07_10-48-06.txt](https://github.com/Nesvilab/FragPipe/files/7670539/log_2021-12-07_10-48-06.txt)
)

**Comment by dpolasky** [comment]
Hi @peterfaull, 
It looks like your data are low resolution MS2 - is that right? It looks like PTM-Shepherd is having an issue because there are no results passing FDR in two of the input files (NG_2a and NG_5a). We don't recommend low-res MS2 for open searches in general due to the difficulty of distinguishing the correct peptide, which might be why there are no results passing FDR. It may also be related to the search settings - for instance, it looks like your open search is set to consider a max modification mass of 500 Da, but it sounds like your modification is +765. You can increase the precursor mass upper setting to 800 Da to find your modification. 

It might be easier to do a mass offset search if you know your modification mass rather than a fully open search (in which case you would not need PTM-Shepherd). You can find a tutorial on that here: https://fragpipe.nesvilab.org/docs/tutorial_offset.html

Best,
Dan

**Comment by peterfaull** [comment]
Excellent - thanks Dan.
