### ISSUE TITLE
Only zero-values for intensities

### ISSUE THREAD

**Issue by monicakruk** [Nesvilab/FragPipe#565]
Hello Nesvilab!

We are very happy with your Fragpipe/MSFragger software! Great work, and thank you for your efforts. One thing we haven't been able to figure out is why we are not getting any values in the intensity columns of our protein, peptide, and ion .tsv outputs from Fragpipe even though the MS1 Quant/IonQuant option is selected. I've attached the log file in the case something stands out.
![image](https://user-images.githubusercontent.com/96442112/146822035-40e58bf1-6a18-467f-8ad6-1faab7273790.png)

If nothing pops out in the log file, perhaps it could be the way I have my program files' paths.

Thanks in advance,
Monica

[log_2021-12-15_22-20-07.txt](https://github.com/Nesvilab/IonQuant/files/7747560/log_2021-12-15_22-20-07.txt)

**Comment by fcyu** [comment]
You didn't enable IonQuant.

If you want to perform label free quantification, please load the `LFQ-MBR` workflow, adjust fasta file, enzyme, and variable modifications. And DO NOT change other parameters unless you know what they are.

Best,

Fengchao

**Comment by fcyu** [comment]
I am sorry that I didn't check carefully, you do enabled IonQuant, but also enabled `spectral library generation`, which crashes. 

Furthermore, You also enabled `generate peptide-level summary` and `generate protein-level summary`. Please DO NOT do that because Philosopher needs lots of memory to generate these two files. With these two enabled, it would take lot of time and you will probability see another error messages. We disable them on purpose because IonQuant will generate it later, which is much faster and more memory efficient.

Best,

Fengchao
