### ISSUE TITLE
Search for heavy nitrogen

### ISSUE THREAD

**Issue by anfoss** [Nesvilab/FragPipe#585]
Hi,

I acquired SILAM data and I am wondering whether this is supported by Fragpipe/MSfragger. Is there a way to search with fixed heavy nitrogen?

**Comment by fcyu** [comment]
I think the only way is adding the mass difference to the fixed modification. For example:
```
add_G_glycine = 0.997035               
add_A_alanine = 0.997035               
add_S_serine = 0.997035                
add_P_proline = 0.997035               
add_V_valine = 0.997035                
add_T_threonine = 0.997035             
add_C_cysteine = 59.015534              
add_L_leucine = 0.997035               
add_I_isoleucine = 0.997035            
add_N_asparagine = 1.99407             
add_D_aspartic_acid = 0.997035         
add_Q_glutamine = 1.99407              
add_K_lysine = 1.99407                 
add_E_glutamic_acid = 0.997035         
add_M_methionine = 0.997035            
add_H_histidine = 2.99111              
add_F_phenylalanine = 0.997035         
add_U_selenocysteine = 0.997035        
add_R_arginine = 3.98814               
add_Y_tyrosine = 0.997035              
add_W_tryptophan = 1.99407      
```

Best,

Fengchao

**Comment by Arthfael** [comment]
Has anyone successfully used these parameters? They make perfect sense, but we have not been successful using them and are wondering if maybe this many mass shifts may not be breaking the search algorithm? Any testimonies would help greatly with the troubleshooting.

On two occasions now, we have tried with samples from a client who said they fully labelled it with N15 - they are an NMR lab, I do not know what the standard for full labeling is for NMR. The only difference is IAA was not labelled so the cysteine mass shift would have been 58.0185
Hardly anything was identified. We know that the sample should not be empty, and used a very sensitive instrument. A search without the N15 mods identified plenty of trypsin and keratin peptides only, which I take it indicates that non-contaminant proteins in the sample are at least partially labelled - to the point of not being identifiable with a normal search.

Right now I am exploring two main possibilities:
 a) Samples labeling efficiency is insufficient, and we are in the grey zone where neither a normal nor a N15-only search work. Unfortunately these modifications cannot be searched as variable, for reasons which I think are obvious.
 b) These parameters - which are a bit of an extreme case and, beyond the monoisotopic mass shift, would also completely change the shape of peptide and fragment envelopes - may actually break FragPipe. Which would be fine, it really is an edge case ^^ 
Hence why I would be really interested to know if anyone has had any success with those?

**Comment by Arthfael** [comment]
I was doing some reading on the subject and stumbled on: https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/10.1002/pmic.200900108

Based on this idea, I have run the following tests:
- A search with from -10 to +0 Da precursor MS1 mass error (essentially a limited Open Search) increased the discoveries somewhat, I went from 1 peptide for my protein of interest to 3. I also found out that most peptides identified had a -1 to -3 Da mass error.
- With a normal closed N15 search + the following new "promiscuous" modification: -0.997035 Da on ACDEFGHIKLMNPQRSTVWY, max 1 occurrence (more breaks MsFragger), I reached 6 peptides.
- With the same as above, but using a search database now limited to those proteins observed in the previous search (+ contaminants and reverse hits) and allowing 3 occurrences of the promiscuous mod per peptide, I reached 12 peptides.
- Increasing FDR (pep-level) to 5%, and adding, on a colleague's suggestion, negative mass shifts for n = 2-4 light nitrogens (each applicable to amino acids with a number of nitrogen atoms superior or equal to n) improved a bit more.

Importantly, this strategy only worked well because I had low complexity samples. For samples where the number of proteins is high, search space will explode, so you may want to stick with the modified open search or only the basic promiscuous single light N varmod, depending on complexity and computing resources.
