### ISSUE TITLE
No MAX LFQ intensity columns in combined_protein.tsv

### ISSUE THREAD

**Issue by ihorrible** [Nesvilab/FragPipe#599]
Hi everyone ! 

My Quant LFQ was performed without any errors and everything seems OK except that I do not have any MAX LFQ intensity columns as it is described in guide (https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html#combined_proteintsv). 

How can I activate this in order to get MAX LFQ columns in combined protein report?

![colnames](https://user-images.githubusercontent.com/63013549/152728737-79545491-0ee6-4b96-880e-ef3a6fe75b09.PNG)

Thanks, 

Ivan  
----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment]
Can you send us your log?

Thanks,

Fengchao

**Comment by ihorrible** [comment]
[log_2022-02-05_10-02-39.txt](https://github.com/Nesvilab/FragPipe/files/8021498/log_2022-02-05_10-02-39.txt)

Here it is

**Comment by fcyu** [comment]
```
2022-02-05 09:55:19 [WARNING] - There are only 2 experiments. Disable MaxLFQ.
```

You only have 2 experiments. We needs at least 3 experiments for MaxLFQ.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Hanna,

Since you are using an old version, IonQuant prints either top-N or MaxLFQ intensity in the intensity column. Thus, in your combined_protein.tsv file, the intensity columns have the MaxLFQ intensity. If you want to see both intensity and MaxLFQ intensity, please upgrade FragPipe, MSFragger, IonQuant, and Philosopher to the latest version (and you should do that in any way.  The new version has a lot of improvements).

Best,

Fengchao

**Comment by hanna6703** [comment]
Will do for future runs. Glad to hear that there is no need to re-run.
Have a nice day!
Hanna
