### ISSUE TITLE
TMT Integrator produces bimodal intensity distributions

### ISSUE THREAD

**Issue by Jonathan8er** [Nesvilab/FragPipe#609]
Dear FragPipe team,

I've been analyzing a TMT data set with FragPipe enabling the Quant (isobaric) option.  When plotting the density of normalized log2 intensities from the tmt-report, I observe a bimodal distribution which I have also seen in another published study that used TMT-Integrator. In contrast, searching the same data set with MaxQuant results in a unimodal distribution of log2 intensities. I am wondering about the cause of this distinct pattern and if that could negatively affect the quality of quantification. Filtering for at least two PSMs in the report can only partly resolve this issue.

I would also like to know if there is an option to apply correction factors for isotopic impurities of the TMT reagent in FragPipe. 

Thank you for your help,
Jonathan

![density before norm](https://user-images.githubusercontent.com/93535717/155550084-0c46dd81-760f-43cf-adbe-30fa1545bd93.png)

**Comment by anesvi** [comment]
This is not related to the isotope correction.  It is because when we convert from ratios to final abundances, we use MS1 precursor ion intensity as part of that by default. And if the software cannot quantify the precursor, there is a missing value imputation step applied. In smaller datasets (like just 1-2 plexes) it creates this "artifact" bump corresponding to the imputed vases. It normally does not affect the results anyway downstream. You can also change in TMT-Integrator to not using MS1 precursor intensity. Uncheck 'use MS1' and 'use top 3' boxes at the bottom of the panel. We can probably add an option in TMT-I not to impute.

**Comment by anesvi** [comment]
Sorry, I see you asked about the isotope correction as a separate question. No, we do not do that. We found it actually introduces new problems, often more than the problem it tries to solve.

**Comment by Jonathan8er** [comment]
That's the explanation I was looking for. Thank you!
