### ISSUE TITLE
TMT-integrator java.lang.nullPointerException

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/FragPipe#617]
Hi,

I keep getting an java.lang.nullPointerException. Any idea what could cause it?

Attached an example and the log.
[log_2022-03-04_09-05-29.txt](https://github.com/Nesvilab/FragPipe/files/8197279/log_2022-03-04_09-05-29.txt)

TmtIntegrator [Work dir: D:\Patrick\AD_CSF_META\_Results\Omar]
java -Xmx132G -cp "B:\fragpipe17\tools\tmt-integrator-3.2.0-rc1.jar" TMTIntegrator D:\Patrick\AD_CSF_META\_Results\Omar\tmt-integrator-conf.yml D:\Patrick\AD_CSF_META\_Results\Omar\TMT1_1\psm.tsv D:\Patrick\AD_CSF_META\_Results\Omar\TMT1_2\psm.tsv D:\Patrick\AD_CSF_META\_Results\Omar\TMT2_1\psm.tsv D:\Patrick\AD_CSF_META\_Results\Omar\TMT2_2\psm.tsv D:\Patrick\AD_CSF_META\_Results\Omar\TMT4_1\psm.tsv D:\Patrick\AD_CSF_META\_Results\Omar\TMT4_2\psm.tsv
UpdateColumns--- 0.10915 min.
Error at: D:\Patrick\AD_CSF_META\_Results\Omar\TMT1_1\psm.tsv java.lang.NullPointerException
Process 'TmtIntegrator' finished, exit code: 0****

**Comment by anesvi** [comment]
I don't know what the issue is. But I noticed that an older version of FragPipe is used
Version info:
FragPipe version 17.0
MSFragger version 3.4
Philosopher version 4.1.1 (build 1637179075)

Please upgrade to 17.1 and see if the error is there. If yes, then we can share a pre-release of FragPipe 18 to test

**Comment by PatrickvanZalm** [comment]
Seemed to have done the trick.

Thanks!

Patrick
