### ISSUE TITLE
Log4J vulnerability 

### ISSUE THREAD

**Issue by fazeliniah** [Nesvilab/FragPipe#625]
Dear Fragpipe developer team, 
We have received the following email from our IT dept:

"I am reaching out in regards to a vulnerability that has been found in your ... system. The program in question is “Fragpipe”, I have your remediation ticket and I’m here to work with you to figure out the best way to handle this vulnerability I was wondering is this application critical to your workflow?"

I know this issue has been brought up before, but I am not sure there has been a new software update. Any help is greatly appreciated. 
Thanks

**Comment by fcyu** [comment]
Thanks for your feedback. I think it is related to https://github.com/Nesvilab/FragPipe/issues/580.

Hi Guo Ci @guoci , 

I understand that you think the log4j that DIA-Umpire is using is not vulnerable because it is version 1.0 not 2.0. But for safe, can you upgrade log4J or replace it with slf4j as soon as possible?

Thanks,

Fengchao

**Comment by fazeliniah** [comment]
Thanks! Do you think we can remove the Umpire for now and use the other modules in Fragpipe? Are there any other files that we need to be aware of having similar problem?

**Comment by fcyu** [comment]
Yes, you can delete dia-umpire in the tool folder for now. To my knowledge, there are no other files having log4j.

Best,

Fengchao

**Comment by guoci** [comment]
@fazeliniah this will be fixed in the next release
