### ISSUE TITLE
IonQuant and Philosopher questions

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#642]
Hello,
I have a few specific questions about the "behind the scenes" operation of IonQuant and the resulting outputs.  I want to make sure that I am understanding the IonQuant settings and interpreting the reports correctly.

1) **Relationship between "FDR Filter and Report" in "Validation" tab and Quant (MS1)**. I recently performed a qualitative analysis with Default (closed search) workflow.  Then I ran Quant (MS1) separately by unchecked all boxes in MSFragger and Validation tab, and checking IonQuant settings.  This seems to have worked but I wanted to make sure that I didn't need the "FDR Filter and Report" option.  The reason I ask is because when I load the LFQ-MBR default workflow, the FDR Filter and Report options are enabled with "Filter" flags: --sequential --prot 0.01.    But when I ran my first qualitative search, the flags were: --sequential --picked --prot 0.01.  Do these flags make a different for IonQuant, or does IonQuant have its own report settings that overide this step in Validation?

2) **m/z tolerance question**. In the Quant (MS1) tab, I see there is a separate RT tolerance for feature detection and for MBR. However, I only see an m/z tolerance for feature detection, but not for MBR.  Is the m/z tolerance for MBR dynamic? or is it the same as the one used for feature detection?

3) **A general question on the "combined_protein" report.** If I am not mistaken, there is no column that provides unique or razor peptides, specifically, a column for "number of peptides where the selected protein is the razor assignment for that peptide."  I only see either Combined Total Peptides, or the other columns are at the Spectral Count level. 
I assume a Unique Spectral Count of >1 could still be from a single peptide?
Also, is it correct that the shared peptides in the Combined Total Peptides are counted for each protein group they are mapped to?
Overall, this is really minor comment as the software has so many great features, but I am wondering if there was a specific reason that unique/razor peptides are not counted for the report?

4) Proteins with zero Unique Spectral Counts and no Indistinguishable Proteins.  I have protein entries with zero unique spectral counts that I can see in the Combined_ion report have mappings to >1 other protein.  The main protein reported is not listed with Indistinguishable notation.  The proteins with shared peptides are also not in the combined protein list, so I assume there are no peptides to support their inclusion based on parsimony. 
For one specific case, I have peptides for the primary protein ID that can map to two other entries. When I looked at the proteins that could be considered indistinguishable, one appears to be indistinguishable, while the other is missing one peptide. I would have initially expected the one indistinguishable protein to be listed but not the other. Is the reporting "all or none" behavior?

5) Related to 4, am I correctly interpreting "unique " as PSMs that map only to one entry in the sequence database?  In other words, the definition of unique or shared here does not depend on the other mapped proteins having unique or only shared evidence from the experiment; it only depends on the sequences in the original database?  Given this definition, this would support my interest mentioned above in a Combined (Razor) Peptide output. 

Thank you in advance for considering my rather technical questions. Apologies if my questions are repeated in other posts, I did make an attempt to look for these specific questions!

Best,
Todd

**Comment by fcyu** [comment]
Hi Todd,

Following are my answers to your questions.

1. Yes, the flags are different in different workflows, which results in slightly different FDR cut-off. IonQuant take whatever in the psm.tsv and protein.tsv files to process. It does not have its own FDR filtering.
2. They use the same m/z tolerance.
3. > I assume a Unique Spectral Count of >1 could still be from a single peptide?

I am sorry that I can't follow your question. Unique spectral count is the number of spectral from unique peptides.

> Also, is it correct that the shared peptides in the Combined Total Peptides are counted for each protein group they are mapped to?

If I understand your question correctly, yes.

> I am wondering if there was a specific reason that unique/razor peptides are not counted for the report?

There is no specific reason. Maybe Felipe @prvst can give you some idea about why those counts are not reported.

4. I am not sure if I follow your question. Maybe you can give an example. BTW, the protein assignment is based on the identified peptides, not all peptides in the fasta file. 
5. If I remember it correctly, it is based on the identification result, not the fasta file. @anesvi Am I correct?

**Comment by enonimos** [comment]
Hi Fengchao,
Thanks for the quick responses, this helps alot.  I just have a few follow-up question.

1. Could you explain more about the FDR algorithm used by the --picked flag?  Is there anything about it that isn't recommended when doing LFQ-MBR?

2 and 3. Thanks, I understand now.

4 and 5. Sorry, I did not explain this very well. I've attached an Excel file with two examples that I hope will help explain.  
     Q1. The first sheet "combined_protein examples" lists two entries.  The first entry with the leading protein ID F5H8R6 has an indistinguishable protein listed, P16787.  When I look up both protein IDs in the combined ion file,  F5H8R6 is the leading protein ID, and all ions are listed as mapped to P16787. In this case, I understand the designation of indistinguishable proteins.
The behavior I'm not sure I understand is in the second  protein entry, C0H677.  Looking up this entry in the ion file (3rd Excel sheet), every ion can be mapped to C0H677 and P16764, while every ion except one, can also be mapped to Q6SWA3.  Wouldn't P16764 be considered indistinguishable and would be listed in that column in the "combined_protein".  Could other distinguishing ions below the FDR threshold be used to affect this assignment?

Q2.  For F5H8R6 which is indistinguishable from P16787, there is no independent evidence that would prove which of these is present/absent in the experiment. In this case, if I'm not mistaken, we could consider these 2 entries as a single protein group according to typical parsimony rules. Some software I have used in the past would consider the peptides/spectra that are mapped to this protein group as unique.  And since it had zero unique SpC, I had initially thought there would be another protein group/entry that had these same spectra mapped but with additional spectra that would map to one protein (and would be unique).  But as far as I could tell, in the FragPipe output, this is not the approach as this was the only entry with these assigned ions.  Just wanted to confirm if this is the expected behavior?

Thanks again,
Todd

**Comment by prvst** [comment]
Hi @enonimos, and I'll try to answer your questions one by one, some might be hard to explain without having the files in had, but hopefully I'll be able to tell you how to read the XML files in order to understand your results.

"Check the XMl files first" is the mantra I repeat to everyone with similar questions or problems. Based on my experience, I can tell you that most of the questions people have related to sequence mapping, and protein grouping can be answered by inspecting the interact.pep.xml and interact.prot.xml files. My first suggestion to you is to get familiar with them.

> If I am not mistaken, there is no column that provides unique or razor peptides, specifically, a column for "number of peptides where the selected protein is the razor assignment for that peptide."

The columns that are just named "Intensity" or Spectral Count are the Unique + Razor ones. We renamed them last year to make the file header more "readable".

>Could you explain more about the FDR algorithm used by the --picked flag? Is there anything about it that isn't recommended when doing LFQ-MBR?

The picked FDR algorithm was published in 2015 by *Savitski et al.*, and you can read more about it [here](https://pubmed.ncbi.nlm.nih.gov/25987413/). Our version is just an implementation of what they describe in there.

>I correctly interpreting "unique " as PSMs that map only to one entry in the sequence database?

Unique means that the peptide sequence maps to only one protein, not protein group. If the peptide maps to multiple proteins in the same group, then the peptide is considered a shared peptide.

> Proteins with zero Unique Spectral Counts and no Indistinguishable Proteins.

This is a bit more tricky. If we assume that there's no problem with the algorithm, there can be a few ways to explain why you see cases like this. It's worth mentioning that there's a difference between *alternative proteins*, and *indistinguishable proteins*. The first one is a PeptideProphet classification, and is present in the interact.pep.xml file, meaning that the peptide sequence also maps to the other protein from the database. Indistinguishable protein is a ProteinProphet classification, and it means that it identified the proteins at hand using the same set of peptides. At some point, we had both classifications in the same Mapped Proteins column. During the FDR filtering, the program separates the data into "layers" (i.e., PSM, peptides, ions, proteins), and each one of them is filtered individually, meaning that you can have different thresholds for the FDR and probability score. The razor assignment combined with the two-step FDR filtered can create scenarios where a protein will be left without a supporting PSM, and vice-versa. At the end, the peptides, ions and[roteins you'll see in the final reports need to survive all these steps. If you want to track down the relationship between a peptide sequence and its alternative and indistinguishable proteins, I suggest you start with the XMl files. They might be large, but they're easy to read.

**Comment by fcyu** [comment]
Hi Felipe @prvst ,

> This is a bit more tricky. If we assume that there's no problem with the algorithm, there can be a few ways to explain why you see cases like this. It's worth mentioning that there's a difference between alternative proteins, and indistinguishable proteins. The first one is a PeptideProphet classification, and is present in the interact.pep.xml file, meaning that the peptide sequence also maps to the other protein from the database. Indistinguishable protein is a ProteinProphet classification, and it means that it identified the proteins at hand using the same set of peptides. At some point, we had both classifications in the same Mapped Proteins column. During the FDR filtering, the program separates the data into "layers" (i.e., PSM, peptides, ions, proteins), and each one of them is filtered individually, meaning that you can have different thresholds for the FDR and probability score. The razor assignment combined with the two-step FDR filtered can create scenarios where a protein will be left without a supporting PSM, and vice-versa. At the end, the peptides, ions and[roteins you'll see in the final reports need to survive all these steps. If you want to track down the relationship between a peptide sequence and its alternative and indistinguishable proteins, I suggest you start with the XMl files. They might be large, but they're easy to read.

Do you mean that the reason of the second example missing the indistinguishable protein is due the FDR filtering? The indistinguishable protein was filtered out with 1% protein FDR.


As to your first answer:

> If I am not mistaken, there is no column that provides unique or razor peptides, specifically, a column for "number of peptides where the selected protein is the razor assignment for that peptide."

> The columns that are just named "Intensity" or Spectral Count are the Unique + Razor ones. We renamed them last year to make the file header more "readable".

They were asking why the unique and razor **peptide counts** are missing. I don't think it has anything to do with the "intensity" column.

Best,

Fengchao

**Comment by prvst** [comment]
I think so, but again, this is hard to answer without looking at the files. The protein might not be there because of the razor assignment too. It could also be something that we didn't predict but I think it might be because of the razor assignment.

If it's about the combined total peptides, then yeah, we just report the total numbers. We changed that a couple of years ago.

**Comment by enonimos** [comment]
Thanks @prvst and @fcyu for the explanations.  Given the razor protein reporting strategy (instead of protein group strategy), it makes sense to me now why you removed reporting of separate unique peptides columns, and only focus on unique+razor.

Having been a user of the TPP, I am comfortable with digging into the xml formats, so I may check that out for specific assignments, thank you for explaining the complexes and what to look out for.  One final clarification on this point of tracking down peptide evidences. Should I expect that an PSM, ion, or peptide that is below its FDR probability threshold could be used to annotate the "indistinguishable proteins" column in the combined_protein file, or each layer evaluated after the FDR filtering?
