### ISSUE TITLE
FragPipe - DIA_SpecLibQuant, FAIMS & multiple CVs - no Dia-NN Quants

### ISSUE THREAD

**Issue by kabalak** [Nesvilab/FragPipe#662]
[FragPipe_DiaNN_MultipleCVs_ERROR_log.zip](https://github.com/Nesvilab/FragPipe/files/8557033/FragPipe_DiaNN_MultipleCVs_ERROR_log.zip)

Running FragPipes (v17.1) DIA_SpecLibQuant workflow with FAIMS data (recorded on an Exploris48 with multiple CVs) for a N-termini dataset, I do get identifications, but no quantifcations from Dia-NN. Is there any way to get it running with FragPipe/msConvert strategies? Converting the .raw files to CV-separated .mzXMLs is not sufficient, as Dia-NN cannot handle .mzXMLs generated by https://github.com/PNNL-Comp-Mass-Spec/FAIMS-MzXML-Generator and after a second round of conversion from .MzXML into .mzMLs with msconvert (default settings), I just get no output.

Honestly, feels like a Dia-NN bug rather, but is there any other way of quantification for DIA data in FragPipe?

**Comment by fcyu** [comment]
May I ask how many CVs in your data? If there is only one, DIA-NN supports it: https://github.com/vdemichev/DiaNN#:~:text=FAIMS%20with%20constant%20CV%20is%20supported

The error you were getting is due to the missing Thermo library. You need to install it by yourself according DIA-NN readme: https://github.com/vdemichev/DiaNN#:~:text=Reading%20Thermo%20.raw%20files%20requires%20Thermo%20MS%20File%20Reader%20to%20be%20installed.%20It%20is%20essential%20to%20use%20specifically%20the%20version%20by%20the%20link%20above%20(3.0%20SP3).

Or, you can convert it to mzML using msconvert if there is only one CV.

Another thing that you need to keep in mind: FragPipe generates one spectral library for each experimental group. Thus, if you want to have a spectral library from all runs, you need to clear the experimental groups. DIA-NN will quant each DIA run separately in any way.

Best,

Fengchao

**Comment by kabalak** [comment]
I am using 2 CVs for the runs which I try to quantify with Dia-NN at the moment; thanks for the hint with the Thermo library. After installation of the corresponding library, the error message disappeared and the run finished and I get Dia-NN output tables. Is it correct, that the FragPipe output tables do not feature any intensities even is quantification seems to work with Dia-NN? (I am personally surprised that it worked with 2 CVs at all - I only supplied raw files and eliminated the experiment assignments as you suggested).
[FragPipe_DiaNN_Multiple_CV_Log.zip](https://github.com/Nesvilab/FragPipe/files/8561095/FragPipe_DiaNN_Multiple_CV_Log.zip)

**Comment by kabalak** [comment]
![FreeStyle_Split_CVs_Completely](https://user-images.githubusercontent.com/75732067/165453607-edee57ca-6522-4a14-81eb-cfa02b0a57ad.jpg)
Just for documentation purpose: attached a screenshot how to correctly split the FAIMS raw files with multiple CVs within FreeStyle; the important point is to use a manual filter "cv=CV" (e.g. "cv=-61") in the chromatogram selection window. If you use the automatically supplied filter options, you always only filter for the MS1 level. I will now try in addition with the split CVs into raw files to see if this is superior or not - afterwards I will for sure be annoyed by the fact that there is no automated tool for this purpose, if you think of cohort data generation...
