### ISSUE TITLE
list of matched b/y ions from psm

### ISSUE THREAD

**Issue by letung1992** [Nesvilab/FragPipe#719]
I'm interested in extracting the list of matched b/y ions (not just total number of matched ions) for each PSM identified by MSFragger. Could you kindly instruct me on how to do it? 
Thank you so much for your time.

**Comment by fcyu** [comment]
Similar to https://github.com/Nesvilab/FragPipe/issues/885

I have implemented the feature to report the matched fragments. Let MSFragger generate the tsv report will have those two new columns. If you want to try the pre-released version, please send an email to yufeATumich.edu (replace `AT` with `@`).

Currently, there are some limitations

The reported fragments are not exactly the one used in the scoring because MSFragger does not record such information (to be fast). I let it "re-match" the fragments when generating the report.
The fragments are deisotoped by default, so the reported matches only have singly charged. Disabling the deisotoping in the database search will have doubly charged fragments being matched, but the sensitivity is sub-optimal.
It only supports closed search now, but I will extend it to open and mass-offset search in the future.
Best,

Fengchao
