### ISSUE TITLE
strycttrypsin vs trypsin in protein digestion in MSFragger

### ISSUE THREAD

**Issue by ihorrible** [Nesvilab/FragPipe#756]
Hello, MsFragger! 

We used trypsin gold in our experiment as protein digest. We see a big difference in additional +2000 proteins when we use strycttrypsin instead of trypsin in MSFragger setup.  We are liitle bit confused which protease should we in our case. 

1. We like the results with strycttrypsin selected, but would like to understand the difference between stricttrypsin vs trypsin. 
2. We also see the warning notice in FragPipe that it should be trypsin or trypsin cnbr, but we 100% sure that is not a trypsin cnbr. 

Thanks,

Ivan T. 

[log_2022-03-30_12-32-18_stricttrypsin.txt](https://github.com/Nesvilab/FragPipe/files/9084228/log_2022-03-30_12-32-18_stricttrypsin.txt)
[log_2022-04-06_16-55-07_trypsin.txt](https://github.com/Nesvilab/FragPipe/files/9084230/log_2022-04-06_16-55-07_trypsin.txt)
![Screenshot 2022-07-11 162340](https://user-images.githubusercontent.com/63013549/178276256-3e4e2fa1-ddc5-4904-b34a-fc6e63dc48b5.png)
![trypsin cnbr](https://user-images.githubusercontent.com/63013549/178276264-6dd12bda-8c15-4de1-855f-51bb8864c222.jpg)

**Comment by dpolasky** [comment]
Hi Ivan,

The Stricttrypsin rules allow cleavage before Pro while the Trypsin rules do not, other than that they are identical. If you are seeing an increase in IDs with stricttrypsin, it is likely because there are some cleavage events at K|P or R|P that are getting detected - we also observe some increase with stricttrypsin and have changed it to be the default for most workflows. I also notice that you have two different sets of raw files in the logs for the two searches - different data could also explain the differences in the results. 

You can safely ignore the warning from FragPipe about finding matching enzymes - that's a note from the internal FragPipe enzyme matching code saying that the rules entered can match multiple enzyme rule sets, but it has no effect at all on the search or results. There is a bug in the enzyme matcher that leads to this warning, which will be fixed in the next release.

Best,
Dan
