### ISSUE TITLE
Feature request - associate diagnostic ions with particular PTMs

### ISSUE THREAD

**Issue by andrewrobertjones** [Nesvilab/FragPipe#761]
Hi all,

Big fan of MS-Fragger and starting to try it out for various PTM-enriched searches. For some of the data sets I want to search, there are known diagnostic ions associated with a specific PTM. In FragPipe / MS-Fragger params file, I see there is an option to set diagnostic ions in general for labile_search mode, but is there a way to associate diagnostic ions with the identification of a specific modification. I am currently trying to re-analyse SUMO-related data sets, and here is a bit of relevant methods text:

"QQTGG was set as a lysine-specific modification, with a monoisotopic mass of 471.20776, and was not allowed to occur at the C-terminal end of peptides. Pyro-QQTGG may spontaneously form out of the tryptic QQTGG remnant as a result of cyclization of the N-terminal glutamine. Pyro-QQTGG (pQQTGG) was set as a lysine-specific modification, with a monoisotopic mass of 454.18121, and was not allowed to occur at the C-terminal ends of peptides. In order to increase identification confidence, diagnostic peaks were searched within MS/MS spectra corresponding to SUMOylated peptides. To this end, candidate MS/MS spectra were searched for peaks corresponding in m/z to fragmentation of the tryptic QQTGG or pQQTGG remnant present on all SUMOylated peptides. For QQTGG, b5-QQTGG, b4-QQTG, b3-QQT and b2-QQ were accepted as diagnostic peaks. For pQQTGG, b5-pQQTGG, b4-pQQTG, b3-pQQT and b2-pQQ were accepted as diagnostic peaks." from https://www.nature.com/articles/nsmb.3366 and data set PXD005296.
Thanks 
Andy

**Comment by dpolasky** [comment]
Hi Andy,

As you surmised, at the moment we can't associate specific diagnostic ions with specific mass offsets (modifications) unfortunately, everything is treated together. I can definitely see how it would be very helpful for the SUMO peptides (and for other searches)! This is something we've discussed adding previously, but the implementation would be quite a project - I'll leave this open and hopefully we can get to it in an upcoming release. 

In the meantime, a possible workaround could be to do two searches, one for regular and one for pryoQ (with the appropriate mass offset and diagnostic ions in each case) and merge the results with iProphet, to get only spectra with the correct diagnostic ions for each offset. It is quite a bit more work since we don't have an integrated iProphet option yet in FragPipe - would have to run that step separately. Feel free to shoot me an email directly (dpolasky [at] umich.edu) if you have questions about trying that. 

Best,
Dan

**Comment by dpolasky** [comment]
Support for pairing specific diagnostic ions, fragment remainder ions, and/or peptide remainder ions to specific mass offsets is now available in MSFragger 4.1 and FragPipe 22, using the new detailed mass offset mode in MSFragger.
