### ISSUE TITLE
Heap space out of memory; large search space

### ISSUE THREAD

**Issue by Professor333** [Nesvilab/FragPipe#782]
I have some large peptide databases to search, from 10Gb to 160Gb. I've configured my linux system with 128Gb of physical RAM to have 3Tb of Swap space (virtual mem). I'm able to get JVM to launch with 2700Gb of virtual memory, but still receive an error that MSFragger is out of memory. 

I'm wondering why 128Gb of physical RAM can't handle a 10Gb file, and why the Swap space isn't being used.

For example, before I run Fragpipe I'll pass some Java options to increase the amount of heap (which should include both physical and swap, but Fragpipe seems to not see it), like so: export _JAVA_OPTIONS="-Xmx2500g -Xms15g -Xmn10g -XX:+UseLargePages -XX:LargePageSizeInBytes=1048576000"

I'm also not sure if Fragpipe is using huge page files, but thought I'd try enabling anyways. Hopefully you all can give me some tips on how to get this working because I believe the computer actually has enough memory to handle these large database files, but it seems something in the software isn't seeing the memory.

**Comment by fcyu** [comment]
Can you send us the log file？

Thanks,

Fengchao

**Comment by Professor333** [comment]
I'm uploading two log files here. One from a run via the GUI, which in the interface appears to limit the numerical value of RAM to the physical RAM of the machine instead of the Java estimated heap space. You'll see a line before MSFragger "Picked up _JAVA_OPTIONS: -Xmx2700g" and "JVM started with 2700 GB memory" because I passed, export _JAVA_OPTIONS="-Xmx2700g  before launching FragPipe from the terminal. 
[log_2022-07-29_22-30-47.txt](https://github.com/Nesvilab/FragPipe/files/9225435/log_2022-07-29_22-30-47.txt)


The second log I copied from the console because it was run f
rom terminal with --headless, and apparently that doesn't generate a log file in the output directory. In it, I've set ram to 2900g, and you'll see a line "JVM started with 2900 GB memory." 
[headless_log.txt](https://github.com/Nesvilab/FragPipe/files/9225437/headless_log.txt)


I'd appreciate any advice or explanation you can offer. This database I'm searching is 15.5Gb with decoys on a machine with 128Gb physical RAM and 3TB Swap space.

**Comment by fcyu** [comment]
Thanks for your file.

First of all, I don't think the virtual memory will be guaranteed to be used. It dependents on the OS and JVM. Even it is used, it would be super slow.

Second, I don't think it makes any sense to give JVM 2900 GB memory because 1) Java array's maximum length is capped by 32-bit int. This will become the bottleneck for MSFragger before it uses all 2900 GB memory; 2) Some JVM has issues when the memory size is larger than, say, 512 GB (we received GitHub issues before).

I suggest you increase 'split database' in the MSFragger tab to, say, 16 to let FragPipe split your fasta files into small chunks. You will need Python for this function to work.

Best,

Fengchao
