### ISSUE TITLE
Error on Umpire DIA

### ISSUE THREAD

**Issue by tasos2310** [Nesvilab/FragPipe#804]
Hi all,
I am trying to perform a DIA analysis with the tool DIA Umpire. I am using mzmL files from DIA data from a Thermo instrument. I am trying to run the samples with the following settings and the message that I see was about an error 2. Could you please tell me any idea about what is wrong to the following procedure?

[DIA error.txt](https://github.com/Nesvilab/FragPipe/files/9398863/DIA.error.txt)
![DIA Umpire](https://user-images.githubusercontent.com/105027375/186056976-c365bdf9-1a95-43cd-8582-296dbe2b7175.png)

**Comment by fcyu** [comment]
One possible reason is not enough memory. Your computer only has 3 GB free memory. Can you try with more memory, say 16GB?

Best,

Fengchao

**Comment by tasos2310** [comment]
Hi Fenghao,
My computer has 16gb ram, and I don't believe that this is the problem, because when I have a problem like this the error message is clearly, Not enough memory.
Best,
Tasos

**Comment by fcyu** [comment]
Please see the following messages from your log file:

C:\Users\samar\Downloads\FragPipe-jre-18.0\fragpipe\jre\bin\java.exe **-Xmx3G** -Dlibs.thermo.dir="C:\Users\samar\Downloads\FragPipe-jre-18.0\fragpipe\tools\MSFragger-3.5\ext\thermo" -cp "C:\Users\samar\Downloads\FragPipe-jre-18.0\fragpipe\tools\DIA_Umpire_SE-2.2.8.jar;C:\Users\samar\Downloads\FragPipe-jre-18.0\fragpipe\tools\batmass-io-1.25.5.jar" dia_umpire_se.DIA_Umpire_SE C:\Users\samar\Fractionation_test\Tassos_1_Dia_S2-A1_1_526.mzML C:\Users\samar\OneDrive\PC\proteomics_fractination\results_DIA\umpire-se.params

Caused by: java.lang.OutOfMemoryError: **Java heap space**

FragPipe automatically detects the free memory size. This time, it found 3 GB (`-Xmx3G`).

The error message: `Caused by: java.lang.OutOfMemoryError: Java heap space` is also easy to understand: out of memory.

Best,

Fengchao

**Comment by tasos2310** [comment]
Thank you Fengchao,
Sorry I didn't understand that this error related too with the limited memory. I will try in a more powerfull computer.
Best,
Tasos
