### ISSUE TITLE
Recommendation for partial processing

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#805]
Hello FP developers,
I am collecting data for a large multi-set DDA label-free quant experiment.  My goal is to generate interim search results after each set of data is collected. In this way, each additional set will be added to the previous sets collected to generate an updated protein report.  I wanted to get advice on the best computational approach to use FragPipe for partial processing. Specifically, I don't want to repeat unnecessary steps for previous data that has already been processed (e.g. by MSFragger).  Currently I have been performing the following:

1) Dataset set "n":  Complete workflow analysis (MSFragger, MSBooster, Percolator, ProteinProphet, Generate Reports, IonQuant).  This first step generates a complete output for my review.  

I then collected a second dataset (n+1) that I want to combine with the first, so I cleared the raw file list, added only the new mzml files for n+1, and performed the partial workflow as follows:
2) MSFragger, MSBooster, Percolator, ProteinProphet

Then I queued the mzml from the original dataset n (in addition to n+1) and performed the following partial workflow
3) ProteinProphet, Generate Reports, IonQuant

I didn't encounter any errors and the output contains all results I expected, however, I'm wondering if my partial workflows are correct or if there is a more efficient way.  For example, can I leave off the first ProteinProphet in step 2 above?  

Also, I wasn't sure if there were any interactions between modules that would change results compared to a single analysis, for instance, MSBooster or Percolator being run in batches compared to processing the complete multi-set in one instance?

Thanks in advance for your advice.
Todd

**Comment by fcyu** [comment]
Hi Todd,

> I didn't encounter any errors and the output contains all results I expected, however, I'm wondering if my partial workflows are correct or if there is a more efficient way. For example, can I leave off the first ProteinProphet in step 2 above?

Yes, your approach is correct except you don't need to run ProteinProphet in the first step since it will be run with all data (n plus n+1) in the second step.

> Also, I wasn't sure if there were any interactions between modules that would change results compared to a single analysis, for instance, MSBooster or Percolator being run in batches compared to processing the complete multi-set in one instance?

As far as I can think of, MSFragger, MSBooster, and Percolator treat each mzML file individually. There is no interaction. But for ProteinProphet, FDR filtering and reporting, IonQuant, TMT-Integrator, Spec library generation, and DIA-NN, you need to have all files ready.

For PeptideProphet (if you enable it), it is a little tricky. If you perform closed search, PeptideProphet processes each file separately. But if you perform open or mass-offset search, PeptideProphet process all files together. Then, you need to have all files ready.

Best,

Fengchao

**Comment by enonimos** [comment]
Thanks Fengchao, this is very helpful.
Todd
