### ISSUE TITLE
Default MSFragger workflow. exit code:137 erro. 55GB of RAM memory

### ISSUE THREAD

**Issue by jiyoungyoun** [Nesvilab/FragPipe#810]
Hi, 

We received exit code 137 when searching ~72 Thermo Exploris raw files using default MSFragger workflow.
Fragpipe was using 55GB of available memory. Please see attached log file here. 

Is this due to large number of raw files searched at once? 

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.
[log_2022-08-26_12-22-25.txt](https://github.com/Nesvilab/FragPipe/files/9436318/log_2022-08-26_12-22-25.txt)
)

**Comment by jiyoungyoun** [comment]
We also see this message when launching Fragpipe in shell. Could this be related to failed database splitting (we do have python installed in config).

Aug 26, 2022 4:19:51 PM org.openide.util.ImageUtilities$CachedLookupLoader getLoader
WARNING: No interface org.openide.util.spi.SVGLoader instance found in ProxyLookup(class=class org.openide.util.Lookup$DefLookup)->[MetaInfServicesLookup[jdk.internal.loader.ClassLoaders$AppClassLoader@55054057], SingletonLookup[jdk.internal.loader.ClassLoaders$AppClassLoader@55054057]]
Aug 26, 2022 4:19:51 PM org.openide.util.ImageUtilities getIcon
INFO: No SVG loader available for loading jar:file:/home/ji-young/programs/fragpipe-18/lib/org-netbeans-swing-outline-RELEASE130.jar!/org/netbeans/swing/etable/columns.svg

**Comment by fcyu** [comment]
Exit code 137 means that there are not enough memory. 

FragPipe detects the free memory when it starts, and uses the value a little bit smaller than that for MSFragger (55 GB in your example). When the amount of free memory becomes smaller (due to, for example, other processes use some of the memory) but MSFragger still tries to allocate 55 GB, the system will stop MSFragger with exit code 137. To solve this problem, you can either increase your physical memory or manually set the memory value with a smaller one in FragPipe's workflow tab.

> We also see this message when launching Fragpipe in shell. Could this be related to failed database splitting (we do have python installed in config).

Those messages don't matter.

Best,

Fengchao
