### ISSUE TITLE
DIA analysis

### ISSUE THREAD

**Issue by tasos2310** [Nesvilab/FragPipe#815]
- Describe the issue or question:
Hi all,
I am trying to make a DIA analysis for a quantification of some samples. My input is Mzml files, I follow the workflow of DIA.speclib_Quant, and I tried two approaches in the spectral libraries. First by using an library taht prepared in the DIA-NN, and second in by generating the library with the fragpipe. The runs starts and run normally, but hours after when few thing seems that completed, I have an error after the MSBooster finish. I would like to ask you if the error related to my files, or is something wrong in the settings. 
Thank you in advance for your answer.
Best
Tasos

- Upload your log file
(If a log file hasn't been ge
[log_2022-08-30_12-22-21(2).txt](https://github.com/Nesvilab/FragPipe/files/9484017/log_2022-08-30_12-22-21.2.txt)
nerated, go to
[log_2022-09-02_02-28-38(1).txt](https://github.com/Nesvilab/FragPipe/files/9484013/log_2022-09-02_02-28-38.txt)
 the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Tasos,

First of all, there were spaces in your folder name, which would crash the tools.

For the error in the first log, it is because you didn't run MSFragger. Please load the workflow and do not make any unnecessary changes. Please also remove the spaces in your folder name.

For the error in the second log, it is due to the spaces in your folder name.

Best,

Fengchao
