### ISSUE TITLE
Identification of peptides with two modifications at same AA

### ISSUE THREAD

**Issue by michaelsteidel86** [Nesvilab/FragPipe#817]
In TMT labeled data I took note that Fragpipe (default settings) does not identify peptides showing N-terminal methionine oxidation + TMT labeling (both mods variable in default). In contrast, I was able to match these kind of peptides using alternative search engines.

Is Fragpipe even capable to match peptides showing multiple mods at same AA?

Thanks
Michael

**Comment by fcyu** [comment]
Of course you can search both oxidized methionine and TMT labeling together because they are on **different** sites! Oxidation is on M no matter if it is at N-terminus or not, but TMT labeling is on N-terminus. You can use the following settings. Please adjust the TMT mass if you are not using TMT 10.
![image](https://user-images.githubusercontent.com/6926299/188474269-09c38b3e-fcf3-464d-9400-a9aa86c6c2c8.png)

> Is Fragpipe even capable to match peptides showing multiple mods at same AA?

MSFragger, which is the tool doing database search in FragPipe, can, but the downstream tools, Philosopher, won't be able to display two variable modifications in its tsv reports. Thus, we hide this option in FragPipe. If you are interested in, please check the option here: https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#allow_multiple_variable_mods_on_residue

On the other hand, you can always find a way to avoid two variable modifications on the same site by adding one more variable modification with the summed mass.

Best,

Fengchao
