### ISSUE TITLE
IonQuant MBR avdance options

### ISSUE THREAD

**Issue by lyons89** [Nesvilab/FragPipe#858]
Hello FP team,

I've got 20 unlabeled samples that I'm searching using LFQ-MBR method and I'm hoping I can get less missing values by playing around with the MBR options, specifically the MBR RT tolerance. Would increasing the time on the RT tolerance benefit me at all or if it added more noise would the FDR be able to correct for it?

Best,
Scott

**Comment by fcyu** [comment]
Hi Scott,

I don't think increasing the RT tolerance will significantly reduce the missing values. 

You can try reducing `min scans` from 3 to 1 or 2. You can also use the `intensity` column rather than the `maxlfq intensity` column because that is from top-N algorithm which is supposed to have less missing values but worse precision.

Best,

Fengchao

**Comment by lyons89** [comment]
Hey FengChao,

Thank you very much for the suggestion. Saved me time going through and testing out different combinations. 

Best,
Scott
