### ISSUE TITLE
Diagnostic ions/neutral losses for modifications

### ISSUE THREAD

**Issue by lewotre** [Nesvilab/FragPipe#861]
Dear MSFragger team,

Thanks for developing this nice piece of software!
I'm looking into two modifications in the same LC-MS/MS run and I know they have specific diagnostic ions and neutral losses that  can be assigned to them. Is there a way to search with these specifically for the modifications, or could this be implemented? 

Also, I have searched for diagnostic ions/ neutral losses, using the labile search option, however, after looking viewer to the spectra, they weren't annotated, is this how it's supposed to be or am I doing something wrong?

Thanks in advance,
Wouter

**Comment by dpolasky** [comment]
Hi Wouter,
We are planning to implement specific diagnostic ion <-> modification pairs soon but have not done so yet, so currently all modifications are considered when diagnostic ions are found, and searched with the same neutral losses. A possible workaround in the meantime is to run two separate searches and combine the results (with iProphet, for example), depending on how differently the modifications behave. 

You're right that the visualization tool does not show custom diagnostic ions yet, but that's another thing we'd like to add soon. You can show neutral losses (fragment remainder ions) using the "change modification" option in the Tools menu. If you set the modification mass to whatever mass remains on the peptide (or a negative value if part of the side chain is lost with the modification), it will show all fragment ions with that mass/neutral loss.  

Best,
Dan

**Comment by RMeelker** [comment]
Dear MS Fragger team, 

I would like to issue a follow-up on this thread. I am also interested in neutral losses and diagnostic ions of specific PTMs. Does your earlier advice still apply or is there any new feature I could try?

Looking forward to your reply.
Best,
Rebecca

**Comment by dpolasky** [comment]
Hi Rebecca,
This is still on our to-do list, but I am optimistic it will be getting done in the relatively near future. Stay tuned!

Best,
Dan

**Comment by antdit** [comment]
Hi Dan,

it's great to see so much development happening on the PTM side of things. I was wondering if you are also planning to implement workflows that allow different diagnostic ions/remainder ions dependent on the modified amino acid but for the same modification. I am thinking specifically about phosphorlyation on Y vs. S/T where for ph-Tyr peptides a specific diagnostic ion can be used (immonium ion at 216.04) to confidently say it's phosphorylated on the tyrosine. Similarly, especially for TMT-labeled peptides, ph-Tyr peptides often show a neutral loss of ~80Da rather than ~98 Da. I guess one can do the workaround that you proposed previously with two different searches that then need to be consolidated and merged afterwards but it would be better to have them in one search. 
Thank you!

Antje

**Comment by dpolasky** [comment]
Hi Antje,
Yes, we are planning to implement modification (mass offset)-specific ions to allow this kind of search and filtering. It is not ready yet, but I will post here when it is finished.

Best,
Dan

**Comment by dpolasky** [comment]
Support for pairing specific diagnostic ions, fragment remainder ions, and/or peptide remainder ions to specific modifications is now available in MSFragger 4.1 and FragPipe 22, using the detailed mass offset mode in MSFragger.
