### ISSUE TITLE
MSStat.csv Intensity Column

### ISSUE THREAD

**Issue by lolaakinlaja** [Nesvilab/FragPipe#862]
Hello, I am wondering if there is a quick way to specify which intensity is populated in the MSStat.csv file. I.e. if I want to use the MaxLFQ intensities, for example, instead of the raw intensities, for downstream differential expression analysis, is that possible to adjust for the MS Stats file?
Thanks

**Comment by fcyu** [comment]
MSstats.csv contains the ion-level intensities, which is the starting point of all other levels' intensities. They are raw intensities because MSstats has its own algorithm to normalize and aggregate the intensities. I don't think you want any artificial adjustment before running MSstats, otherwise, it might break some assumptions.

Best,

Fengchao

**Comment by lolaakinlaja** [comment]
Thank you!
