### ISSUE TITLE
error while adding decoys to a database

### ISSUE THREAD

**Issue by JoergDoellinger** [Nesvilab/FragPipe#863]
Dear FrapPipe Team,

I have downloaded a fasta file from Uniprot (all entries of the genus Vibrio in the Knowledgebase). When I try to add decoys in Fragpipe I receive the following error: 

java.lang.IllegalStateException: Something happened during database update
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
	... 1 more

What does that mean?

Best regards

Joerg

**Comment by fcyu** [comment]
Can you send the text in the console of Run tab?

Thanks,

Fengchao

**Comment by JoergDoellinger** [comment]
[log_2022-10-20_15-47-45.txt](https://github.com/Nesvilab/FragPipe/files/9830663/log_2022-10-20_15-47-45.txt)
Dear Fengchao,

please find the log file attached to this message.

Thanks,

Joerg

**Comment by fcyu** [comment]
Hi Joerg,

Thanks for your log. Could you also send me the `C:\Users\Doellingerj\Desktop\Diagnostik\Databases\uniprot-vibrio_2022.10.13.fasta` file?

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Joerg,

Your fasta file has been well received!

I ran the commands in the console and it worked (see the attached screenshot). The reasons of FragPipe crashing are that 1) your fasta file is really big (601 MB). Philosopher took ~6 min to finish adding decoys; 2) FragPipe has a 1 min timeout. If Philosopher took more than 1 min, FragPipe would stop it.

I guess we might need to increase the timeout period to, say, 10 min, since several users have reported this issue.

![image](https://user-images.githubusercontent.com/6926299/196973949-86cd7573-4803-4211-8562-319fcd1dd3c1.png)

Best,

Fengchao

**Comment by fcyu** [comment]
Fixed in https://github.com/Nesvilab/FragPipe/commit/5faec0b1c9664b06650ef2f74ac2ab0e51f8f4b3

**Comment by mart5176** [comment]
Hi @fcyu,

Has this fix been implemented into the current version of FragPipe? If not, is there a way I can implement it into my version to avoid this crash? 

Thanks,
Richard

**Comment by fcyu** [comment]
Hi Richard,

We are going to release a new version soon. If you don't want to wait, can you download the pre-prelease versions from https://www.dropbox.com/sh/22vh8lmala2l8hs/AAC7lLx8Qk8iF0n2YGAWfOtJa?dl=0 ?

You need to use all new FragPipe, MSFragger, IonQuant, and Philosopher.

Best,

Fengchao

**Comment by mart5176** [comment]
Awesome, Fengchao, thank you so much!

Best,
Richard
