### ISSUE TITLE
Mass Offsets WorkFlow - single customized mass shift PTM dependent file

### ISSUE THREAD

**Issue by TomClarkMassSpec** [Nesvilab/FragPipe#869]
Hello! 

I have a (feature?) request for the workflow: mass offset-common PTMs. I've done lots of open searches for exploring the possible mods and of course the closed searches. I need localized data for this application so in turning to the mass-offsets method, the program works well but there is a dependence on Unimod or a common PTMs file that I'd like to circumvent. It does as it says in the paper (PTM-Shepherd: analysis and summarization of post-translational and chemical modifications from open search results, Geiszler, et. al., 2020) and goes to 'common mods' first and if it's not satisfied, it turns to the custom file set I've set in PTM Shepherd. UNIMOD has a lot of errors and additionally there are mods that don't apply to my sample and these false PTM hits decrease the chances of finding mods that are real (I'm aware of the other side of the coin here). Is there a way or a file I can replace to that it always points to my custom file for a mass offset-common PTMs like workflow?

- And while I'm here, and hopefully this doesn't get people to hate me, is it possible to have a future feature request of selecting PTM annotation tolerance under Shepherd on the ppm scale (instead of Da).

Thank You,
Tom

**Comment by fcyu** [comment]
Hi Tom,

Have you tried the `custom annotation file` in the PTM tab?

As to the PTM annotation tolerance, if PTM-Shepherd supports it, I can add it to FragPipe.

Best,

Fengchao

**Comment by danielgeiszler** [comment]
The custom annotation file should give you what you’re looking for. I’ll upload the existing files in the documents so that it’s easier to format and write an explanation somewhere.

For the annotation tolerance, are you referring to the values written to the psm.tsv?

**Comment by TomClarkMassSpec** [comment]
Hi Fengchao,

Yes, I use the custom annotation file. I just ran a double check to make sure of everything.

For a few minutes I thought I had sorted it, as when I open a default mass offsets workflow, I was expecting it to open all the settings on the subsequent tabs but the "PTM" tab had defaults for "open" loaded. Upon changing this to "offsets", this does now set the global mod summary to PTMs from the custom annotation file. In either case there is a PTM-Shepherd extended output folder. That folder does contain a tsp with the PTMs assigned from the custom annotation folder but does not have localization information beyond localization counts.

But the peptide, protein and 'project_name'.tsv files all take their PTMs from another source. The paper does state "
Detected peaks are iteratively annotated using entries from the Unimod (retrieved: 2 Oct 2019)(13) modification database (including single residue insertions and deletions and isotopic peaks), supplemented with a user-specified list of mass shifts". So in that respect the software is doing what it says. But the it also reads, "Some exceptionally rare or protocol-based modifications (e.g., O18 labeling, N15 labeling) that regularly confounded annotation were removed". which I also see. 

Pep/Prot Localization Information: I think I have to build a script to cross reference the PTM from within PTM Shepard folder and at least two of other the tsv files to get localization by mass offset method? 

PTM type assignment: I know this can be quite complex so I am wondering if there is a file I can swap to short circuit the shifts to point exclusively to one custom list?

Thank You,
Tom

**Comment by TomClarkMassSpec** [comment]
Hi Daniel,

Your answer tipped me off to the fact that the psm file is updated with the mods from the file as hoped. I incorrectly assumed the peptide and protein files would derive from the psm file also, and that the only different was inference and filtering. I can work with the psm file.

Thank You,
Tom

**Comment by danielgeiszler** [comment]
>For a few minutes I thought I had sorted it, as when I open a default mass offsets workflow, I was expecting it to open all the settings on the subsequent tabs but the "PTM" tab had defaults for "open" loaded. Upon changing this to "offsets", this does now set the global mod summary to PTMs from the custom annotation file. In either case there is a PTM-Shepherd extended output folder. That folder does contain a tsp with the PTMs assigned from the custom annotation folder but does not have localization information beyond localization counts.

PTM-Shepherd localization can be found if you check the extended output option, but it’s mainly intended for internal use. We recommend that you use the MSFragger localization that is contained within the psm.tsv (and depending on your settings propagated through to the peptide and protein tables). This is the same algorithm implemented in PTM-Shepherd. Note that neither PTM-Shepherd nor MSFragger uses Unimod localization information, which was key to multiple discoveries in that paper (thank you for reading it before posting, by the way!).

I’m currently implementing a better localization algorithm which should be available in a month or so. I can notify you when there’s a demo version available.

>But the peptide, protein and 'project_name'.tsv files all take their PTMs from another source. The paper does state " Detected peaks are iteratively annotated using entries from the Unimod (retrieved: 2 Oct 2019)(13) modification database (including single residue insertions and deletions and isotopic peaks), supplemented with a user-specified list of mass shifts". So in that respect the software is doing what it says. But the it also reads, "Some exceptionally rare or protocol-based modifications (e.g., O18 labeling, N15 labeling) that regularly confounded annotation were removed". which I also see.

All of these tables are produced before PTM-Shepherd acts on them. PTM-Shepherd only works with and modified the psm.tsv tables. I’m not sure where the modifications in that list are coming from. I’d guess they’re coming from philosopher? @fcyu  @prvst 

I also have plans to work on output further up the pipeline so that changes are propagated through it, but it’s not the highest priority change at the moment.

>Pep/Prot Localization Information: I think I have to build a script to cross reference the PTM from within PTM Shepard folder and at least two of other the tsv files to get localization by mass offset method?

For pep/prot localization, this is a bit outside the scope of PTM-Shepherd at the moment. It would require some changes to the pipeline to get this up and running via that avenue. Maybe this is something we can work out between how IonQuant and PTM-Shepherd interact @fengchao?

>PTM type assignment: I know this can be quite complex so I am wondering if there is a file I can swap to short circuit the shifts to point exclusively to one custom list?

Is this about the psm.tsv, peptide.tsv, and protein.tsv tables? If so, I think this is a philosopher question. As I’ve started working with the data as an end user, I’ve realized there are issues here that make the workflows pretty complicated to use. I’m working on simplifying this so that there aren’t so many partially overlapping/confusing parameters between different tools. Sorry you aren’t doing this analysis a year from now, Tom!

**Comment by danielgeiszler** [comment]
> Hi Daniel,
> 
> 
> 
> Your answer tipped me off to the fact that the psm file is updated with the mods from the file as hoped. I incorrectly assumed the peptide and protein files would derive from the psm file also, and that the only different was inference and filtering. I can work with the psm file.
> 
> 
> 
> Thank You,
> 
> Tom

That's a fair assumption. Unfortunately, they are derived from the psm files. But they're all produced at the same time, THEN PTM-Shepherd is executed. PTM-Shepherd only manipulates the psm.tsv.

Like I said above, I'm working on getting the results propagated to all the tables, but I have a feeling it won't be available for quite some time.

**Comment by TomClarkMassSpec** [comment]
I now know to work with the psm file. That's enough for now. 

Hopefully we can connect again in a year with some papers.

Thanks again, Tom
