### ISSUE TITLE
Philosopher 4.5.1-RC21: downloading UP000002485 failed for unknown reasons

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#878]
Following commands can reproduce the bug

```shell
philosopher.exe workspace --clean
philosopher.exe workspace --init
philosopher.exe database --id UP000002485 --reviewed
philosopher.exe workspace --clean
```

Output in the console
```shell
INFO[15:42:16] Executing Database  v4.5.1
WARN[15:42:16] contaminants are not going to be added to database
INFO[15:42:16] Fetching Schizosaccharomyces pombe (strain 972 / ATCC 24843) (Fission yeast) database UP000002485
2022/11/04 15:42:17 EOF
```

Best,

Fengchao

**Comment by prvst** [comment]
It's a known issue caused by the UniProt API changes, no workaround for the moment. The solution for now is to grab the file from their website, and add the contaminants with Philosopher

**Comment by tobiasko** [comment]
We are also experiencing quite some broken downloads, but often it is not clear to us why certain DBs can be downloaded while other proteome IDs fail. @prvst Could you summarise which downloads are problematic and why? Is the remote service not available at all times? The above example

https://www.uniprot.org/proteomes/UP000002485

Is a reference proteome from a common model organism. Nothing exotic or something with a "strange" status.

Comment: Grabbing files from the webpage sounds like an easy workaround, but for a scripted job this a bigger issue.

**Comment by guoci** [comment]
@prvst I think the query string is incorrect, please see my PR.
https://github.com/Nesvilab/philosopher/pull/399

**Comment by prvst** [comment]
@tobiasko The recent UniProt API changes are really strange, to put it nicely. It took me a while to figure this out, especially because all these were undocumented. Basically, the previous way to query the API doesn't work anymore, and now you have to query the proteomes in different ways depending on the content of the reference proteome you're trying to get. Proteomes with official references, proteomes with only Swiss-Prot sequences, proteomes with only Tremble, and proteomes with both now need to be accessed in different ways. The interesting thing is that there is no pragmatical way to know ahead of the query which one is the case for the organism you are interested in. The only way I know so far is through the website. Because of this, I'll have to break down the way how Philosopher downloads the proteomes into separate parts, check them individually, and them merge them. This will require some changes, hence the delay in having them available for now.

@guoci Thanks, but see above. Your changes will fix one scenario and brake others.

**Comment by prvst** [comment]
I'm releasing some last-time fixes today, and then I'll prepare the changes to work around the UniProt API issues. For now, my suggestion is that if you are working with non-canonical model organisms, for example, use the website to fetch the sequences.

**Comment by prvst** [comment]
Fixed. Added to v5.0.0
