### ISSUE TITLE
Feature request: Detailed reporting of identified fragment ions

### ISSUE THREAD

**Issue by StefanTenzer** [Nesvilab/FragPipe#885]
Dear Fragpipe Team,
thanks for your amazing work! 
We are currently trying to extract information at fragment ion level from FragPipe results.
Ideally, we would need a report file that provides addition information at the fragment ion level for each identified PSM (in the psm.tsv) , i.e. observed product_MZ, theoretical_product_MZ, Intensity, Annotation.
This file will likely be relatively large in size, but ideal for e.g. visualization of the identified spectra.

Best regards,

Stefan Tenzer

**Comment by fcyu** [comment]
Hi Stefan,

Thank you very much for your suggestion. If you want to visualize the annotated spectra, you can open the FP-PDV window by clicking "Open visualization window" in the "Run" tab.

**Comment by fcyu** [comment]
I have implemented the feature to report the matched fragments. Let MSFragger generate the `tsv` report will have those two new columns. If you want to try the pre-released version, please send an email to yufeATumich.edu (replace `AT` with `@`).

Currently, there are some limitations

1. The reported fragments are not exactly the one used in the scoring because MSFragger does not record such information (to be fast). I let it "re-match" the fragments when generating the report.
2. The fragments are deisotoped by default, so the reported matches only have singly charged. Disabling the deisotoping in the database search will have doubly charged fragments being matched, but the sensitivity is sub-optimal.
3. It only supports closed search now, but I will extend it to open and mass-offset search in the future.

Best,

Fengchao
