### ISSUE TITLE
Silac Arg6-Lys6 Same label

### ISSUE THREAD

**Issue by Skourtis** [Nesvilab/FragPipe#896]
Hi, 

In the past Andromeda struggled with Arg and Lys with the same labels e.g. Arg6; Lys6. This was mentioned by Juergen in the MQ discussion google group here, saying:  
"MaxQuant assumes that the lysines are labeled differently from the arginines.
For instance, labeling both arginine and lysine with six 13C atoms
will cause problems. "
https://groups.google.com/g/maxquant-list/c/MFCrqnA9he0
" If you use six 13C for both there is no way to tell if it is
a lysine or arginine containing peptide just based on the mass
difference between SILAC partners. However, MaxQuant will try to
determine the lysine/arginine content and will be wrong in 50% of the
cases." 
Of course if there is a missed tryptic cleavage  and the peptide contains 1 K and 1 R but only 6 shift, it's impossible to know which is labelled. But it is important for MSFragger?

Is this a problem for MSFragger as well?
Thank you,
Savvas

**Comment by fcyu** [comment]
Hi Savvas,

Thank you very much for your message.

If I understand MaxQuant's algorithm correctly, it pairs heavy and light (For simplicity, let's assume there is no medium labeling since adding medium won't affect anything in this discussion.) MS1 features before doing any MS/MS search. I think this is the cause of the issue you mentioned. 

As to MSFragger (database search) and IonQuant (SILAC quantification), we perform database searching before SILAC pairing. So, IonQuant knows if it is a Arg6 or Lys6. BUT, use "modified peptides without labels + label count with mass diff" to identify a peptide because there are use cases that the label can't be localized. Also, when performing re-quantify, we don't have the MS/MS search for the complementary peptide. So, in a word, IonQuant also don't distinguish Arg6 and Lys6 although theoretically it can.

Best,

Fengchao
