### ISSUE TITLE
IonQuant no longer generate *_quant.csv files because they are useless intermediate files

### ISSUE THREAD

**Issue by wyu** [Nesvilab/FragPipe#923]
Hi, I'm trying to get a LFQ workflow running for DDA run from our TimsTOF instrument. However, the output from IonQuant seems to be missing, even though the log file indicated a success IonQuant step.

What I'm looking for is *_quan.csv for each of the run that I usually get from my Thermo raw files. Are we expecting the same file from the TimsTOF run?

By the way, the Bruker native library shipped with the latest MsFragger 3.6 is not working. I had to bring back the version from v3.5 in order to complete the IonQuant step.

Thanks!
Wen

[log_2022-12-11_17-46-47.txt](https://github.com/Nesvilab/FragPipe/files/10204560/log_2022-12-11_17-46-47.txt)
- Describe the issue or question:

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by wyu** [comment]
Hi, I need to correct myself that the same problem is happening for the Thermo raw file with the latest IonQuant (v1.8.9).
[log_2022-12-11_13-58-34.txt](https://github.com/Nesvilab/FragPipe/files/10204652/log_2022-12-11_13-58-34.txt)

In the prev version (v1.8.0), the Thermo raw files yield _quant.csv as expected. 

Thanks!
Wen

**Comment by fcyu** [comment]
Hi Wen,

I think you got the questions wrong at the beginning. And then, tried to "fix" the problem in the wrong direction, which makes it looks complicated. Actually it is very simple.

> Hi, I'm trying to get a LFQ workflow running for DDA run from our TimsTOF instrument. However, the output from IonQuant seems to be missing, even though the log file indicated a success IonQuant step.
> What I'm looking for is *_quan.csv for each of the run that I usually get from my Thermo raw files. Are we expecting the same file from the TimsTOF run?

IonQuant no longer generates `*_quant.csv` files. They are intermediate files generated by old versions of IonQuant. The entries in those files are not 100% useful, and accurate. To prevent any misleading, I removed those files in the latest version. Please use `psm.tsv`, `ion.tsv`, `peptide.tsv`, `protein.tsv`, `*_label_quant.tsv`, and `combined_*.tsv` files.

> By the way, the Bruker native library shipped with the latest MsFragger 3.6 is not working. I had to bring back the version from v3.5 in order to complete the IonQuant step.

I see no error messages regarding this issue from your log files. Can you upload the log file with the error message saying IonQuant couldn't read Bruker's files?


> Hi, I need to correct myself that the same problem is happening for the Thermo raw file with the latest IonQuant (v1.8.9).
[log_2022-12-11_13-58-34.txt](https://github.com/Nesvilab/FragPipe/files/10204652/log_2022-12-11_13-58-34.txt)
> In the prev version (v1.8.0), the Thermo raw files yield _quant.csv as expected.

Again, IonQuant no longer generates `*_quant.csv` files. They are intermediate files generated by old versions of IonQuant. The entries in those files are not 100% useful, and accurate. To prevent any misleading, I removed those files in the latest version. Please use `psm.tsv`, `ion.tsv`, `peptide.tsv`, `protein.tsv`, `*_label_quant.tsv`, and `combined_*.tsv` files.


> Hi, looks like we have a temp workaround on this problem:
> Download the temp patch of fragpipe jar as mentioned in another thread and replace the copy in the lib folder
> Remove the ionquant 1.8.9 from the tools folder, and point the active version to 1.8.0 in the FragPipe GUI
> replace the "ext/bruker" folder with the one from MsFragger 3.5 to avoid the error about Bruker native library.

These "workaround" is not needed because you got the questions wrong. Please do not mislead users.

Best,

Fengchao

**Comment by wyu** [comment]
Hi Fengchao,

Thanks for looking into the issue!  

We're depending on some of the columns from the _quan.csv" file for our data QC pipeline. Do you know if they can be found in the files you mentioned? The ion, psm, and peptide files mostly contain the "intensity" information as I can see. 

Thanks!
Wen

retention_time_end, retention_time_begin, apex_retention_time, retention_time
We're not aware of the changes in the file output

**Comment by fcyu** [comment]
Hi Wen,

No, they are not in the tsv files.

Best,

Fengchao

**Comment by wyu** [comment]
Hi Fengchao,

Thanks for the clarification! Is there a way to have those files back in the future update? We're using FragPipe in headless mode for our data QC pipeline as it's much faster than MaxQuant.

Wen

**Comment by fcyu** [comment]
Hi Wen,

I would like to keep this issue open until I implement the requirement. An open issue can keep me noted.

Thanks,

Fengchao

**Comment by fcyu** [comment]
The latest IonQuant write the retention time and ion mobility information to the `combined_ion.tsv` file.

Best,

Fengchao
