### ISSUE TITLE
FragPipe-PDV viewer glitching issues

### ISSUE THREAD

**Issue by tobimaile** [Nesvilab/FragPipe#929]
Hi all,

I just upgraded to FragPipe 19.0 and an issue we had occasionally with 18.0 is now a constant glitch:

When opening FP-PDV, the window glitches out by overlaying additional copies of window segments within the window frame. Adjusting window size or managing to press any functional area within the remaining functional window areas restores the glitch for a few seconds before it glitches out again. We observed this in 18.0 as well, but usually resizing the window fixed it for several minutes up to the entire session and basic viewer functions were operational.

I am not certain on how to fix this, we installed both FragPipe 19.0 and JRE 9 without issues on our machine.

Best,
Tobi

**Comment by KaiLiCn** [comment]
Hi Tobi,

Sorry for the inconvenience. But I didn't re-generate this bug. If it's ok, could you please share your raw data and corresponding result folder with me?

Best,
Kai

**Comment by anesvi** [comment]
Hi Tobi
That's a bit strange indeed, no one else reported it. If you are going done nonstandard searches, please share some data with Kai as he asked. But if standard, maybe it is something else, screen resolution related... do you have another computer to try?
Alexey

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tobimaile** [comment]
Hello all,

Thank you for getting back to me so quickly, much appreciated!

The data I ran so far is standard DDA and also PRM files on Bruker .d files. I loaded both type of files up on version 18.0 and 19.0 and in both cases, windows for FP-PDV and the main Fragpipe window glitched out.
I then updated our Nvidia graphics driver to the most recent version (527.56, 12/08/2022), but the problem persists. 
We run everything on a 64bit Windows system on 5120x1440 resolution on a Samsung Galaxy G9 Ultrawide monitor for better visibility (helps a lot with Skyline as well), backed up by a 3090 RTX card. The glitches I got after the update are a bit different however, with the main Fragpipe window being unaffected and the FP-PDV window becoming unresponsive. To exit the window, I have to end the process via TaskManager under the OpenJDK Platform binary folder.

On another note, old data can not be opened in 19.0 in my hands. I get an error message after opening FP-PDV that tells me that no valid manifest file in my results folder. Is this due to the missing FP-PDV.db file in these older datasets?

**Comment by KaiLiCn** [comment]
Hi Tobi,

Could you share your raw file and corresponding result folder with me? It will help us to figure out this issue. You could share it via Google Drive or Dropbox. Or you can send a private link to my email: lkai@umich.edu

For the old data, since we change a lot of result files in 19.0, the old data can not be loaded in 19.0. However, you can open it in 18.0 with the new FP-PDV. There are a few steps to do that.

1. Download the FP-PDV which is compatible with 18.0: https://github.com/Nesvilab/FP-PDV/releases/download/V1.0.3/FP-PDV-1.0.3.jar
2. Open your FragPipe 18.0 folder -> tools -> FP-PDV folder as follow:
 ![image](https://user-images.githubusercontent.com/29800230/207977689-202c3aaa-4612-447c-88a9-f74c36b9475f.png)
3. Delete the .jar file and put downloaded .jar file in the folder.
4. Go back to FragPipe 18.0 and open the visualization again.

Then you can load the old version results in FP-PDV (with new features).

You can follow updates of FP-PDV here: https://github.com/Nesvilab/FP-PDV

Please let me know if you meet any difficulties.

Kai

**Comment by tobimaile** [comment]
Hi Kai, I will contact you via email about files etc.

I also tried replacing the jar-file but I do end up on an infinite loading loop when I try to open FP-PDV on Fragpipe 18.0. replacing the jar file with the original works just fine and the data loads into FP-PDV.
