### ISSUE TITLE
Usage of MaxLFQ intensity and intensity, and how to look for the unique peptides?

### ISSUE THREAD

**Issue by SharmaGautam1** [Nesvilab/FragPipe#936]
- Describe the issue or question:
Hi,
I have four questions that need your support for clarification:
1. When to enable MaxLFQ and when not? If we enabled MaxLFQ, then what does it mean? When to use MaxLFQ  intensity and just intensity for analysis? Under what circumstances should we go with either maxLFQ intensity and intensity?
2. How can we know that the output carried in fragpipe out has more than 2 unique peptides? In Proteome Discoverer (PD), we set the analysis to be more than two unique peptides. In fragpipe, how to enable such things?
3. In the combined_protein.tsv file, what does the Indistinguishable Proteins column mean?
4. Is there any source which also explains about the output file columns?

---
Best Regards
Gautam Sharma

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Gautam,

> When to enable MaxLFQ and when not? If we enabled MaxLFQ, then what does it mean? 

You can always enable MaxLFQ intensity since both intensity and MaxLFQ intensity will be reported. If not enable MaxLFQ, there will be only intensity.

> When to use MaxLFQ intensity and just intensity for analysis? Under what circumstances should we go with either maxLFQ intensity and intensity?

It depends on your data. One of the common case is when you only have a few experiments. In this case, some MaxLFQ intensities would be zero due to the algorithm but the intensities would not. Another case is AP-MS where there are big intensity ratios.

> How can we know that the output carried in fragpipe out has more than 2 unique peptides? In Proteome Discoverer (PD), we set the analysis to be more than two unique peptides. In fragpipe, how to enable such things?

I don't think this information is in the output files. You might add it in the future release. For now, you need to get this information in your downstream analysis.

> In the combined_protein.tsv file, what does the Indistinguishable Proteins column mean?

They are proteins that are equally supported by the evidence and cannot be distinguished from the identification in the "Protein" column

> Is there any source which also explains about the output file columns?

Yes, here: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html

Best,

Fengchao

**Comment by SharmaGautam1** [comment]
Thanks for the quick reply and the clarification.

---
Best Regards
Gautam Sharma

**Comment by fcyu** [comment]
You are welcome!

Best,

Fengchao
