### ISSUE TITLE
Special characters in the protein header breaks IonQuant

### ISSUE THREAD

**Issue by blucherxeus** [Nesvilab/FragPipe#949]
Hi, Dear FragPipe team
I was using preset workflow nonspecific HLA to analyse timsTOF data, i chose IM-MS when i loaded raw file following "Using FragPipe".
When i choose "Quant (MS1)-LFQ" with default parameters, FragPipe reports an error as log file shows. If i do not use Quant (MS1), everyting works properly.
Am i doing somthing wrong?

Thank you,
Wang.

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].
[log_2022-12-30_18-28-03.txt](https://github.com/Nesvilab/FragPipe/files/10333906/log_2022-12-30_18-28-03.txt)
txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by fcyu** [comment]
Hi Wang,

I couldn't reproduce the issue. Could you please upload the .d folders and all files in the result folders to https://www.dropbox.com/request/hDKoM6h5coARZx1L2Qt5 ?

Thanks,

Fengchao

**Comment by blucherxeus** [comment]
Hi Fengchao

I have uploaded all files to dropbox, thank you

Thanks
Wang

**Comment by fcyu** [comment]
Hi Wang,

Thank you very much for your files.

I found the cause: the protein `D8_Neo_WES_$CODING_CHANGE_c.A2726T%PASS@CADPS_p.E909V` breaks IonQuant because `@` is used for special purpose by the program. I don't think the protein header is allowed to have special characters, such as `$%@_`.

Can you modify your fasta file and try again?

Thanks,

Fengchao

**Comment by blucherxeus** [comment]
Hi Fengchao

Thank you for your help.
I`ll change my fasta file and try again. 

Best
Wang
