### ISSUE TITLE
FragPipe Percolator setting

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#951]
Greetings,

I am trying to change some parameters of percolator via FragPipe validation tab. I am interested to use the command of:
**--fido-gridsearch-mse-threshold** <float> – Q-value threshold that will be used in the computation of the MSE and ROC AUC score in the grid search. When I tried using the command of **--fido-gridsearch-mse-threshold 0.1**, did not observe any difference in output data compared to default percolator setting. 

I would like to increase my q-value in percolator to 0.1. Could you advise me on how to do it?

Regards,
Ben

**Comment by fcyu** [comment]
Hi Ben,

I think the fido options are for protein grouping in Percolator which 1) is not used by FragPipe; and 2) if you want to make it work in the standalone Percolator version, you need to add the additional protein grouping options.

BTW, please do not enable the protein grouping function in Percolator because 1) it is not used by FragPipe; and 2) it takes lots of time.

> I would like to increase my q-value in percolator to 0.1. Could you advise me on how to do it?

I don't think it will change the result much since FragPipe uses Philosopher to filter the FDR. Percolator is just for PSM rescoring.

Best,

Fengchao
