### ISSUE TITLE
interact-[dataname].pep.xml files from Fragpipe 19.1 can not be uploaded in Skyline

### ISSUE THREAD

**Issue by tobimaile** [Nesvilab/FragPipe#969]
Hi all,

Thank you for your continuing work on MSFragger! 

After the re-introduction of .mgf files in 3.7, I ran into a new problem with uploading files into Skyline:

While interact-.pep.xml files from 18.0 upload just fine, interact-.pep.xml files from 19.1 now have an error message in Skyline stating that there is an "Error getting a score type for this file" with a subsequent message stating that the corresponding .mgf file is required. The corresponding .mgf files are present in the directory and should be found. However when I continue on Skyline for the .mgf file search, only the .mzML files show up in the Skyline loader. Looks like something is wrong with the current .mgf files?
When I load interact-.pep.xml files from 18.0, this error message does not appear.

Interestingly, the regular .pepxml files upload just fine compared to the interact-.pep.xml files in all versions of Fragpipe.

Best,
Tobi

**Comment by fcyu** [comment]
Hi Tobi,

I reproduced your observations. Furthermore, I found that using the *.pepXML file (the one without `interact-` as prefix), Skyline recognized it from X!Tandem, which is OK since MSFragger uses hyperscore, and worked well. It indicates that the uncalibrated.mgf is good. 

I guess some changes in interact-*.pep.xml file break Skyline. But, we did not make any big changes. I am not sure what breaks Skyline. I think it's time to create a tick to https://skyline.ms/project/home/support/begin.view . I can do that if that's OK

Best,

Fengchao

**Comment by fcyu** [comment]
interact-*.pep.xml files have the probability after rescoring (by PeptideProphet or Percolator), but *.pepXML files don't have it.

I have created a ticked to https://skyline.ms/announcements/home/support/thread.view?rowId=57930

Best,

Fengchao

**Comment by tobimaile** [comment]
Thank you for the update Fengchao!

Best,
Tobi

**Comment by fcyu** [comment]
FYI, there are some updates in the Skyline forum: https://skyline.ms/announcements/home/support/thread.view?rowId=57930

I think the ideal solution is changing Skyline to make it support MSFragger's new change. If they don't like this idea, I will see what I can do in MSFragger. Such as renaming the mgf to `_uncalibrated_uncalibrated.mgf`, but it looks awkward.

Best,

Fengchao

**Comment by fcyu** [comment]
We have integrated Skyline with FragPipe. People can let FragPipe generate Skyline files seamlessly now. Contact us if you want to try the pre-released versions.

Best,

Fengchao
