### ISSUE TITLE
Percolator (DIA-Umpire) throwing error with DIA files after splitting FAIMS CVs. 

### ISSUE THREAD

**Issue by TTCooper-PhD** [Nesvilab/FragPipe#988]
I have tested a single sample that has been fractionated offline with bRP and each injection is subjected to three FAIMS CV values while acquiring in DIA mode on Thermo Eclipse over 240 min gradient. Each CV-value has been generated as a mzML file. 

I am getting an error with Perculator but I am unsure how to interpret it. Would you please take a look?

Process 'Percolator' finished, exit code: -1073741819

Here is the log file:

[log_2023-01-30_23-56-25.txt](https://github.com/Nesvilab/FragPipe/files/10546545/log_2023-01-30_23-56-25.txt)

Thank you.

**Comment by fcyu** [comment]
Since we are not the developer of Percolator, I am not sure of the exact reason. But it seems that there is no ID in that file: `tc_29Jan2023_TrypLysC_FracH_120minLC_HCD_DIA_75_Q3_edited.pin`. Maybe should let Percolator to generate an empty file rather than crash.

Best,

Fengchao

**Comment by TTCooper-PhD** [comment]
> Since we are not the developer of Percolator, I am not sure of the exact reason. But it seems that there is no ID in that file: `tc_29Jan2023_TrypLysC_FracH_120minLC_HCD_DIA_75_Q3_edited.pin`. Maybe should let Percolator to generate an empty file rather than crash.
> 
> Best,
> 
> Fengchao

This is likely and expected, as from what I can tell this fraction/CV likely has little to no PSMs available. I am using the FragPipe GUI so would I need to change something under the Perculator tab?  Why do these files work with I select "DIA SpectLib_Quant"?

**Comment by fcyu** [comment]
The file having 0 IDs is `*_Q3` from DIA-Umpire, which has the lowest spectra quality (please read the DIA-U paper for details). For the `DIA_SpecLib_Quant` workflow, FragPipe uses MSFragger-DIA not DIA-Umpire, so it is less likely to have empty pin files.

Best,

Fengchao

**Comment by anesvi** [comment]
I looked at the log too

The issue is with Q2 and Q3 files
DIA-Umpire generates Q1, Q2, and Q3 files. Q2 files correspond to precursors detected with only 2 isotopes. Q3 are the files where pseudo-MS/MS spectra are assembled around precursors detected in MS2 scans (unfractionated precursors). Q3 and Q2 files have much fewer IDs than Q1 files.

I guess in this dataset, there were not enough high scoring IDs for Percolator in Q2 and Q3 files.
E.g:
Reading tab-delimited input from datafile tc_29Jan2023_TrypLysC_FracA_240minLC_HCD_DIA_35_Q2_edited.pin
Found 196 PSMs
or
Reading tab-delimited input from datafile tc_29Jan2023_TrypLysC_FracH_120minLC_HCD_DIA_75_Q3_edited.pin
Found 2 PSMs

I am not sure why so few IDs. I suspect it has something to do with FAIMS

Fengchao, we can probably print empty files.

But for now, you need to run just using Q1 files. In DIA-Umpire tab, uncheck Q2 and Q3 boxes
If you do not want to run DIA-Umpire again, do the following:

  1.  Select and load DIA_SpecLib_Quant workflow
  2.  load Q1,mzML files (from your previous run) and annotate them as DDA
  3.  Load DIA mzML files and annotate as DIA-Quant
  4.  RUN
FragPipe will build the library from the extracted Q1 mzML files and do DIA-NN quant from the full DIA files

Alexey

**Comment by fcyu** [comment]
Hi @TTCooper-PhD ,

We would like to debug this issue with the help of Lukas. Could you please share `tc_29Jan2023_TrypLysC_FracH_120minLC_HCD_DIA_75_Q3_edited.pin` with us? My email is yufe AT umich.edu.

Thanks,

Fengchao
